### PR TITLE
boost171: default to Python version 3.11; boost173: obsolete

### PR DESCRIPTION
**Pull request by MarcusCalhoun-Lopez**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS x.y
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [ ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by michaelld** [comment]
I have no objection to bumping the default Python version for Boost, assuming that the various Boost versions all work with this latest Python version ... let's see what the CI/QA does

**Comment by michaelld** [comment]
CI/QA/Checks failed ... maybe timeout do to taking so long? need to check to see what's going on there before committing this, even if it's nice and simple changes!

**Comment by michaelld** [comment]
The error for macOS 11 is `Error: Failed to destroot boost173: ln: /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_devel_boost173/boost173/work/destroot/opt/local/libexec/boost/1.73/lib/libboost_python27-mt.dylib: File exists`

**Comment by michaelld** [comment]
There are 30 or so errors, all of the rest being (I think) older Boost versions not being compatible with the default Python variant version ... for example:
```
./boost/python/object/make_instance.hpp:50:31: error: expression is not assignable
      Py_SIZE(instance) = offsetof(instance_t, storage);
```

**Review by michaelld — COMMENTED** [review]
Need to verify that older Boost work with Python311 ... I haven't tried ; from the look of the QA/CI/Check build log I'd say some aren't compatible. ... not sure if we want to try to patch them or just not allow them to use +python311 ... need to try these out to see if they do actually work & thus if the QA/CI/Check has issues

**Comment by reneeotten** [comment]
@michaelld what's the status of this?

**Comment by kencu** [comment]
Rene… this will need boost-by-boost individual testing and verification of each version.

I guess any of us can pick one version and sign off on it if it works with python 3.11. We should keep a list of the tests up here.

**Comment by reneeotten** [comment]
@mascguy @michaelld can you comment on what the plan is here? We should move to the default Python version, has the required testing been done. Or do we just merge this and fix whatever is broken... this PR has been open long enough now.

**Comment by mascguy** [comment]
> @mascguy @michaelld can you comment on what the plan is here? We should move to the default Python version, has the required testing been done. Or do we just merge this and fix whatever is broken... this PR has been open long enough now.

When this PR was first created, the various Boost 1.7x ports weren't defaulting to Python 3.11. But as of this writing, only two of those remain: 1.71 and 1.73. And given that the latter failed CI, let's drop that for now, and just update 1.71.

As for 1.73, a quick grep of the ports tree yields no dependent ports. And given that we need to start pruning older Boost versions anyway, let's start by dropping 1.73.

**Review by mascguy — APPROVED** [review]

**Comment by mascguy** [comment]
Update: It looks like `boost171` has some build issues that need to be fixed, for Python 3.11. So reverted back to 3.10 for now, until those are sorted out.
