### PR TITLE
libsoup: blacklist old Apple gcc, fix build on <10.7

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

`libsoup` 3.x does not build with gcc-4.2.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
With `gcc-4.2`:

```
In file included from ../libsoup-3.4.2/libsoup/soup-headers.h:10,
                 from ../libsoup-3.4.2/libsoup/auth/soup-auth.h:9,
                 from ../libsoup-3.4.2/libsoup/soup.h:11,
                 from libsoup/soup-enum-types.c:7:
../libsoup-3.4.2/libsoup/soup-message.h:18: error: redefinition of typedef ‘SoupMessage’
../libsoup-3.4.2/libsoup/soup-types.h:24: error: previous declaration of ‘SoupMessage’ was here
In file included from ../libsoup-3.4.2/libsoup/soup.h:11,
                 from libsoup/soup-enum-types.c:7:
../libsoup-3.4.2/libsoup/auth/soup-auth.h:15: error: redefinition of typedef ‘SoupAuth’
../libsoup-3.4.2/libsoup/soup-types.h:18: error: previous declaration of ‘SoupAuth’ was here
In file included from ../libsoup-3.4.2/libsoup/soup.h:16,
                 from libsoup/soup-enum-types.c:7:
../libsoup-3.4.2/libsoup/cookies/soup-cookie.h:26: error: redefinition of typedef ‘SoupCookie’
../libsoup-3.4.2/libsoup/soup-types.h:20: error: previous declaration of ‘SoupCookie’ was here
In file included from ../libsoup-3.4.2/libsoup/soup.h:17,
                 from libsoup/soup-enum-types.c:7:
../libsoup-3.4.2/libsoup/cookies/soup-cookie-jar.h:14: error: redefinition of typedef ‘SoupCookieJar’
../libsoup-3.4.2/libsoup/soup-types.h:21: error: previous declaration of ‘SoupCookieJar’ was here
In file included from ../libsoup-3.4.2/libsoup/soup.h:24,
                 from libsoup/soup-enum-types.c:7:
../libsoup-3.4.2/libsoup/hsts/soup-hsts-enforcer.h:15: error: redefinition of typedef ‘SoupHSTSEnforcer’
../libsoup-3.4.2/libsoup/soup-types.h:22: error: previous declaration of ‘SoupHSTSEnforcer’ was here
In file included from ../libsoup-3.4.2/libsoup/soup.h:26,
                 from libsoup/soup-enum-types.c:7:
../libsoup-3.4.2/libsoup/hsts/soup-hsts-policy.h:13: error: redefinition of typedef ‘SoupHSTSPolicy’
../libsoup-3.4.2/libsoup/soup-types.h:23: error: previous declaration of ‘SoupHSTSPolicy’ was here
In file included from ../libsoup-3.4.2/libsoup/soup.h:29,
                 from libsoup/soup-enum-types.c:7:
../libsoup-3.4.2/libsoup/soup-message-metrics.h:12: error: redefinition of typedef ‘SoupMessageMetrics’
../libsoup-3.4.2/libsoup/soup-types.h:25: error: previous declaration of ‘SoupMessageMetrics’ was here
In file included from ../libsoup-3.4.2/libsoup/soup.h:33,
                 from libsoup/soup-enum-types.c:7:
../libsoup-3.4.2/libsoup/server/soup-auth-domain.h:14: error: redefinition of typedef ‘SoupAuthDomain’
../libsoup-3.4.2/libsoup/soup-types.h:19: error: previous declaration of ‘SoupAuthDomain’ was here
In file included from ../libsoup-3.4.2/libsoup/server/soup-server.h:10,
                 from ../libsoup-3.4.2/libsoup/soup.h:36,
                 from libsoup/soup-enum-types.c:7:
../libsoup-3.4.2/libsoup/websocket/soup-websocket-connection.h:30: error: redefinition of typedef ‘SoupWebsocketConnection’
../libsoup-3.4.2/libsoup/soup-types.h:30: error: previous declaration of ‘SoupWebsocketConnection’ was here
In file included from ../libsoup-3.4.2/libsoup/soup.h:36,
                 from libsoup/soup-enum-types.c:7:
../libsoup-3.4.2/libsoup/server/soup-server.h:16: error: redefinition of typedef ‘SoupServer’
../libsoup-3.4.2/libsoup/soup-types.h:26: error: previous declaration of ‘SoupServer’ was here
In file included from ../libsoup-3.4.2/libsoup/soup.h:37,
                 from libsoup/soup-enum-types.c:7:
../libsoup-3.4.2/libsoup/server/soup-server-message.h:17: error: redefinition of typedef ‘SoupServerMessage’
../libsoup-3.4.2/libsoup/soup-types.h:27: error: previous declaration of ‘SoupServerMessage’ was here
In file included from ../libsoup-3.4.2/libsoup/soup.h:38,
                 from libsoup/soup-enum-types.c:7:
../libsoup-3.4.2/libsoup/soup-session.h:16: error: redefinition of typedef ‘SoupSession’
../libsoup-3.4.2/libsoup/soup-types.h:28: error: previous declaration of ‘SoupSession’ was here
In file included from ../libsoup-3.4.2/libsoup/soup.h:39,
                 from libsoup/soup-enum-types.c:7:
../libsoup-3.4.2/libsoup/soup-session-feature.h:14: error: redefinition of typedef ‘SoupSessionFeature’
../libsoup-3.4.2/libsoup/soup-types.h:29: error: previous declaration of ‘SoupSessionFeature’ was here
In file included from ../libsoup-3.4.2/libsoup/soup.h:46,
                 from libsoup/soup-enum-types.c:7:
../libsoup-3.4.2/libsoup/websocket/soup-websocket-extension.h:32: error: redefinition of typedef ‘SoupWebsocketExtension’
../libsoup-3.4.2/libsoup/soup-types.h:31: error: previous declaration of ‘SoupWebsocketExtension’ was here
ninja: build stopped: subcommand failed.
```

**Comment by mascguy** [comment]
As I reminded you several days ago - and let me say it again - include the Devel (and Upstream) ports if they exist!

**Comment by barracuda156** [comment]
> As I reminded you several days ago - and let me say it again - include the Devel (and Upstream) ports if they exist!

@mascguy Sorry, won’t miss this again.

**Review by mascguy — APPROVED** [review]

**Comment by barracuda156** [comment]
@mascguy Thank you!
