### PR TITLE
notmuch: Update to 0.29.1

### PR DESCRIPTION
**Pull request by rseichter**
The `Makefile` fix for which I provided a patch in the last port version has been accepted upstream and is included in release 0.29.1. The suggested `configure` fix has been accepted as well and should be included in the next release, but for now it still needs a patch file.

### CODE REVIEW

File: mail/notmuch/Portfile [hunk 1]
```diff
@@ -41,7 +40,6 @@ depends_lib         port:gmime3 \
                     port:zlib
 
 patchfiles          ${distname}-configure.patch \
-                    ${distname}-doc-makefile.patch \
```
Comment (l2dy) [inline mail/notmuch/Portfile]: Please also remove the patch file from git.

Comment (rseichter) [reply mail/notmuch/Portfile]: Yeah, about that: I was not sure what would happen if somebody wanted to install version 0.29 instead of 0.29.1 (for whatever reason). For Gentoo Linux, we only remove patches tied to a particular version when the ebuild (i.e. the Gentoo pendant to a MacPorts port) is also removed.

I can remove the patch, just did not want to foul things up.

Comment (chrstphrchvz) [reply mail/notmuch/Portfile]: I'm not familiar with Gentoo's packaging, but MacPorts typically only offers a single version of a port, such that when a port is updated, the previous version is no longer offered. (Reverting to an old version of a port takes more effort as a result. If multiple versions of the software are offered, it is normally done using separate ports.)

Comment (rseichter) [reply mail/notmuch/Portfile]: Oddly enough, I did not realise that MacPorts basically only offers a single version for each port. Gentoo distinguishes between stable and unstable builds (the latter being less extensively tested and usually not problematic in any way), and that for different supported processor architectures. It is even normal to have more than one unstable build per architecture, to enable users to fall back if the latest version of packaged software XYZ introduces errors.

In any case, I removed the patches for version 0.29. 😉

**Comment by l2dy** [comment]
Merged. Thanks for your contribution!

**Comment by rseichter** [comment]
@cjones051073 Pinging you because of your work on #4576. The builds on OS X 10.6 still [fail](https://build.macports.org/builders/ports-10.6_x86_64_legacy-builder/builds/105680/steps/install-port/logs/stdio) due to
```
lib/index.cc: In function ‘GMimeFilter* notmuch_filter_discard_non_term_new(GMimeContentType*)’:
lib/index.cc:250: error: expected primary-expression before ‘.’ token
```
I'm not certain if you want to invest any more time, though. I imagine the number of Notmuch users on Snow Leopard being limited these days...

**Comment by cjones051073** [comment]
the build is using the compiler `/usr/bin/llvm-g++-4.2`. Try adding this to the blacklist list.
