### PR TITLE
colm & ragel: updates of both ports and fixes for PPC

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

`colm` updated to 0.14.7.
`ragel` updated to 7.0.4.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by barracuda156** [comment]
So `colm` builds fine now on buildbots (without html docs), while `ragel` fails strangely on:
```
/usr/bin/clang++ -DHAVE_CONFIG_H -I.  -I../aapl -I../colm/include -I/opt/local/include/aapl -I/opt/local/include -I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk  -pipe -Os -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -arch x86_64 -MT ragel-rlreduce.o -MD -MP -MF .deps/ragel-rlreduce.Tpo -c -o ragel-rlreduce.o `test -f 'rlreduce.cc' || echo './'`rlreduce.cc
[2047](https://github.com/macports/macports-ports/runs/7870750620?check_suite_focus=true#step:8:2053)
  make[3]: *** No rule to make target `/opt/local/lib/libfsm.la', needed by `ragel'.  Stop.
[2048](https://github.com/macports/macports-ports/runs/7870750620?check_suite_focus=true#step:8:2054)
  make[3]: *** Waiting for unfinished jobs....
```

**Comment by kencu** [comment]
the problem with the test is that it is not being built for the build arch. probably missing arch flags I would guess.

**Comment by kencu** [comment]
what is wrong with building the docs exactly?

**Comment by kencu** [comment]
@jmroot 

are we doomed to have @barracuda156 to add this to 10,000 ports to support rosetta? This is added by the muniversal PG I believe, but that is not being used here for his pure cross build.

Also, I believe this will not work if muniversal is added (but I haven’t tested that).

platform darwin 10 powerpc {
     # Rosetta gets it wrong otherwise
     configure.args-append \
                     --build=powerpc-apple-darwin${os.major}
 }

**Comment by barracuda156** [comment]
> are we doomed to have @barracuda156 add this to 10,000 ports to support rosetta? This is added by the muniversal PG I believe, but that is not being used here for his pure cross build.

@kencu TBH I would rather find a better and universal fix, than adding this manually (whether in Macports or locally). If you could suggest how to fix that in Macports base, that will be very much preferred (by myself too).

**Comment by kencu** [comment]
I can't change base for this, but if there is suitable motivation, it might be done.

add that for all builds when the build is not being done by cmake, meson, or other non-autotools builds maybe. 

Unlikely to happen, but might as well ask as adding the same exact block to every autotools build is kinda silly.

**Comment by barracuda156** [comment]
> what is wrong with building the docs exactly?

```
Making install in colm
make[2]: Entering directory `/opt/local/var/macports/build/_opt_PPCRosettaPorts_lang_colm/colm/work/colm-0.14.7/doc/colm'
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 0_00_welcome.html 0_00_welcome.adoc
make[2]: b: No such file or directory
make[2]: [0_00_welcome.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 0_06_scope.html 0_06_scope.adoc
make[2]: b: No such file or directory
make[2]: [0_06_scope.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 1_05_variables.html 1_05_variables.adoc
make[2]: b: No such file or directory
make[2]: [1_05_variables.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 3_00_language_transformation.html 3_00_language_transformation.adoc
make[2]: b: No such file or directory
make[2]: [3_00_language_transformation.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 8_00_advanced_topics.html 8_00_advanced_topics.adoc
make[2]: b: No such file or directory
make[2]: [8_00_advanced_topics.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 9_00_q_and_a.html 9_00_q_and_a.adoc
make[2]: b: No such file or directory
make[2]: [9_00_q_and_a.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 0_01_installing.html 0_01_installing.adoc
make[2]: b: No such file or directory
make[2]: [0_01_installing.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 1_00_language_overview.html 1_00_language_overview.adoc
make[2]: b: No such file or directory
make[2]: [1_00_language_overview.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 1_06_iterators.html 1_06_iterators.adoc
make[2]: b: No such file or directory
make[2]: [1_06_iterators.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 3_01_lex.html 3_01_lex.adoc
make[2]: b: No such file or directory
make[2]: [3_01_lex.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 8_01_embedding.html 8_01_embedding.adoc
make[2]: b: No such file or directory
make[2]: [8_01_embedding.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 0_02_vim_syntax.html 0_02_vim_syntax.adoc
make[2]: b: No such file or directory
make[2]: [0_02_vim_syntax.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 1_01_statements.html 1_01_statements.adoc
make[2]: b: No such file or directory
make[2]: [1_01_statements.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 2_00_types.html 2_00_types.adoc
make[2]: b: No such file or directory
make[2]: [2_00_types.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 3_02_parse.html 3_02_parse.adoc
make[2]: b: No such file or directory
make[2]: [3_02_parse.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 8_02_modularity.html 8_02_modularity.adoc
make[2]: b: No such file or directory
make[2]: [8_02_modularity.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 0_03_commandline.html 0_03_commandline.adoc
make[2]: b: No such file or directory
make[2]: [0_03_commandline.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 1_02_expressions.html 1_02_expressions.adoc
make[2]: b: No such file or directory
make[2]: [1_02_expressions.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 2_01_basic.html 2_01_basic.adoc
make[2]: b: No such file or directory
make[2]: [2_01_basic.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 3_03_match.html 3_03_match.adoc
make[2]: b: No such file or directory
make[2]: [3_03_match.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 8_03_performance.html 8_03_performance.adoc
make[2]: b: No such file or directory
make[2]: [8_03_performance.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 0_04_hello_world.html 0_04_hello_world.adoc
make[2]: b: No such file or directory
make[2]: [0_04_hello_world.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 1_03_control_flow.html 1_03_control_flow.adoc
make[2]: b: No such file or directory
make[2]: [1_03_control_flow.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 2_02_list_map_struct_alias.html 2_02_list_map_struct_alias.adoc
make[2]: b: No such file or directory
make[2]: [2_02_list_map_struct_alias.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 3_04_undo.html 3_04_undo.adoc
make[2]: b: No such file or directory
make[2]: [3_04_undo.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 8_04_error_handling.html 8_04_error_handling.adoc
make[2]: b: No such file or directory
make[2]: [8_04_error_handling.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 0_05_fizzbuzz.html 0_05_fizzbuzz.adoc
make[2]: b: No such file or directory
make[2]: [0_05_fizzbuzz.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 1_04_functions.html 1_04_functions.adoc
make[2]: b: No such file or directory
make[2]: [1_04_functions.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 2_03_def.html 2_03_def.adoc
make[2]: b: No such file or directory
make[2]: [2_03_def.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 3_05_reduction.html 3_05_reduction.adoc
make[2]: b: No such file or directory
make[2]: [3_05_reduction.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 8_05_contributing.html 8_05_contributing.adoc
make[2]: b: No such file or directory
make[2]: [8_05_contributing.html] Error 1 (ignored)
make[3]: Entering directory `/opt/local/var/macports/build/_opt_PPCRosettaPorts_lang_colm/colm/work/colm-0.14.7/doc/colm'
make[3]: Nothing to be done for `install-exec-am'.
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 0_00_welcome.html 0_00_welcome.adoc
make[3]: b: No such file or directory
make[3]: [0_00_welcome.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 0_06_scope.html 0_06_scope.adoc
make[3]: b: No such file or directory
make[3]: [0_06_scope.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 1_05_variables.html 1_05_variables.adoc
make[3]: b: No such file or directory
make[3]: [1_05_variables.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 3_00_language_transformation.html 3_00_language_transformation.adoc
make[3]: b: No such file or directory
make[3]: [3_00_language_transformation.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 8_00_advanced_topics.html 8_00_advanced_topics.adoc
make[3]: b: No such file or directory
make[3]: [8_00_advanced_topics.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 9_00_q_and_a.html 9_00_q_and_a.adoc
make[3]: b: No such file or directory
make[3]: [9_00_q_and_a.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 0_01_installing.html 0_01_installing.adoc
make[3]: b: No such file or directory
make[3]: [0_01_installing.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 1_00_language_overview.html 1_00_language_overview.adoc
make[3]: b: No such file or directory
make[3]: [1_00_language_overview.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 1_06_iterators.html 1_06_iterators.adoc
make[3]: b: No such file or directory
make[3]: [1_06_iterators.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 3_01_lex.html 3_01_lex.adoc
make[3]: b: No such file or directory
make[3]: [3_01_lex.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 8_01_embedding.html 8_01_embedding.adoc
make[3]: b: No such file or directory
make[3]: [8_01_embedding.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 0_02_vim_syntax.html 0_02_vim_syntax.adoc
make[3]: b: No such file or directory
make[3]: [0_02_vim_syntax.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 1_01_statements.html 1_01_statements.adoc
make[3]: b: No such file or directory
make[3]: [1_01_statements.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 2_00_types.html 2_00_types.adoc
make[3]: b: No such file or directory
make[3]: [2_00_types.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 3_02_parse.html 3_02_parse.adoc
make[3]: b: No such file or directory
make[3]: [3_02_parse.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 8_02_modularity.html 8_02_modularity.adoc
make[3]: b: No such file or directory
make[3]: [8_02_modularity.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 0_03_commandline.html 0_03_commandline.adoc
make[3]: b: No such file or directory
make[3]: [0_03_commandline.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 1_02_expressions.html 1_02_expressions.adoc
make[3]: b: No such file or directory
make[3]: [1_02_expressions.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 2_01_basic.html 2_01_basic.adoc
make[3]: b: No such file or directory
make[3]: [2_01_basic.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 3_03_match.html 3_03_match.adoc
make[3]: b: No such file or directory
make[3]: [3_03_match.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 8_03_performance.html 8_03_performance.adoc
make[3]: b: No such file or directory
make[3]: [8_03_performance.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 0_04_hello_world.html 0_04_hello_world.adoc
make[3]: b: No such file or directory
make[3]: [0_04_hello_world.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 1_03_control_flow.html 1_03_control_flow.adoc
make[3]: b: No such file or directory
make[3]: [1_03_control_flow.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 2_02_list_map_struct_alias.html 2_02_list_map_struct_alias.adoc
make[3]: b: No such file or directory
make[3]: [2_02_list_map_struct_alias.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 3_04_undo.html 3_04_undo.adoc
make[3]: b: No such file or directory
make[3]: [3_04_undo.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 8_04_error_handling.html 8_04_error_handling.adoc
make[3]: b: No such file or directory
make[3]: [8_04_error_handling.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 0_05_fizzbuzz.html 0_05_fizzbuzz.adoc
make[3]: b: No such file or directory
make[3]: [0_05_fizzbuzz.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 1_04_functions.html 1_04_functions.adoc
make[3]: b: No such file or directory
make[3]: [1_04_functions.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 2_03_def.html 2_03_def.adoc
make[3]: b: No such file or directory
make[3]: [2_03_def.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 3_05_reduction.html 3_05_reduction.adoc
make[3]: b: No such file or directory
make[3]: [3_05_reduction.html] Error 1 (ignored)
b html5 -a icons -a iconsdir=/usr/share/asciidoc/icons -a max-width=800px -a source-highlighter=pygments -o 8_05_contributing.html 8_05_contributing.adoc
make[3]: b: No such file or directory
make[3]: [8_05_contributing.html] Error 1 (ignored)
 /opt/local/bin/gmkdir -p '/opt/local/var/macports/build/_opt_PPCRosettaPorts_lang_colm/colm/work/destroot/opt/local/share/doc/colm'
 /opt/local/bin/ginstall -c -m 644 ./0_00_welcome.html ./0_06_scope.html ./1_05_variables.html ./3_00_language_transformation.html ./8_00_advanced_topics.html ./9_00_q_and_a.html ./0_01_installing.html ./1_00_language_overview.html ./1_06_iterators.html ./3_01_lex.html ./8_01_embedding.html ./0_02_vim_syntax.html ./1_01_statements.html ./2_00_types.html ./3_02_parse.html ./8_02_modularity.html ./0_03_commandline.html ./1_02_expressions.html ./2_01_basic.html ./3_03_match.html ./8_03_performance.html ./0_04_hello_world.html ./1_03_control_flow.html ./2_02_list_map_struct_alias.html ./3_04_undo.html ./8_04_error_handling.html ./0_05_fizzbuzz.html ./1_04_functions.html ./2_03_def.html ./3_05_reduction.html ./8_05_contributing.html '/opt/local/var/macports/build/_opt_PPCRosettaPorts_lang_colm/colm/work/destroot/opt/local/share/doc/colm'
ginstall: cannot stat './0_00_welcome.html': No such file or directory
ginstall: cannot stat './0_06_scope.html': No such file or directory
ginstall: cannot stat './1_05_variables.html': No such file or directory
ginstall: cannot stat './3_00_language_transformation.html': No such file or directory
ginstall: cannot stat './8_00_advanced_topics.html': No such file or directory
ginstall: cannot stat './9_00_q_and_a.html': No such file or directory
ginstall: cannot stat './0_01_installing.html': No such file or directory
ginstall: cannot stat './1_00_language_overview.html': No such file or directory
ginstall: cannot stat './1_06_iterators.html': No such file or directory
ginstall: cannot stat './3_01_lex.html': No such file or directory
ginstall: cannot stat './8_01_embedding.html': No such file or directory
ginstall: cannot stat './0_02_vim_syntax.html': No such file or directory
ginstall: cannot stat './1_01_statements.html': No such file or directory
ginstall: cannot stat './2_00_types.html': No such file or directory
ginstall: cannot stat './3_02_parse.html': No such file or directory
ginstall: cannot stat './8_02_modularity.html': No such file or directory
ginstall: cannot stat './0_03_commandline.html': No such file or directory
ginstall: cannot stat './1_02_expressions.html': No such file or directory
ginstall: cannot stat './2_01_basic.html': No such file or directory
ginstall: cannot stat './3_03_match.html': No such file or directory
ginstall: cannot stat './8_03_performance.html': No such file or directory
ginstall: cannot stat './0_04_hello_world.html': No such file or directory
ginstall: cannot stat './1_03_control_flow.html': No such file or directory
ginstall: cannot stat './2_02_list_map_struct_alias.html': No such file or directory
ginstall: cannot stat './3_04_undo.html': No such file or directory
ginstall: cannot stat './8_04_error_handling.html': No such file or directory
ginstall: cannot stat './0_05_fizzbuzz.html': No such file or directory
ginstall: cannot stat './1_04_functions.html': No such file or directory
ginstall: cannot stat './2_03_def.html': No such file or directory
ginstall: cannot stat './3_05_reduction.html': No such file or directory
ginstall: cannot stat './8_05_contributing.html': No such file or directory
make[3]: *** [install-docDATA] Error 1
make[3]: Leaving directory `/opt/local/var/macports/build/_opt_PPCRosettaPorts_lang_colm/colm/work/colm-0.14.7/doc/colm'
make[2]: *** [install-am] Error 2
make[2]: Leaving directory `/opt/local/var/macports/build/_opt_PPCRosettaPorts_lang_colm/colm/work/colm-0.14.7/doc/colm'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/opt/local/var/macports/build/_opt_PPCRosettaPorts_lang_colm/colm/work/colm-0.14.7/doc'
make: *** [install-recursive] Error 1
```

This also failed on build bots, not just for me.

**Comment by barracuda156** [comment]
> I can't change base for this, but if there is suitable motivation, it might be done.

@kencu This is by the way genuinely Rosetta-specific problem (on 10.6 PPC the triple is set correctly). But I think it makes sense to have Rosetta fixed, since that is a more accessible environment for anyone wishing to build/test smth for PPC (at least `ppc32`): few ppl have PPC hardware.

**Comment by kencu** [comment]
> This also failed on build bots, not just for me. [colm.log](https://github.com/macports/macports-ports/files/9387721/colm.log) (here I disabled my doc patch).

so ideally the build line calling asciidoc needs fixing, either by us or upstream. Presumably that is in:
```
doc/Makefile
```

**Comment by jmroot** [comment]
> @kencu This is by the way genuinely Rosetta-specific problem (on 10.6 PPC the triple is set correctly).

It's not really even wrong. The machine you're building on really is x86/x64. If you want to build code for a different system than you're running on, the correct option to set is technically `--host`, not `--build`. That triggers cross-compilation mode, which unfortunately not everything supports correctly (and there's no way to auto-detect that that's what you want to do). And the build/host/target model doesn't map very well to systems that can run code built for 3 different archs and compilers that can build for any number of archs…

**Comment by barracuda156** [comment]
> > @kencu This is by the way genuinely Rosetta-specific problem (on 10.6 PPC the triple is set correctly).
> 
> It's not really even wrong. The machine you're building on really is x86/x64. If you want to build code for a different system than you're running on, the correct option to set is technically `--host`, not `--build`. That triggers cross-compilation mode, which unfortunately not everything supports correctly (and there's no way to auto-detect that that's what you want to do). And the build/host/target model doesn't map very well to systems that can run code built for 3 different archs and compilers that can build for any number of archs…

@jmroot The _physical_ cpu is x86, but from what I understand this is not a scenario of cross-compiling, since Rosetta emulated PPC cpu. That is, we do not use Intel compilers to build for PPC (cross-compilation scenario), all software is natively PPC, even Macports itself.

**Comment by kencu** [comment]
> from what I understand this is not a scenario of cross-compiling, since Rosetta emulated PPC cpu. That is, we do not use Intel compilers to build for PPC (cross-compilation scenario), all software is natively PPC, even Macports itself.

it is mostly cross compiling, as you are usually calling gcc-4.2 built as intel to build the powerpc code -- which needs to be forced to build cross with this tedious block.

when you call gcc7 or gcc12 it is using powerpc code, and an emulator, so not cross compiling. so doesn't need this b;ock. likely.

it's a true, hacky, mess.

**Comment by barracuda156** [comment]
@kencu Turns out that the error `No rule to make target `/opt/local/lib/libfsm.la', needed by `ragel'` has been reported to upstream ages ago, but never fixed and issue closed (link above).

@essandess No solution ever since, right? Strangely, on 10.6.8 it builds fine though.

**Comment by essandess** [comment]
> @essandess No solution ever since, right? Strangely, on 10.6.8 it builds fine though.

Correct. I've been waiting to see if this ever affects `rspamd` via `hyperscan`, but this doesn't affect either so far.

**Comment by barracuda156** [comment]
Update from 10.5.8. `colm` builds fine for `ppc`:
```
36-249:~ svacchanda$ port -v installed colm
The following ports are currently installed:
  colm @0.14.7_0 (active) requested_variants='-universal' platform='darwin 9' archs='ppc' date='2022-10-08T02:03:56+0800'
```

Its universal variant fails on Leopard however:
```
codegen.cc:123: warning: this decimal constant is unsigned only in ISO C90
codegen.cc:148: warning: this decimal constant is unsigned only in ISO C90
codegen.cc: In member function ‘void TableArray::stringGenerate(long long int)’:
codegen.cc:211: error: duplicate case value
codegen.cc:205: error: previously used here
libtool: compile:  /usr/bin/g++-4.2 -DHAVE_CONFIG_H -I. -I../../src -I../../src/aapl -I/opt/local/include -pipe -Os -arch ppc -arch ppc64 -c redfsm.cc -o libfsm_la-redfsm.o >/dev/null 2>&1
fatal error: lipo: can't open input file: /opt/local/var/macports/build/_opt_PPCLeopardPorts_lang_colm/colm/work/.tmp/ccq3148Z.out (No such file or directory)
make[3]: *** [libfsm_la-codegen.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
```

@kencu @mascguy Should I add `variant_universal no`? (I cannot check all arches though.)

**Comment by barracuda156** [comment]
@essandess `ragel` 7.0.4 builds fine on 10.5.8 too:
```
36-249:~ svacchanda$ port -v installed ragel
The following ports are currently installed:
  ragel @7.0.4_0 (active) requested_variants='-universal' platform='darwin 9' archs='ppc' date='2022-10-08T02:12:23+0800'
```
Any idea why on older OS there is no error?

**Comment by barracuda156** [comment]
Updated to latest-commit versions from Github, rebased upon master. Let’s see if this works.

**Comment by barracuda156** [comment]
@mascguy Ready for review, checks passed.
