### PR TITLE
mysql56: update to 5.6.48

### PR DESCRIPTION
**Pull request by chrstphrchvz**
#### Description
See https://dev.mysql.com/doc/relnotes/mysql/5.6/en/news-5-6-48.html

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### ~~Tested on~~

Untested.

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
From https://paste.z0k.xyz/42e8cd75f98a:

```
[ 56%] Building CXX object storage/innobase/CMakeFiles/innobase.dir/handler/i_s.cc.o
cd /opt/local/var/macports/build/_Users_runner_runners_2.169.1_work_1_s_databases_mysql56/mysql56/work/build/storage/innobase && /usr/bin/clang++  -DHAVE_CONFIG_H -DHAVE_IB_ATOMIC_PTHREAD_T_GCC=1 -DHAVE_IB_GCC_ATOMIC_BUILTINS=1 -DHAVE_IB_GCC_ATOMIC_BUILTINS_64=1 -DHAVE_IB_GCC_ATOMIC_BUILTINS_BYTE=1 -DHAVE_IB_GCC_ATOMIC_TEST_AND_SET=1 -DHAVE_IB_GCC_ATOMIC_THREAD_FENCE=1 -DHAVE_IB_GCC_SYNC_SYNCHRONISE=1 -DHAVE_LIBEVENT2 -DHAVE_TLSv13 -DSIZEOF_PTHREAD_T=8 -I/opt/local/var/macports/build/_Users_runner_runners_2.169.1_work_1_s_databases_mysql56/mysql56/work/build/include -I/opt/local/var/macports/build/_Users_runner_runners_2.169.1_work_1_s_databases_mysql56/mysql56/work/mysql-5.6.48/storage/innobase/include -I/opt/local/var/macports/build/_Users_runner_runners_2.169.1_work_1_s_databases_mysql56/mysql56/work/mysql-5.6.48/storage/innobase/handler -I/opt/local/var/macports/build/_Users_runner_runners_2.169.1_work_1_s_databases_mysql56/mysql56/work/mysql-5.6.48/include -I/opt/local/var/macports/build/_Users_runner_runners_2.169.1_work_1_s_databases_mysql56/mysql56/work/mysql-5.6.48/sql -I/opt/local/var/macports/build/_Users_runner_runners_2.169.1_work_1_s_databases_mysql56/mysql56/work/mysql-5.6.48/regex -I/opt/local/include  -pipe -Os -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -Wall -Wextra -Wformat-security -Wvla -Woverloaded-virtual -Wno-unused-parameter -Wno-tautological-pointer-compare -Wno-ignored-qualifiers -Wno-null-conversion -Wno-unused-private-field -DNDEBUG -DDBUG_OFF -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.14   -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -o CMakeFiles/innobase.dir/handler/i_s.cc.o -c /opt/local/var/macports/build/_Users_runner_runners_2.169.1_work_1_s_databases_mysql56/mysql56/work/mysql-5.6.48/storage/innobase/handler/i_s.cc
[…]
/opt/local/var/macports/build/_Users_runner_runners_2.169.1_work_1_s_databases_mysql56/mysql56/work/mysql-5.6.48/storage/innobase/handler/i_s.cc:3018:14: error: implicit instantiation of undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
        std::string fts_table_name(fts_internal_tbl_name);
                    ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iosfwd:193:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
/opt/local/var/macports/build/_Users_runner_runners_2.169.1_work_1_s_databases_mysql56/mysql56/work/mysql-5.6.48/storage/innobase/handler/i_s.cc:3451:14: error: implicit instantiation of undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
        std::string fts_table_name(fts_internal_tbl_name);
                    ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iosfwd:193:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
/opt/local/var/macports/build/_Users_runner_runners_2.169.1_work_1_s_databases_mysql56/mysql56/work/mysql-5.6.48/storage/innobase/handler/i_s.cc:3912:14: error: implicit instantiation of undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
        std::string fts_table_name(fts_internal_tbl_name);
                    ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iosfwd:193:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
/opt/local/var/macports/build/_Users_runner_runners_2.169.1_work_1_s_databases_mysql56/mysql56/work/mysql-5.6.48/storage/innobase/handler/i_s.cc:4082:14: error: implicit instantiation of undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
        std::string fts_table_name(fts_internal_tbl_name);
                    ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iosfwd:193:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
[…]
4 errors generated.
make[2]: *** [storage/innobase/CMakeFiles/innobase.dir/handler/i_s.cc.o] Error 1
```

Not sure what to do about this yet.

**Comment by chrstphrchvz** [comment]
I wonder if the i_s.cc file is missing `#include <string>` (not the most helpful error message if so). However the same file in mysql 5.7.30 might not have it yet compiles just fine.

**Comment by chrstphrchvz** [comment]
Adding the missing `#include <string>` appears to fix the issue. I have submitted a patch for it upstream: https://bugs.mysql.com/bug.php?id=99799

**Comment by chrstphrchvz** [comment]
Pinging @kencu as they're working on this port at the moment

**Comment by kencu** [comment]
Oh -- I didn't know you guys were working on this here. 

I just tweaked the present version of mysql56 to build on 10.6.8 for someone in the related ticket. Hope that doesn't mess you up at all.

**Comment by chrstphrchvz** [comment]
@Ken It's all good now; I saw the ticket activity and noticed this needed a tiny conflict resolved. I'm curious if you wanted to try this out on those older macOS versions you were testing, or could shepherd this PR for me.

**Comment by kencu** [comment]
looks like we didn't overlap at all -- and wouldn't it be a peach if this version just builds thru on 10.6.8 now too! I guess we'll see when you commit this.
