### PR TITLE
llvm-3.4: unbreak build on Rosetta

### PR DESCRIPTION
**Pull request by barracuda156**
Fixes: https://trac.macports.org/ticket/64498

#### Description

Sample project does not use arch flags and does not pass those even when they are explicitly added either in Makefile or in portfile. So on Rosetta objects are built for x86, and linkage fails.
Sample is optional anyway and excluded on Sparc. Just exclude it for Rosetta case.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
you misunderstood how the patch works. It forces ppc7400 on anything newer than Tiger.

Now it would force ppc7400 on anything newer than Leopard, but use older assembly code on Leopard. I doubt that is what you want. ( forget the fact it is broken code at present anyway).

And anyway, changing this patch in this port would not fix the build of this port on Rosetta, as it is not used to build itself, of course.

So… ?

**Comment by barracuda156** [comment]
> you misunderstood how the patch works. It forces ppc7400 on anything newer than Tiger.

That is super-strange and must be wrong then, since Leopard supports `ppc64` and has to have either generic target or `ppc970`.

> Now it would force ppc7400 on anything newer than Leopard, but use older assembly code on Leopard. I doubt that is what you want. ( forget the fact it is broken code at present anyway).

Sorry that I misread it, not noticing LT. Is that "lower than", with ! for negation?

> And anyway, changing this patch in this port would not fix the build of this port on Rosetta, as it is not used to build itself, of course.

As a matter of fact, _it does build_ with updated patch. It fails otherwise. We have discussed that earlier: https://trac.macports.org/ticket/64498
I mean, I misunderstood the statement, but it did fix the build on Rosetta somehow. And this is not a single case, since it fixed the build on my other machine with 10.6.8 earlier.

I convert this to Draft first though. This patch may need to be changed in a somewhat different way.

**Comment by kencu** [comment]
oh, yeah, thanks for reminding me. It seems to ? build some kind of sample…. still not sure abt that, but I reread that ticket and recall now.

**Comment by barracuda156** [comment]
> oh, yeah, thanks for reminding me. It seems to ? build some kind of sample…. still not sure abt that, but I reread that ticket and recall now.

What do you think we could try?
One thing, a fix for Rosetta is needed, whether logical or not. Other thing, perhaps `ppc7400` should not be applied to Leopard `ppc64`.

P. S. By the way, building `llvm-3.4` for `ppc64` turned nowhere trivial: https://github.com/iains/darwin-toolchains-start-here/discussions/29#discussioncomment-2302119

File: lang/llvm-3.4/files/0004-Set-the-Mach-O-CPU-Subtype-to-ppc7400-when-targeting.patch [hunk 1]
```diff
@@ -32,7 +32,7 @@ index 0d42081..7260c10 100644
        bool is64 = getPointerSize() == 8;
 +      MachO::CPUSubTypePowerPC CS = MachO::CPU_SUBTYPE_POWERPC_ALL;
 +
-+      if (TheTriple.isOSDarwin() && !TheTriple.isMacOSXVersionLT(10,5)) {
++      if (TheTriple.isOSDarwin() && (!TheTriple.isMacOSXVersionLT(10,5) && !TheTriple.isMacOSXVersionLT(10,6))) {
```
Comment (catap) [inline lang/llvm-3.4/files/0004-Set-the-Mach-O-CPU-Subtype-to-ppc7400-when-targeting.patch:35]: Why not `isMacOSXVersionLT(10,6)` only?

Comment (barracuda156) [reply lang/llvm-3.4/files/0004-Set-the-Mach-O-CPU-Subtype-to-ppc7400-when-targeting.patch:35]: @catap Fair enough.

I will test the build again, if all goes as planned, will update the PR and hopefully it gets pushed. `llvm34` is a big stopped on Rosetta otherwise.

Comment (kencu) [reply lang/llvm-3.4/files/0004-Set-the-Mach-O-CPU-Subtype-to-ppc7400-when-targeting.patch:35]: well, even if it builds, it doesn't work :P

I think we just need to get llvm out of the variants for cctools and ld64 on PowerPC, which would be by far the better option IMHO. I believe that is the only reason it is wanted at all anyway.

Of course, someday, over the rainbow, way up high, iain will maybe actually fix llvm and clang for powerpc and then some of this llvm stuff starts to make sense.

Comment (catap) [reply lang/llvm-3.4/files/0004-Set-the-Mach-O-CPU-Subtype-to-ppc7400-when-targeting.patch:35]: @kencu I feel that migration to xtools seems much early :)

Comment (barracuda156) [reply lang/llvm-3.4/files/0004-Set-the-Mach-O-CPU-Subtype-to-ppc7400-when-targeting.patch:35]: > well, even if it builds, it doesn't work :P

@kencu It works for what it is currently used for, which some LTO magic or w/e.

> I think we just need to get llvm out of the variants for cctools and ld64 on PowerPC, which would be by far the better option IMHO. I believe that is the only reason it is wanted at all anyway.

Unfortunately, `xcode` variant of `ld64` is broken, so until we move to `xtools`, there is no other feasible option. (Well, unless someone fixes `cctools` properly, but that cannot be myself.)

Comment (kencu) [reply lang/llvm-3.4/files/0004-Set-the-Mach-O-CPU-Subtype-to-ppc7400-when-targeting.patch:35]: xtools won't really help this llvm34 issue, but someday, after a LOT LOT LOT of testing, MacPorts might consider moving whole hog to Iain's toolchain, on all systems where it is newer than what we have. What I am running now on 10.6 Intel is already MUCH newer than what he has, so I will never change to xtools. Maybe 10.4 and 10.5 might change, and @barracuda156 's 10.6-on-PowerPC passion. There will be LOTS of discussion about that, I bet :>

the xcode variant of ld64 was never meant to be used on any systems except the very very newest ones (10.15 and newer) so you should just stay well away from that on older systems. It is of absolutely no value anyway, as the cctools and ld64 in those ancient xcodes is from the 2008 era. Why would you want that?????

I use (and build) cctools and ld64 just fine on every system from 10.4 PPC to Monterey. What exact problem are you having that you are trying to fix? I think it is that one or both of cctools and ld64 defaults to invoking LLVM to get LTO, all of which is pretty much useless on PowerPC. The fix there is to make it stop asking for LLVM in the first place. Anyway, llvm34 builds on 10.5 PPC as I recall.

Don't mess things up too much while you're playing around please,, guys. This has all worked for years, so please don't blow it all up to support Rosetta on 10.6....play nice :>

Comment (barracuda156) [reply lang/llvm-3.4/files/0004-Set-the-Mach-O-CPU-Subtype-to-ppc7400-when-targeting.patch:35]: > The fix there is to make it stop asking for LLVM in the first place.

@kencu Likely so, but who is gonna make it?

> Anyway, llvm34 builds on 10.5 PPC as I recall.

It builds fine for ppc32 on 10.6 PPC too. The issue just concerns Rosetta **and, by the way, ppc64 on Leopard**. The latter still broken completely: https://github.com/iains/darwin-toolchains-start-here/discussions/29

> This has all worked for years

As a matter of fact, Macports for ppc64 will not work without manual trickery. While I am sure you can fix it locally for yourself and likely have done that earlier, it is broken in the master. For years :)

Comment (kencu) [reply lang/llvm-3.4/files/0004-Set-the-Mach-O-CPU-Subtype-to-ppc7400-when-targeting.patch:35]: when last I built cctools and ld64 universal on 10.5 ppc/ppc64, I recall no troubles. It’s been a while, though, since I did that… not sure what troubles you’re having with ppc64 on 10.5 now. Other than the recent icu won’t build as ppc64 with gcc7, of course, haven’t seen or heard any issues or seen any tickets about issues.

As you’ve been around only a few months, must be hard to know what has been broken For Years :).

Comment (barracuda156) [reply lang/llvm-3.4/files/0004-Set-the-Mach-O-CPU-Subtype-to-ppc7400-when-targeting.patch:35]: > when last I built cctools and ld64 universal on 10.5 ppc/ppc64, I recall no troubles. It’s been a while, though, since I did that… not sure what troubles you’re having with ppc64 on 10.5 now. Other than the recent icu won’t build as ppc64 with gcc7, of course, haven’t seen or heard any issues or seen any tickets about issues.

I cannot test `llvm-3.4` for `ppc64` right now (still away from PPC hardware), but last time(s) I tried, it failed – which is why I opened that discussion thread.
None of Pythons will build as ppc+ppc64 from the master. (I have fixed them for myself eventually, but you saw how it went with even simple fixes for Pythons for PPC – with PR being just closed, so I left it at that.)
It is overall impossible to have Macports on Leopard as ppc64-only, as it is.

> As you’ve been around only a few months, must be hard to know what has been broken For Years :).

Unless someone has broken archaic ports recently, I assume either no one ever tested them or otherwise did not push fixes into the master.

**Comment by barracuda156** [comment]
@kencu @catap @mascguy So I confirm that `llvm-3.4` does not build on Rosetta from existing in the master portfile:
```
:info:build Undefined symbols:
:info:build   "_main", referenced from:
:info:build       start in crt1.10.5.o
:info:build ld: symbol(s) not found
:info:build collect2: ld returned 1 exit status
```
[llvm-3.4.log](https://github.com/macports/macports-ports/files/9482724/llvm-3.4.log)

File: lang/llvm-3.4/files/0004-Set-the-Mach-O-CPU-Subtype-to-ppc7400-when-targeting.patch (hunk 1 above)
Comment (kencu) [reply lang/llvm-3.4/files/0004-Set-the-Mach-O-CPU-Subtype-to-ppc7400-when-targeting.patch:35]: nobody has ever tested building anything on macports with Rosetta on 10.6, other than one-off jokey things. Nobody would have ever pushed anything into master to support this. I still am 100% against pushing such oddball specific fixes, but you seem to have induced Christopher into doing it for you.

cctools and ld64 build as universal ppc/ppc64 on Leopard PPC, have for years. That is a (more or less) supported MacPorts configuration.

I picture the time you move on from this passion and are no longer interested in building things as rosetta on 10.6, and we start stripping all these hacks out.

**Comment by catap** [comment]
@barracuda156 I really doubt that llvm can be built for PPC or on Rosetta without ton of work.

File: lang/llvm-3.4/files/0004-Set-the-Mach-O-CPU-Subtype-to-ppc7400-when-targeting.patch (hunk 1 above)
Comment (kencu) [reply lang/llvm-3.4/files/0004-Set-the-Mach-O-CPU-Subtype-to-ppc7400-when-targeting.patch:35]: As before, however -- **proper fixes**, that do the right thing for all builds and in the process also happen to fix 10.6-on-PPC (and Rosetta on 10.6) are completely perfectly fine, and much appreciated.

having llvm-3.4 build with CPU_SUBTYPE_ALL for PPC build may be an OK fix.... Jeremy did the ppc7400 thing for a reason, not sure exactly what it was. Maybe just to build faster code, not sure.

Comment (barracuda156) [reply lang/llvm-3.4/files/0004-Set-the-Mach-O-CPU-Subtype-to-ppc7400-when-targeting.patch:35]: @kencu You might have built llvm34 for ppc64 for yourself, what I am saying is that it will not work from portfiles from the master. It gonna fail on llvm34.

Rosetta has a value for testing ppc for those who do not have hardware. Can’t see a reason why not to fix something that can be fixed and doesn’t affect other systems.

Comment (mascguy) [reply lang/llvm-3.4/files/0004-Set-the-Mach-O-CPU-Subtype-to-ppc7400-when-targeting.patch:35]: > Nobody has ever tested building anything on macports with Rosetta on 10.6, other than one-off jokey things. Nobody would have ever pushed anything into master to support this. I still am 100% against pushing such oddball specific fixes, but you seem to have induced Christopher into doing it for you.

Ken, I always welcome your input. And whenever you see something that isn't kosher, please speak up!

You've also provided plenty of positive praise for a number of Sergey's PRs. So honestly, this is a surprising - if not shocking - comment.

Perhaps if you can elaborate a bit, relative to what you consider acceptable, vs. unacceptable?

**Comment by barracuda156** [comment]
> @barracuda156 I really doubt that llvm can be built for PPC or on Rosetta without ton of work.

Well, llvm (not clang) builds for ppc, and all versions from 3.5 to 7.1 build for Rosetta and ppc64. What is broken is specifically llvm33 and llvm34 for Rosetta and ppc64. And then newer llvm, of course.

I have llvm5 on all systems, right now on Rosetta and on 10.5.8 ppc64.

**Comment by catap** [comment]
> Well, llvm (not clang) builds for ppc

Sorry, I mean llvm eq clang in my comment.

**Comment by barracuda156** [comment]
> > Well, llvm (not clang) builds for ppc
> 
> 
> 
> Sorry, I mean llvm as clang in my comment.


Oh sure, but we don’t need it.

**Comment by barracuda156** [comment]
@mascguy In any case I will update the PR as ready for review once I find a way to fix it that is reproducible. Current patch is insufficient or redundant for Rosetta, but I did build llvm34 on Rosetta, which was discussed in the Trac ticket. I need to figure out what exactly worked and minimize needed changes.

ppc64 seems to be broken, and possibly a better way will be use gcc10-bootstrap to build llvm5, and then use that for ld64 and cctools on 10.5.8 ppc64, bypassing these ancient broken versions altogether.

**Comment by kencu** [comment]
on 10.5 PPC, cctools doesn't require or use llvm. It's a trivial change to have the same for rosetta. 

ld64-127 does require llvm to build, I believe, but it uses llvm-3.3 on PPC Leopard, not llvm-3.4. If llvm-3.3 builds on rosetta, that would do, therefore. 

NB: ld64-97 works better for ppc anyway (as we know) and does not require any llvm. I would probably use that on rosetta for ppc code, for now.

until someday in the future when xtools is inhaled properly into macports.

**Comment by barracuda156** [comment]
> on 10.5 PPC, cctools doesn't require or use llvm. It's a trivial change to have the same for rosetta.
> 
> ld64-127 does require llvm to build, I believe, but it uses llvm-3.3 on PPC Leopard, not llvm-3.4. If llvm-3.3 builds on rosetta, that would do, therefore.
> 
> NB: ld64-97 works better for ppc anyway (as we know) and does not require any llvm. I would probably use that on rosetta for ppc code, for now.
> 
> until someday in the future when xtools is inhaled properly into macports.

@kencu I am not qualified to judge whether it is needed, but Macports wants llvm34 (or llvm33, which is broken likewise for Rosetta and ppc64):
```
10:~ svacchanda$ port rdeps ld64-97
The following ports are dependencies of ld64-97 @97.17_9+llvm34:
  libmacho-headers
  llvm-3.4
    python27
      xz
        lbzip2
        gettext
          libiconv
            gperf
          libtextstyle
            ncurses
          gettext-runtime
          gettext-tools-libs
      pkgconfig
      bzip2
      db48
      expat
      libedit
      libffi
        expect
          automake
            autoconf
              m4
          tcl
        dejagnu
      sqlite3
        zlib
      openssl11
      python_select
      python2_select
    perl5
      perl5.34
        gdbm
          readline
    llvm_select
```
And yes, we actually should set `ld64-97` as the default one for PPC.

**Comment by kencu** [comment]
> ppc64 seems to be broken, and possibly a better way will be use gcc10-bootstrap to build llvm5, and then use that for ld64 and cctools on 10.5.8 ppc64, bypassing these ancient broken versions altogether.

well of course that has always been the plan for the last year or two, stated many times, but it will be llvm-7.0 as that is what Iain has fixed for PPC, and his xtools fixes imported into macports and used across-the-board for older systems.

File: lang/llvm-3.4/files/0004-Set-the-Mach-O-CPU-Subtype-to-ppc7400-when-targeting.patch (hunk 1 above)
Comment (mascguy) [reply lang/llvm-3.4/files/0004-Set-the-Mach-O-CPU-Subtype-to-ppc7400-when-targeting.patch:35]: > I picture the time you move on from this passion and are no longer interested in building things as Rosetta on 10.6, and we start stripping all these hacks out.

I'm absolutely fine with everything that has been done thus far, for Sergey's past PRs. And much of the time, the additions are a few simple lines of logic, which are benign for non-PPC/Rosetta builds.

Even in the cases where additional patches are necessary, those are cleanly segregated from the portfile itself. And Not a Big Deal.

So the long and short of it is this: I certainly won't be letting anyone rip these changes out of anything I maintain! And folks can also expect strong pushback, if they try to rip out these changes for other ports... whether they maintain them or not.

**Comment by kencu** [comment]
> @kencu I am not qualified to judge whether it is needed, but Macports wants llvm34 (or llvm33, which is broken likewise for Rosetta and ppc64):

You're getting very close to being qualified!

So these default settings for llvm use in cctools and ld64-N are just things that Jeremy and I set up, based on what 10.4, 10.5, and 10.6 could build at the time we set them up. It's not broken, exactly -- rosetta wasn't a consideration at the time to be supported.

**Comment by barracuda156** [comment]
@kencu @catap As you can see, I have these on Rosetta:
```
10:~ svacchanda$ port -v installed | grep llvm
  cctools @949.0.1_2+llvm34 (active) requested_variants='+llvm34' platform='darwin 10' archs='ppc' date='2022-07-17T06:16:10+0700'
  ld64-97 @97.17_9+llvm34 requested_variants='' platform='darwin 10' archs='ppc' date='2022-07-17T06:08:35+0700'
  ld64-97 @97.17_9+llvm50 (active) requested_variants='+llvm50-llvm34' platform='darwin 10' archs='ppc' date='2022-09-04T01:40:42+0700'
  llvm-3.4 @3.4.2_16 (active) requested_variants='' platform='darwin 10' archs='ppc' date='2022-07-17T06:05:13+0700'
  llvm-5.0 @5.0.2_4+polly (active) requested_variants='+polly' platform='darwin 10' archs='ppc' date='2022-08-07T11:50:01+0700'
  llvm_select @2_0 (active) requested_variants='' platform='darwin 10' archs='noarch' date='2022-07-17T03:34:02+0700'
10:~ svacchanda$ sw_vers
ProductName:	Mac OS X Server
ProductVersion:	10.6.8
BuildVersion:	10K549
```
The same `ld64-97 @97.17_9+llvm50` I was using on 10.5.8 (ppc+ppc64) and 10.6 PPC (10A190).
The problem is that some way is needed to either get rid of `llvm-3.x` dependency or to fix `llvm-3.x` until a move to `llvm-7.1` happens. What we have now in master is broken, even though it affects a small number of people.

**Comment by barracuda156** [comment]
> So these default settings for llvm use in cctools and ld64-N are just things that Jeremy and I set up, based on what 10.4, 10.5, and 10.6 could build at the time we set them up. It's not broken, exactly -- rosetta wasn't a consideration at the time to be supported.

@kencu When I say broken I rather mean ppc64, which is a standard case for 10.5.x. (Rosetta sort of became more relevant now, since PPC hardware is getting scarcer.)

I will return to ppc64 case later, that needs testing to see what works. I recall the process was not trivial, but eventually it worked out. And I may need your and others help to fix that properly.

**Comment by kencu** [comment]
> The problem is that some way is needed to either get rid of `llvm-3.x` dependency or to fix `llvm-3.x` until a move to `llvm-7.1` happens. 

The llvm requirements for ld64 are established in this section of the ld64 Portfile.

https://github.com/macports/macports-ports/blob/ae599db331c972d809ee069ffca9fabf9fea5166/devel/ld64/Portfile#L371

They were set up based on 10.4, 10.5, and 10.6 as they are, not considering rosetta.

So to take into account the rosetta case, you would make a slight adjustment to that code, so that no llvm is defaulted on a 10.6 rosetta system. ld64-97 will build fine without llvm.

File: lang/llvm-3.4/files/0004-Set-the-Mach-O-CPU-Subtype-to-ppc7400-when-targeting.patch (hunk 1 above)
Comment (kencu) [reply lang/llvm-3.4/files/0004-Set-the-Mach-O-CPU-Subtype-to-ppc7400-when-targeting.patch:35]: Unmaintainable spaghetti hacks to support an oddball build system that absolutely nobody except for 1 person ever uses are not something I can possibly support.

I hear the exact same thing coming from others.

But -- have at it if you like it ;> What happens in MacPorts is certainly not up to me.

Comment (kencu) [reply lang/llvm-3.4/files/0004-Set-the-Mach-O-CPU-Subtype-to-ppc7400-when-targeting.patch:35]: > Rosetta has a value for testing ppc for those who do not have hardware. Can’t see a reason why not to fix something that can be fixed and doesn’t affect other systems.

You keep saying this, but a 10.5 Leopard VM runs just fine on Parallels and is a much better testbed for PowerPC code.

Comment (catap) [reply lang/llvm-3.4/files/0004-Set-the-Mach-O-CPU-Subtype-to-ppc7400-when-targeting.patch:35]: > A 10.5 Leopard VM runs just fine on Parallels

Have you achieved installed Parallels tools?

Comment (kencu) [reply lang/llvm-3.4/files/0004-Set-the-Mach-O-CPU-Subtype-to-ppc7400-when-targeting.patch:35]: Sure, didn't seem to have any troubles -- this was all done about 5 years ago, now, and updated when Parallels updates...

Screen Sharing Picture September 3, 2022 at 8 06 21 PM PDT

Comment (catap) [reply lang/llvm-3.4/files/0004-Set-the-Mach-O-CPU-Subtype-to-ppc7400-when-targeting.patch:35]: Ken, all my attempts to install Patallels Tools are failed🥺

Comment (barracuda156) [reply lang/llvm-3.4/files/0004-Set-the-Mach-O-CPU-Subtype-to-ppc7400-when-targeting.patch:35]: @catap On 10.5.8, not 10.6.8, right?

Comment (catap) [reply lang/llvm-3.4/files/0004-Set-the-Mach-O-CPU-Subtype-to-ppc7400-when-targeting.patch:35]: @barracuda156 yes, on 10.5.8; I also have it as Parallels VM. It is officially supported and I've opened an issue inside Parallels to fix tools with provided crashes, gdb dumps and so on :)

Comment (kencu) [reply lang/llvm-3.4/files/0004-Set-the-Mach-O-CPU-Subtype-to-ppc7400-when-targeting.patch:35]: Heisenbergs I guess. 

I have not yet installed the very latest Parallels update -- I generally hang back a little with things like that. The VM is ripping fast with 8 cores and 16GB of RAM.

Sometimes after I have used it for a few days the screen display will start tearing during refreshes and similar glitches; I log into it using Screen Sharing and it's fine that way, until I reboot it.

I can't get Tiger running on Parallels, but VirtualBox runs Tiger reasonably well.

Comment (catap) [reply lang/llvm-3.4/files/0004-Set-the-Mach-O-CPU-Subtype-to-ppc7400-when-targeting.patch:35]: @kencu well, I've successfully boot Tiger in Parallels, but it had a random crashes :)

Comment (kencu) [reply lang/llvm-3.4/files/0004-Set-the-Mach-O-CPU-Subtype-to-ppc7400-when-targeting.patch:35]: > Ken, all my attempts to install Patallels Tools are failed🥺

Oh, one thing I can tell you here -- sometimes you must manually uninstall Parallels Tools and then reboot, and then install parallels tools fresh. Updating Parallels Tools can fail on older system VMs if it is already installed.

Comment (kencu) [reply lang/llvm-3.4/files/0004-Set-the-Mach-O-CPU-Subtype-to-ppc7400-when-targeting.patch:35]: > @kencu well, I've successfully boot Tiger in Parallels, but it had a random crashes :)

very interesting. I must have tried a dozen times, and it would never accept the Tiger boot.

Comment (catap) [reply lang/llvm-3.4/files/0004-Set-the-Mach-O-CPU-Subtype-to-ppc7400-when-targeting.patch:35]: > very interesting. I must have tried a dozen times, and it would never accept the Tiger boot.

It was a kind of magic. Installer can boot, or can crash. Usually crash but sometimes it may boot. If boot, it may try to install. With a lot of luck it can do it.

Tiger inside parallels seems like a walk in minefield. It randomly crashes. And it is unuseful at all.

Comment (kencu) [reply lang/llvm-3.4/files/0004-Set-the-Mach-O-CPU-Subtype-to-ppc7400-when-targeting.patch:35]: I left a link to the virtualbox/tiger instructions in your parallels post, but here it is for you again https://github.com/ranma42/TigerOnVBox

Honestly, though, it's a timehole. Tiger is missing some really basic supports like rpath, and that is getting to be a big PITA. I had supported Tiger for some years on MacPorts because I was using an old Tiger PPC box to send out faxes using hylafax for about 15 years and didn't want to go through the project of updating it.

But I moved the hylafax server to a current Ubuntu system with brand new faxmodem PCI cards, and mothballed the Tiger PPC system, converting it to debian11 instead. Now that box runs rust and llvm-14 :>

Comment (catap) [reply lang/llvm-3.4/files/0004-Set-the-Mach-O-CPU-Subtype-to-ppc7400-when-targeting.patch:35]: > I had supported Tiger for some years on MacPorts because I was using an old Tiger PPC box to send out faxes using hylafax for about 15 years and didn't want to go through the project of updating it.

sounds like you live in Germany too :) here fax is quite useful in 2022.

**Comment by barracuda156** [comment]
@kencu Returning to this issue to complete it.

I tried linking the problematic file manually, it still fails:
```
macmini:sample svacchanda$ /usr/bin/g++-4.2 -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_llvm-3.4/llvm-3.4/work/build/include -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_llvm-3.4/llvm-3.4/work/build/projects/sample/include -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_llvm-3.4/llvm-3.4/work/build/projects/sample/tools/sample -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_llvm-3.4/llvm-3.4/work/llvm-3.4.2.src/include -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_llvm-3.4/llvm-3.4/work/llvm-3.4.2.src/projects/sample/include -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_llvm-3.4/llvm-3.4/work/llvm-3.4.2.src/projects/sample/tools/sample  -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Os  -fno-exceptions -fno-common -Woverloaded-virtual -Wcast-qual  -Os -rdynamic -Wl,-rpath -Wl,@executable_path/../lib -L/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_llvm-3.4/llvm-3.4/work/build/projects/sample/Release/lib -L/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_llvm-3.4/llvm-3.4/work/build/Release/lib -L/opt/local/lib -Wl,-headerpad_max_install_names -arch ppc -mmacosx-version-min=10.6  -pedantic -Wno-long-long -Wall -W -Wno-unused-parameter -Wwrite-strings    -o /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_llvm-3.4/llvm-3.4/work/build/projects/sample/Release/bin/Sample  /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_llvm-3.4/llvm-3.4/work/build/projects/sample/tools/sample/Release/main.o -lsample -lz -lpthread -lffi -lcurses -lm
ld: warning: in /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_llvm-3.4/llvm-3.4/work/build/projects/sample/tools/sample/Release/main.o, file was built for unsupported file format which is not the architecture being linked (ppc)
ld: warning: in /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_llvm-3.4/llvm-3.4/work/build/projects/sample/Release/lib/libsample.a, file was built for unsupported file format which is not the architecture being linked (ppc)
Undefined symbols:
  "_main", referenced from:
      start in crt1.10.5.o
ld: symbol(s) not found
collect2: ld returned 1 exit status
```
The symbol is present however in `crt1.10.5`
```
macmini:sample svacchanda$ nm -arch ppc -g /usr/lib/crt1.10.5.o |grep main
         U _main
```

**Comment by kencu** [comment]
> The symbol is present however in `crt1.10.5`
> 
> ```
> macmini:sample svacchanda$ nm -arch ppc -g /usr/lib/crt1.10.5.o |grep main
>          U _main
> ```

"U" means the symbol is undefined... i.e.  not found.

**Comment by kencu** [comment]
I still say your best mileage would be to work on ld64-97 (and maybe ld64-127) so they don't need any llvm variant when building for ppc. After all, we all know that it is a waste of time anyway, as PPC code cannot be LTO'd by any llvm available outside Iain's repos (and even in there, I am not sure).

But -- I just don't have it in me to start working on how to fix llvm-3.4 to build as PPC rosetta on a 10.6 Intel system. I don't want to set up such a system, and I it's just too hard to spend time fixing issues with such a system by remote control. So -- very sorry, but you are on your own here.

**Comment by barracuda156** [comment]
> But -- I just don't have it in me to start working on how to fix llvm-3.4 to build as PPC rosetta on a 10.6 Intel system. I don't want to set up such a system, and I it's just too hard to spend time fixing issues with such a system by remote control. So -- very sorry, but you are on your own here.

I think we have an answer now. Just need to patch relevant Makefile to pass archflags.

**Comment by kencu** [comment]
there you go, now you're making some headway -- but still a waste of time even if it does build, as llvm-3.4 is useless for PPC. Just make ld64-97 build without llvm (like it does on Tiger) and move along to something useful.

**Comment by barracuda156** [comment]
> there you go, now you're making some headway -- but still could be considered a waste of time even if it does build, as llvm-3.4 is not functional for PPC. IMHO make ld64-97 build without llvm (like it does on Tiger) and move along to something worthy of your time…

Should we make `ld64` build without `llvm34` for all PPC? That would fix universal builds (ppc+ppc64) on 10.5.8 too.

P. S. Since I spent so much time on this silly LLVM anyway, I want to complete the fix, but `ld64` matter is relevant still, since `llvm34` is broken for ppc64, and that I am not gonna try fixing.

**Comment by barracuda156** [comment]
@kencu Could we merge this? Should be uncontroversial. Affects only Rosetta (and, well, 10A190, but only Rosetta needs this fix).

**Comment by barracuda156** [comment]
@kencu P. S. I do remember that we want to move away from using old LLVMs on PPC, but it won’t hurt fixing the build anyway. Also, until we make changes to cctools and ld64, this fix is needed.

**Comment by barracuda156** [comment]
Closing in favor of: https://github.com/macports/macports-ports/pull/17694
