### PR TITLE
rsync: update to 3.4.4

### PR DESCRIPTION
**Pull request by herbygillot**
Refresh fileflags.diff using FreeBSD's patch ported to rsync 3.4.4. This retains the existing --fileflags aliases while adding the documented --file-flags spelling and immutable-file handling.

Update the generated rsync.1 manpage to match the patched rsync.1.md documentation.

### CODE REVIEW

**Comment by barracuda156** [comment]
Unfortunately, it fails to build as is: https://github.com/RsyncProject/rsync/issues/1025

**Comment by herbygillot** [comment]
> Regression: 3.4.4 fails to build on macOS 10.6: `syscall.c: error: too few arguments to function ‘do_lchown’` RsyncProject/rsync#1025

@barracuda156, just added a patch, can you try again? It's AI-generated, so YMMV.

**Comment by barracuda156** [comment]
@herbygillot I will try, thank you.

Have you seen upstream patch in https://github.com/RsyncProject/rsync/pull/1026 btw? It does not exclude the need to fix FreeBSD patch used here, but fixed upstream-side issue.

**Comment by jmroot** [comment]
This will close https://trac.macports.org/ticket/74160

**Comment by pmetzger** [comment]
Given that we have security bugs in the current rsync, can we update this now and make additional fixes later?

**Comment by barracuda156** [comment]
I will check in an hour or two if exactly the current version compiles. (I was thinking that upstream version gets picked and then a bug in FreeBSD patch is fixed, but in any case a working rsync is better than a broken one.)

**Comment by barracuda156** [comment]
@herbygillot It does require upstream fix (I have referenced it above):

```
:info:build syscall.c: In function ‘do_xstat_at’:
:info:build syscall.c:1316: warning: unused parameter ‘at_flags’
:info:build syscall.c: In function ‘do_lstat_at’:
:info:build syscall.c:1367: error: ‘AT_SYMLINK_NOFOLLOW’ undeclared (first use in this function)
:info:build syscall.c:1367: error: (Each undeclared identifier is reported only once
:info:build syscall.c:1367: error: for each function it appears in.)
:info:build /usr/bin/gcc-4.2 -std=gnu99 -I. -I. -I./zlib -pipe -Os -arch ppc -DHAVE_CONFIG_H -Wall -W -I/opt/local/include -DRSYNC_NO_AT_SYSCALLS -c log.c -o log.o
:info:build make: *** [syscall.o] Error 1
:info:build make: *** Waiting for unfinished jobs....
```

**Comment by pmetzger** [comment]
gcc 4.2 is a circa 2007 compiler. I don't think we should leave our users open to a security hole because of an issue with a compiler from almost 20 years ago.

**Comment by barracuda156** [comment]
@pmetzger This has absolutely nothing to do with a compiler. And it is a real bug which upstream acknowledged.
But w/e, I give up. You prefer broken stuff, your choice.

**Comment by pmetzger** [comment]
There are actual security holes in the rsync in our tree. This puts our users in danger. We have been waiting for a long time for this to be fixed. We cannot wait indefinitely.

**Comment by pmetzger** [comment]
Just to be clear: rsync seems to build just fine on the CI and on my machine. I presume that it is broken on your machine because you are using a PowerPC system from decades ago.
