### PR TITLE
mesa: fix build on macOS 10.11 and earlier

### PR DESCRIPTION
**Pull request by chrstphrchvz**
Recently added patch uses `clock_gettime()` on macOS 10.14 and earlier; `clock_gettime()` is unavailable on macOS 10.11 and earlier, but is available from legacysupport.

#### Description
(Alternatively, the maintainer can figure out an alternative approach to using `clock_gettime()`—as yet another alternative to `timespec_get()`—which upstream can incorporate.)

See recent build failures for macOS 10.7-10.11: https://ports.macports.org/port/mesa/builds
```
In file included from ../include/c11/threads.h:66:
../include/c11/threads_posix.h:391:9: warning: implicit declaration of function 'clock_gettime' is invalid in C99 [-Wimplicit-function-declaration]
        clock_gettime(CLOCK_REALTIME, ts);
        ^
../include/c11/threads_posix.h:391:23: error: use of undeclared identifier 'CLOCK_REALTIME'
        clock_gettime(CLOCK_REALTIME, ts);
                      ^
```
(10.6 fails during patching; static-strndup.patch appears to be outdated. See https://trac.macports.org/ticket/62063)

###### ~~Tested on~~

Untested; I do not have access to an affected macOS version.
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
this doesn't fix the build on 10.6.8, but it looks like it is needed for some systems, so we can try it.

**Comment by chrstphrchvz** [comment]
After I opened this PR, someone opened https://trac.macports.org/ticket/62061 regarding the issue. Should it be closed?
