### PR TITLE
ghostscript: fix build with freetype 2.10.3

### PR DESCRIPTION
**Pull request by chrstphrchvz**
Fixes: https://trac.macports.org/ticket/61306

###### Tested on

macOS 10.15.7
Xcode 12 command line tools

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
Added another patch to fix missing `#include <stdlib.h>` for `+ghostpdl` variant under Xcode 12:

```
./jpegxr/r_strip.c:1710:28: error: implicit declaration of function 'abs' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        unsigned int iEM = abs(iPixVal);
                           ^
```

**Review by michaelld — APPROVED** [review]
works for me on macOS 11.0 20A5384c ;  Xcode 12.2 12B5025f

FYI didn't work without this fix ... so :+1:
