### PR TITLE
i2pd: fix build on macOS <10.15 with Clangs

### PR DESCRIPTION
**Pull request by aeiouaeiouaeiouaeiouaeiouaeiou**
###### Tested on

macOS 10.8.5 12F2560 x86_64
Xcode 5.1.1 5B1008

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
>there is nothing about macOS version as such, it is an old `libc++` issue

https://build.macports.org/builders/ports-10.14_x86_64-builder/builds/238359/steps/install-port/logs/stdio

```
In file included from /opt/local/var/macports/build/i2pd-4aaadd19/work/i2pd-2.57.0/libi2pd_client/AddressBook.cpp:19:
/opt/local/var/macports/build/i2pd-4aaadd19/work/i2pd-2.57.0/build/../libi2pd/util.h:180:4: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
                        auto& GetIOService () { return m_Service; }
                        ^
/opt/local/var/macports/build/i2pd-4aaadd19/work/i2pd-2.57.0/build/../libi2pd/util.h:180:35: error: no viable conversion from returned value of type 'boost::asio::io_context' to function return type 'int'
                        auto& GetIOService () { return m_Service; }
                                                       ^~~~~~~~~
```

This does not happen on newer versions of macOS with Clang, so the problem is definitely not just with `libc++`.

CC @herbygillot @mascguy

**Comment by barracuda156** [comment]
@aeiouaeiouaeiouaeiouaeiouaeiou Well, the whole of your fix amounts to supplying newer `libc++` headers and adjusting compiler choice. This is not a problem of macOS version – you won’t need these fixes when building with gcc against libstdc++ on the same macOS versions.

I am fine with not going into details and just stating “fix build on macOS <10.15 with clangs”, for example. The current title is misleading, since the problem does not exist on systems using gcc with libstdc++.

**Comment by barracuda156** [comment]
@aeiouaeiouaeiouaeiouaeiouaeiou Thank you!

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
ping @reneeotten @herbygillot

File: security/i2pd/Portfile [hunk 1]
```diff
@@ -51,10 +61,6 @@ platform darwin {
     }
 }
 
-# https://github.com/PurpleI2P/i2pd/issues/1798
```
Comment (barracuda156) [inline security/i2pd/Portfile:54]: Maybe keep the issue ref though?

Comment (aeiouaeiouaeiouaeiouaeiouaeiou) [reply security/i2pd/Portfile:54]: The issue is outdated because now more versions of Clang need to be blocked due to another error.

Comment (barracuda156) [reply security/i2pd/Portfile:54]: Ok, w/e. (For reviewers – this is not a blocker to merge.)
