### PR TITLE
qt6-qtbase: attempt to fix build with 10.14 SDK

### PR DESCRIPTION
**Pull request by chrstphrchvz**
###### Tested on

Only patch phase is tested.

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by mascguy** [comment]
Getting warmer, but builds now fail with:

```
:info:build [...]/work/qtbase-everywhere-src-6.2.1/src/gui/rhi/qrhimetal.mm:385:26: error: cannot initialize a variable of type 'const NSUInteger' (aka 'const unsigned long') with an rvalue of type 'id'
:info:build         const NSUInteger deviceLocation = [d->dev location];
:info:build                          ^                ~~~~~~~~~~~~~~~~~
:info:build 1 warning and 1 error generated.
```

Full log attached:

[qt6-qtbase-main-round-2.log.gz](https://github.com/macports/macports-ports/files/8428423/qt6-qtbase-main-round-2.log.gz)

**Comment by chrstphrchvz** [comment]
Added return value cast:

```
const NSUInteger deviceLocation = (NSUInteger)[d->dev location];
                                  ~~~~~~~~~~~~
```

Does it help?

**Comment by mascguy** [comment]
> Added return value cast:
> 
> ```
> const NSUInteger deviceLocation = (NSUInteger)[d->dev location];
>                                   ~~~~~~~~~~~~
> ```
> 
> Does it help?

Yes indeed, and the build succeeded. Great work!

**Review by mascguy — APPROVED** [review]
