### PR TITLE
TOra: Fix build with clang-902.0.39.2 (Xcode 9.4.1)

### PR DESCRIPTION
**Pull request by mkhon**
#### Description

Fix build with clang-902.0.39.2 (Xcode 9.4.1)

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on
macOS 10.13.6 17G65
Xcode 9.4.1 9F2000 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
Thanks for your pull request.

In your request, you checked this box:

>  followed our Commit Message Guidelines?

...except you didn't actually follow the guidelines.  Unfortunately, that means I can't trust that the rest of the checkboxes reflect reality, either. Please

1. Fix the commit message to match the commit message guidelines.
2. Tell us exactly what sorts of testing you've performed.

**Comment by pmetzger** [comment]
> Oh, that rather arrogant BDE-style comments (if you know what it means).

I don't care to know what it means. The commit message standard is pretty simple and easy to follow.

> the commit fixed the compilation error referenced in the issue. I do not know what else should I put into the subject - can you advice?

The standard explains, among other things, that the commit message needs to reference the port being modified. We have thousands of them, and a message of the form "Fix build with clang" does not explain to any of the people reading the commit message stream which of the thousands of ports has just been changed. Perhaps you might try reading the document, as it is quite clear and even explains the motivation behind what it demands.

**Comment by mkhon** [comment]
Marcus,

- I reverted portrevision bump
- I corrected commit message to include port name

Thanks!

**Comment by pmetzger** [comment]
@mkhon This looks good now. Have you submitted the patches upstream? Regardless, if everyone feels this is now in a good state, we can merge it.
