### PR TITLE
blender: add support for Universal Scene Description (USD)

### PR DESCRIPTION
**Pull request by jasonliu--**
#### Description

Also in this commit:
* The eigen3 port was recently updated to a version that is incompatible with the version of Ceres Solver that comes with Blender 2.83.0. So I have temporarily commented out using the eigen3 port (so that the port compiles with the older eigen3 source that is supplied with the Blender source code) until the Blender port can catch up to using a compatible version of Ceres Solver and eigen3.
* I discovered that the Cycles renderer wasn't getting compiled using Embree. I've fixed the port so that Embree is now getting used during the compile.

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.11.6 15G22010
Xcode 8.2.1 8C1002

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by jasonliu--** [comment]
Note to any reviewers/committers: I have no idea why the Azure build is failing for just 10.14. According to the pastebin, it looks like it has something to do with the macOS SDK, but since I don't have access to a machine with 10.14, I have no way to troubleshoot this. Needless to say, I made sure that the build works fine on my macOS 10.11 / Xcode 8.2 machine before submitting this PR.

File: graphics/blender/Portfile [hunk 1]
```diff
@@ -281,4 +340,24 @@ variant manpage description {Build manpage} {
...
+
+variant embree_static \
+    description {Build Blender using static Embree libraries, instead of a dynamic library. Use this variant if you intend to install the Embree port using the +static variant.} \
+{
+    require_active_variants embree static
+}
+
+if {![variant_isset embree_static]} {
+    require_active_variants embree {} static
+}
```
Comment (ryandesign) [inline graphics/blender/Portfile:361]: Why is all of this happening? It is brittle / confusing to offer variants that change what libraries are installed and to require matched sets of variants across different ports. Why should there be a monolithic variant of usd or a static variant of embree at all?

File: graphics/blender/Portfile [hunk 2]
```diff
@@ -145,6 +151,55 @@ post-patch {
...
+            {/embree_sse42/d} \
+            {/lexers/d} \
+            {/math/d} \
+            {/simd/d} \
+            {/sys/d} \
+            {/tasking/d} \
+        ] {
+            reinplace $re \
+                ${worksrcpath}/build_files/cmake/Modules/FindEmbree.cmake
+        }
```
Comment (ryandesign) [inline graphics/blender/Portfile:200]: Your continued use of reinplaces where patchfiles are preferred is frustrating. Each of these reinplaces, for example, removes just a single line from the file, and all of the lines are together. It would be shorter, simpler, more clear what you're doing to use a patchfile instead, and it would prevent problems in the future. Today, for example, the file doesn't contain any other lines that contain the three characters "sys" in that order, but you cannot be certain that the file will not be modified in the future to contain such other occurrences or that removing such other occurrences would not have negative effects on the build.

**Comment by kencu** [comment]
> Note to any reviewers/committers: I have no idea why the Azure build is sometimes failing for just 10.14 (this is not the first PR for Blender which this has happened). According to the pastebin, it looks like it has something to do with the macOS SDK, but since I don't have access to a machine with 10.14, I have no way to troubleshoot this. Needless to say, I made sure that the build works fine on my macOS 10.11 / Xcode 8.2 machine before submitting this PR.

Indeed, somehow it is mixing two different SDKs together, with results that are not working out:
```
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Headers/IconsCore.h:663:70: error: expected function body after function declarator
  SInt16 *                 outLabel)               /* can be NULL */ __OSX_AVAILABLE_BUT_DEPRECATED_MSG(__MAC_10_1, __MAC_10_13, __IPHONE_NA, __IPHONE_NA, "Use -[NSWorkspace iconForFile:] instead.");
                                                                     ^
/Applications/Xcode_11.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/Availability.h:291:57: note: expanded from macro '__OSX_AVAILABLE_BUT_DEPRECATED_MSG'
                                                        __AVAILABILITY_INTERNAL##_osxIntro##_DEP##_osxDep##_MSG(_msg)
                                                        ^
<scratch space>:5:1: note: expanded from here
__AVAILABILITY_INTERNAL__MAC_10_1_DEP__MAC_10_13_MSG
^
```

File: graphics/blender/Portfile (hunk 1 above)
Comment (jasonliu--) [reply graphics/blender/Portfile:361]: > It is brittle / confusing to offer variants that change what libraries are installed and to require matched sets of variants across different ports.

The variants don't actually change what libraries are installed. All they do is make sure that if the user installs the variants of those libraries, that Blender has to be built in a certain way. I don't think that using variants is any more brittle than simply checking for which variant of the library is installed before the build phase begins, because any mismatched situations will give users feedback as to how they can get to a working, non-broken state. If you feel that doing a check before the build phase is sufficient for the situation where a user goes in and installs one of the libraries' variants after building Blender, then fine, but then please don't blame me later if users complain that they aren't getting any sort of messages that Blender is broken after installing the library variants.

> Why should there be a monolithic variant of usd or a static variant of embree at all?

These are the main modes of use for usd and embree, and other software projects which depend on usd or embree may need to use those variants. For example, there are portions of Embree that only get compiled when compiling Embree as a static library. Specifically, these portions pertain to Intel instruction set extensions such as AVX2, SSE2, SSE4, etc. When Embree is compiled as a dynamic library, it's not necessary to compile modules for these instruction sets separately. However, if Embree is compiled as a static library, modules for each of the instruction sets needs to be compiled, which can result in a very large static library. (See https://github.com/macports/macports-ports/pull/9366#issuecomment-742020416)

File: graphics/blender/Portfile (hunk 2 above)
Comment (jasonliu--) [reply graphics/blender/Portfile:200]: And I find it frustrating that you seem to keep implying that patchfiles are always preferred over reinplaces. If Blender's source code was relatively unchanging, then I might agree with you, but Blender is currently undergoing a period of rapid change and development. There's no guarantee that the entire reinplace won't simply disappear a couple of updates from now.

I will admit that the regexes, as I have written them, are a bit inefficient and have the possibility for ambiguity later, but that simply means that the regexes should be modified to make them better... it doesn't necessarily mean that they shouldn't be regexes at all, in favor of a patchfile. Conversely to what you said, one could argue that you can't be certain that the context lines before and after a patch block won't be modified in the future such that the patch will fail. And I would argue that a project like Blender, where the code is currently in rapid flux, that this situation is more likely to happen, whereas a well-written regular expression, which is completely position independent, would actually be _less_ likely to have problems.

Comment (jasonliu--) [reply graphics/blender/Portfile]: I've modified the regexes to be more specific.
