### PR TITLE
python314-devel: add compatibility patch to fix build on macOS <10.12

### PR DESCRIPTION
**Pull request by aeiouaeiouaeiouaeiouaeiouaeiou**
Closes: https://trac.macports.org/ticket/71608

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 10K549 x86_64
Xcode 4.2 4C199

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
@jmroot please review these changes. I don't think it will break anything critically, especially since Python 3.14 is still in alpha testing.

File: lang/python314-devel/Portfile [hunk 1]
```diff
@@ -59,6 +64,9 @@ depends_run         port:python_select-${pythonVerNoDot} \
                     port:python3_select-${pythonVerNoDot}
 
 compiler.c_standard 2011
+# libintvector.h:230:9: error: unknown type name '__m256i' on macOS < 10.11
+compiler.blacklist-append \
+                    {clang < 800}
```
Comment (jmroot) [inline lang/python314-devel/Portfile:69]: What changed to introduce this requirement?

File: lang/python314-devel/files/patch-pylifecycle-compatibility.diff [hunk 2]
```diff
@@ -0,0 +1,89 @@
...
++#    define HAS_APPLE_SYSTEM_LOG 1
++#  elif defined(TARGET_OS_OSX) && TARGET_OS_OSX
++#    if defined(MAC_OS_X_VERSION_10_12) && MAC_OS_X_VERSION_MIN_REQUIRED >= MAC_OS_X_VERSION_10_12
++#      define HAS_APPLE_SYSTEM_LOG 1
++#    else
++#      define HAS_APPLE_SYSTEM_LOG 0
++#    endif
++#  else
++#    define HAS_APPLE_SYSTEM_LOG 0
++#  endif
```
Comment (jmroot) [inline lang/python314-devel/files/patch-pylifecycle-compatibility.diff:23]: This is a lot more complicated than it needs to be, and upstream isn't going to accept unconditionally defining `TARGET_OS_OSX`. You know you are on macOS if it is undefined, so the correct condition would be something like:
```
#if (defined(TARGET_OS_IPHONE) && TARGET_OS_IPHONE) \
     || ((!defined(TARGET_OS_OSX) || TARGET_OS_OSX) \
         && MAC_OS_X_VERSION_MIN_REQUIRED >= 101200)
#define HAS_APPLE_SYSTEM_LOG 1
#else
#define HAS_APPLE_SYSTEM_LOG 0
#endif
```

File: lang/python314-devel/Portfile (hunk 1 above)
Comment (kencu) [reply lang/python314-devel/Portfile:69]: I suspect it has to do with the fact that older clang versions did not enable avx by default, and needed an extra flag sent. This was fixed in approx llvm clang-7.

these were added here:

https://github.com/python/cpython/commit/325e9b8ef400b86fb077aa40d5cb8cec6e4df7bb

see this:

https://github.com/llvm/llvm-project/blob/9a95c097d0466c594f40a4ba9ced8a155574fdff/llvm/lib/Support/BLAKE3/CMakeLists.txt#L53

and this:

https://github.com/BLAKE3-team/BLAKE3/issues/79

Comment (aeiouaeiouaeiouaeiouaeiouaeiou) [reply lang/python314-devel/Portfile:69]: That's right.

The updated HACL module actively utilizes intrinsic functions. They are enabled via `HACL_CAN_COMPILE_SIMD128` and `HACL_CAN_COMPILE_SIMD256` macros ([blocked on ARM64](https://github.com/python/cpython/blob/401bfc69d1258fde07141cd1a12af00aa44a8e0f/Modules/blake2module.c#L44) for obvious reasons).
I didn't block them because of the possible performance impact and since the software is still in alpha development.

File: lang/python314-devel/files/patch-pylifecycle-compatibility.diff (hunk 2 above)
Comment (aeiouaeiouaeiouaeiouaeiouaeiou) [reply lang/python314-devel/files/patch-pylifecycle-compatibility.diff:23]: I don't understand the distinction, since I just replaced `#  include <TargetConditionals.h>` with `#  define TARGET_OS_OSX 1` and the upsream still doesn't have that code.

File: lang/python314-devel/Portfile (hunk 1 above)
Comment (kencu) [reply lang/python314-devel/Portfile:69]: Rather than restrict compilers to this degree, perhaps it would be useful to consider adding the needed flag to enable avx512 like llvm did? That is probably also upstreamable, I would think.

Likely still need to restrict the compiler selection, but perhaps not as severely.

Comment (kencu) [reply lang/python314-devel/Portfile:69]: Assuming that works, Josh could probably take that added avx512 flag upstream if he wanted to, using the LLVM installation as backup.

Comment (jmroot) [reply lang/python314-devel/Portfile:69]: A configure check for whether the compiler supports/needs `-mavx512vl` would be a more upstreamable fix.

Comment (aeiouaeiouaeiouaeiouaeiouaeiou) [reply lang/python314-devel/Portfile]: I deleted that part of the code and rebased the branch.

3.14 alpha 4 release is [expected today](https://peps.python.org/pep-0745/), but I want to see how these changes from this PR will affect buildbots.

**Comment by jmroot** [comment]
I'm happy to test out changes in the port, but the goal (mine at least) is to get the changes included upstream, so the changes we try here should be exactly the same changes that we propose for adoption upstream. This is why I'm asking to remove `#define TARGET_OS_OSX 1` and instead handle it being undefined correctly with the single simplified check.
