### PR TITLE
ansifilter: fix compiler incompatibility on OSX 10.8 and below - attempt 2

### PR DESCRIPTION
**Pull request by tessus**
The compile runs still error out. @kencu suggested to use the PortGroup
directive instead. Without having access to the build machines this
is just a trial and error until the buildbots are invoked for PRs.

### CODE REVIEW

**Comment by tobypeterson** [comment]
Purely an assumption here, but I would guess that the makefile still needs modification to accept CC, CFLAGS, etc from environment provided by MacPorts. It isn't magically going to find the right compiler (unless it does, in which case ignore me).

**Comment by tessus** [comment]
Hmm, I thought that the PortGroup would override the CC variable automatically, or at least I had the impression from @kencu's statement.

**Comment by mojca** [comment]
I can confirm that this doesn't work
{{{
g++ -c -Wall -O2 -DNDEBUG -std=c++11 arg_parser.cpp -o arg_parser.o
g++ -c -Wall -O2 -DNDEBUG -std=c++11 stringtools.cpp -o stringtools.o
cc1plus: error: unrecognized command line option "-std=c++11"
cc1plus: error: unrecognized command line option "-std=c++11"
}}}
but that's because the port is not [Using the right compiler](https://trac.macports.org/wiki/UsingTheRightCompiler).

I actually don't know if MacPorts provides the environmental variables during the build phase, maybe the variables are only available during configure.

**Comment by mojca** [comment]
The `makefile` uses qmake. That makes me suspect that the port should either use the `qmake` (4 or 5) PortGroup and depend on some Qt packages. Or what's the point of "qt-gui" subfolder?

**Comment by tessus** [comment]
@mojca I'm not building the GUI in this port, just the commandline tool. I might get the GUI build with a variant at one point, but right now I only care about getting the commandline tool compiled on osx < 10.8

**Comment by mojca** [comment]
> Hmm, I thought that the PortGroup would override the CC variable automatically, or at least I had the impression from @kencu's statement.

Well, yes, it would set the proper compiler. But only if the `Portfile` makes sure that the variables are properly passed to the software's build system. When `./configure` or `CMake` is used, then `CC`, `CXX` etc. are automatically taken from the environment. In your case I suspect that the `qmake` group might have solved the problem, but I'm not sure. Manually written Makefiles are always a problem.

Please start by experimenting with
```
sudo port -v build ansifilter configure.compiler=macports-clang-4.0
```
on your machine. You need to see the proper compiler being chosen. Until that works on 10.12 there's no reason to expect that it will automagically work on 10.6.

**Comment by tessus** [comment]
@tobypeterson just tested it https://github.com/macports/macports-ports/pull/427#issuecomment-294085267

**Comment by tessus** [comment]
I'l' add it in a sec

**Comment by mojca** [comment]
Quotes are missing.

**Comment by mojca** [comment]
But anyway:
```
/opt/local/bin/clang++-mp-4.0 -Os -D_GLIBCXX_USE_CXX11_ABI=0 -stdlib=macports-libstdc++ arg_parser.cpp -o arg_parser.o
/opt/local/bin/clang++-mp-4.0 -Os -D_GLIBCXX_USE_CXX11_ABI=0 -stdlib=macports-libstdc++ stringtools.cpp -o stringtools.o
Undefined symbols for architecture x86_64:
  "_main", referenced from:
      start in crt1.10.6.o
ld: symbol(s) not found for architecture x86_64
Undefined symbols for architecture x86_64:
  "_main", referenced from:
      start in crt1.10.6.o
ld: symbol(s) not found for architecture x86_64
```

**Comment by mojca** [comment]
The files should be compiled with the option `-c`.

**Comment by tessus** [comment]
I'm sorry, I have no idea what the error means. It compiles without problems on osx >= 10.9.

I don't have a 10.8 machine to debug this further. I've sent a few emails to the developer of ansifilter and his answer was this:

>  there is a transition concerning auto_ptr (deprecated since gcc6) and unique_ptr (new shiny type).
You can try this: remove  -std=c++11 in the makefile and replace unique_ptr by auto_ptr in main.cpp, line 116.

This is what I did in my first patch to fix the compile issue, but it still abended somewhere else.

**Comment by mojca** [comment]
The error means that the makefiles are flawed.

I had to patch the makefile in the following way:
```
$(EXECUTABLE): $(OBJECTS)
	$(CC) $(LDFLAGS) $(CFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) -c $(CFLAGS) $< -o $@
```
That is: add `$(CFLAGS)` when building the executable and adding `-c` when building the object files. `CFLAGS` in the first call are a bit weird, maybe `LDFLAGS` should be properly patched instead.

In any case, you'll additionally be bitten by https://trac.macports.org/ticket/53634

For the `Portfile` I needed:
```
build.args-append        CC="${configure.cxx}" \
                         CFLAGS="${configure.cxxflags} -std=c++11"
```
Note that this section should not be specific to darwin or < 10.9. You have to set the compiler in any case.

**Comment by tessus** [comment]
Why is it not compiled with `-c`? This makes no sense.

From the Makefile:

```
$(EXECUTABLE): $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@
```

The CFLAGS from the makefile are `CFLAGS= -c -Wall -O2 -DNDEBUG -std=c++11`. 

So, if you set CC to the compiler provided by macports and append the CXX flags from macports to CFLAGS, why doesn't it work?

It seems that CFLAGS is overwritten and not appended.

**Comment by mojca** [comment]
Btw, just replacing the `unique_ptr` won't help. `std::to_string` is also a C++11-only feature (http://en.cppreference.com/w/cpp/string/basic_string/to_string) and there might be others.

Here's the explanation of what happens when some flags are missing (missing `-stdlib=libc++` when compiling the final binary):
```
/opt/local/bin/clang++-mp-3.9 -c -Os -stdlib=libc++ preformatter.cpp -o preformatter.o
/opt/local/bin/clang++-mp-3.9  main.o arg_parser.o stringtools.o cmdlineoptions.o platform_fs.o codegenerator.o htmlgenerator.o pangogenerator.o texgenerator.o latexgenerator.o rtfgenerator.o plaintextgenerator.o bbcodegenerator.o elementstyle.o stylecolour.o preformatter.o -o ansifilter
```

You need to ask upstream to fix the problems in the makefile (not yet sure about `CFLAGS` for the main executable). You should also ask upstream to call the flags `CXXFLAGS`. We usually never add `-std=c++` and alike to `CFLAGS`.

**Comment by mojca** [comment]
OK, the following works without the first patch for the `makefile`:
```tcl
build.args-append        CC="${configure.cxx}" \
                         CFLAGS="${configure.cxxflags} -std=c++11" \
                         LDFLAGS="${configure.ldflags} -stdlib=${configure.cxx_stdlib}"
```

**Comment by tessus** [comment]
Ah, just saw your reply. Now it makes sense. Yes, the build process of ansifilter is a bit weird.

I agree. I will send upstream the suggestion to fix the makefile and use CXXFLAGS.
Until then, I will incorporate your changes and add another commit. Will do that tomorrow though. I'm a bit tired and don't want to screw it up.

**Comment by tessus** [comment]
Ok, our comments crossed paths.

I will still ask upstream for the changes in the makefile. I've never seen `-c` in CFLAGS before. And since I don't have to patch the Makefile now, I'll commit your changes in a sec.

**Comment by tessus** [comment]
@mojca no, you need the patch to the makefile. just tried it without it. it failed.

**Comment by mojca** [comment]
I committed the changes now, no need to do anything else for MP, but please report the problem upstream.

Yes, the changes need to go to the `makefile`, not to `CFLAGS`. What I meant was that we also need additional flags next to `LDFLAGS` and I'm not sure about the proper solution for that.

**Comment by tessus** [comment]
ah, ok. yes, I will. thanks.

**Comment by mojca** [comment]
I used `LDFLAGS="${configure.ldflags} -stdlib=${configure.cxx_stdlib}"`, but I'm not happy with that part.

**Comment by tessus** [comment]
what would you suggest instead?

I will ask him to put the `-c` in the right place and add a CXXFLAGS var.

But where else should `-std=c++11` and `-stdlib=${configure.cxx_stdlib}` go?
`-std=c++11` is a compile flag, so it belongs in CXXFLAGS (which we don't have right now). 
But what is wrong with adding a linker flag to LDFLAGS?
