### PR TITLE
bfs: use legacysupport

### PR DESCRIPTION
**Pull request by chrstphrchvz**
#### Description
Build fails on macOS 10.9 and earlier:

```
bftw.c:384:11: warning: implicit declaration of function 'openat' is invalid in C99 [-Wimplicit-function-declaration]
        int fd = openat(at_fd, at_path, flags);
                 ^
bftw.c:417:14: error: use of undeclared identifier 'AT_FDCWD'
        int at_fd = AT_FDCWD;
                    ^
exec.c:268:23: error: use of undeclared identifier 'AT_FDCWD'
        if (ftwbuf->at_fd != AT_FDCWD) {
                             ^
bftw.c:495:13: warning: implicit declaration of function 'fdopendir' is invalid in C99 [-Wimplicit-function-declaration]
        DIR *ret = fdopendir(dfd);
                   ^
bftw.c:495:7: warning: incompatible integer to pointer conversion initializing 'DIR *' with an expression of type 'int' [-Wint-conversion]
        DIR *ret = fdopendir(dfd);
             ^     ~~~~~~~~~~~~~~
color.c:730:12: error: use of undeclared identifier 'AT_FDCWD'
                        at_fd = AT_FDCWD;
                                ^
eval.c:341:11: error: use of undeclared identifier 'AT_REMOVEDIR'
                flag |= AT_REMOVEDIR;
                        ^
eval.c:347:6: warning: implicit declaration of function 'unlinkat' is invalid in C99 [-Wimplicit-function-declaration]
        if (unlinkat(ftwbuf->at_fd, ftwbuf->at_path, flag) != 0) {
            ^
color.c:739:16: error: use of undeclared identifier 'AT_FDCWD'
                if (at_fd == AT_FDCWD && path[0] != '/') {
                             ^
eval.c:410:13: warning: implicit declaration of function 'openat' is invalid in C99 [-Wimplicit-function-declaration]
                int dfd = openat(ftwbuf->at_fd, ftwbuf->at_path, O_RDONLY | O_CLOEXEC | O_DIRECTORY);
                          ^
eval.c:416:14: warning: implicit declaration of function 'fdopendir' is invalid in C99 [-Wimplicit-function-declaration]
                DIR *dir = fdopendir(dfd);
                           ^
eval.c:416:8: warning: incompatible integer to pointer conversion initializing 'DIR *' with an expression of type 'int' [-Wint-conversion]
                DIR *dir = fdopendir(dfd);
                     ^     ~~~~~~~~~~~~~~
bftw.c:1024:18: error: use of undeclared identifier 'AT_FDCWD'
        ftwbuf->at_fd = AT_FDCWD;
                        ^
fsade.c:50:38: error: use of undeclared identifier 'AT_FDCWD'
        if (!proc_works || ftwbuf->at_fd == AT_FDCWD) {
                                            ^
fsade.c:61:18: error: use of undeclared identifier 'AT_FDCWD'
                if (xfaccessat(AT_FDCWD, path, F_OK) != 0) {
                               ^
```

###### Tested on

Untested
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by ylluminarious** [comment]
@chrstphrchvz I'm not sure if this program was intended to work on versions earlier than 10.9. What am I supposed to do to fix this?

**Comment by chrstphrchvz** [comment]
There are quite a few programs in MacPorts which are running on older macOS versions than upstream developers intend to support.

If getting a program working on older macOS is easy thanks to MacPorts' existing infrastructure for doing so, then it might be worth a try. If it proves difficult or is undesirable, then the port can be prevented from attempting to install on older macOS versions:

```
if {${os.platform} eq "darwin" && ${os.major} < some_darwin_version} {
    known_fail yes
    pre-fetch {
        ui_error "${name} ${version} requires macOS 10.x or later."
        return -code error "incompatible macOS version"
    }
}
```

**Comment by ylluminarious** [comment]
@ryandesign Thanks for merging this.

@chrstphrchvz Thanks for clarifying this. Your change seems fine to me so I'm giving a belated approval even though it was already merged 😆

**Comment by ryandesign** [comment]
I didn't test it myself but merged it since it's harmless to try and that would let the buildbot give it a go.

It didn't work:

https://build.macports.org/builders/ports-10.9_x86_64-builder/builds/129026/steps/install-port/logs/stdio

```
Undefined symbols for architecture x86_64:
  "_faccessat", referenced from:
      _xfaccessat in util.o
  "_fdopendir$INODE64", referenced from:
      _bftw_open in bftw.o
      _eval_empty in eval.o
  "_fstatat", referenced from:
      _bfs_stat in stat.o
  "_macports_legacy_sysconf", referenced from:
      _bfs_exec_parse in exec.o
  "_openat", referenced from:
      _bftw_file_openat in bftw.o
      _eval_empty in eval.o
  "_readlinkat", referenced from:
      _xreadlinkat in util.o
  "_unlinkat", referenced from:
      _eval_delete in eval.o
```

This is happening because it isn't linking with libMacportsLegacySupport.dylib.

This shows us that the port has a problem on all OS versions: It does not honor the LDFLAGS MacPorts sets. This could probably be fixed using the makefile-1.0 portgroup; that will also remove the need for many of the manually-set lines of the portfile. I'll see if I can make the changes.

**Comment by kencu** [comment]
Hey - almost a home run! But it sure isn't happy with the clang-425 in Lion <https://build.macports.org/builders/ports-10.7_x86_64-builder/builds/32985/steps/install-port/logs/stdio>

**Comment by ryandesign** [comment]
Yup, just seeing that and blacklisting it.
