### PR TITLE
aria2: restore Tiger build

### PR DESCRIPTION
**Pull request by kencu**
no current libuv at present on Tiger

### CODE REVIEW

**Comment by Schamschula** [comment]
Looks like there is a new error I didn't see on my system

`error: use of undeclared identifier 'make_unique'`

This is a C++14 issue.

This PR is not related.

**Comment by kencu** [comment]
So this builds and runs on Tiger, but aside from that, I notice the Travis builds fail here and yet it built just fine on my home 10.14 system just now.

However, building it at home on 10.14 in trace mode fails, just like Travis does.

Must be some missing dependency somewhere....

**Comment by Schamschula** [comment]
It built cleanly in trace mode yesterday, on my High Sierra machine with Xcode 10.

**Comment by Schamschula** [comment]
Hmm. I didn't mention, that I had built with +gnutls +sqilte3. I just tried building with just +sqlite3, and got the same error. Perhaps an issue with libuv when building against appletls?

**Comment by kencu** [comment]
If it helps, my successful build on 10.14, without trace mode, picks up `Nettle`, `Libssh2`, and `LibGmp`, whereas these three are excluded from my failing build with trace mode on. Perhaps one of them is involved.

**Comment by Schamschula** [comment]
The +openssl variant also builds cleanly. I'll remove libuv support for the appletls build.
