### PR TITLE
WIP xorg-server-devel: Update to 1.20.x branch

### PR DESCRIPTION
**Pull request by cjones051073**
#### Description

Update xorg-server-devel to latest commit in the 1.20.x git branch.
Adapt to new xorg-xorgproto prototype header package.

- [ ] bugfix
- [x] enhancement
- [ ] security fix

macOS 10.13.6 17G65
Xcode 9.4.1 9F2000

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
Does this still crash on exit, or was that figured out?

**Comment by pmetzger** [comment]
Oh, and _thank you so much_ for working on this.

File: x11/xorg-server-devel/Portfile [hunk 1]
```diff
@@ -88,19 +71,24 @@ configure.args --with-apple-applications-dir=${applications_dir} \
...
+        0001-os-connection-Improve-abstraction-for-launchd-secure.patch \
+        0002-randr-Initialize-RandR-even-if-there-are-currently-n.patch \
+        0003-glx-Initialize-glx-even-if-there-are-currently-no-sc.patch \
+        5000-sdksyms.sh-Use-CPPFLAGS-not-CFLAGS.patch \
+        5001-Revert-dix-Restore-PaintWindow-screen-hook.patch \
+        5002-Workaround-the-GC-clipping-problem-in-miPaintWindow-.patch \
+        5003-Use-old-miTrapezoids-and-miTriangles-routines.patch \
+        5004-fb-Revert-fb-changes-that-broke-XQuartz.patch \
+        5005-fb-Revert-fb-changes-that-broke-XQuartz.patch \
+        5006-work-around-double-delete-on-exit.patch
```
Comment (pmetzger) [inline x11/xorg-server-devel/Portfile]: I'm surprised none of these patches are in the upstream? (Jeremy usually put stuff in that had been accepted upstream already.)

Comment (cjones051073) [reply x11/xorg-server-devel/Portfile]: The last one is one I added. It should never go upstream as is as its a work around not a fix.

The others I am not sure, I did not to be honest check if they are upstream or not. They do apply though which suggests not...

**Comment by cjones051073** [comment]
I have 'fixed' the crash on exit with the `5006-work-around-double-delete-on-exit.patch`...

its not a proper fix, just a work around, until someone figures out what is really going on.

It might well be related to whatever `0003-glx-Initialize-glx-even-if-there-are-currently-no-sc.patch` addresses. I had to report this a bit and I am not convinced it is entirely correct.

**Comment by cjones051073** [comment]
Note, as this is a level package I figured it 'OK' to push experimental stuff. I am not sure though I would want this to got to the primary `xorg-server` port as is though...

File: x11/xorg-server-devel/Portfile (hunk 1 above)
Comment (pmetzger) [reply x11/xorg-server-devel/Portfile]: We might want to investigate why they didn't go upstream then. We'll probably have to do it alone since Jeremy isn't here to explain.

**Comment by pmetzger** [comment]
Shall we merge? It is the `-devel` port.

**Comment by cjones051073** [comment]
I'm still poking at it a bit in my spare moments.. Something peculiar seems to be going on with some allocs/frees, but I cannot yet put my finger on what. Suggest making this WIP for a bit whilst I continue.

**Comment by cjones051073** [comment]
OK... Think I have figured out the crash on exit issue, and I think its an upstream bug.

In a nut shell, the issue is the loop at line 447 in

https://gitlab.freedesktop.org/xorg/xserver/blob/server-1.20-branch/glx/glxscreens.c

loops over a memory buffer of __GLXconfig structs and individually frees each. The issue is this buffer was allocated with a *single* call to calloc at line 116 in

https://gitlab.freedesktop.org/xorg/xserver/blob/server-1.20-branch/hw/xquartz/GL/visualConfigs.c

This means the correct way (if I have understood the C standard correctly) to release the memory is a *single* call to free passing the start of the memory buffer, as returned by the calloc call. I have prepared a trivial patch to make this fix, and with it everything seems fine.

Note, just for reference, the offending loop seems new in the 1.20.x branch. It does not exist in 1.19.x or older.

I've tried to search their bugzilla,

https://bugzilla.freedesktop.org

to see if anything is already there for it, but not found anything so far. Its not the easiest thing in the world to search though so I could have missed it.

I would be grateful if others familiar with C would take a look at the above to see if they agree its a bug. I'm much more familiar with C++ than C (and the more I look at C the happier I get with this) so haven't had much to do with malloc/calloc/free (compared to new/delete operators) so I could be missing something, but I don't think so.

**Comment by cjones051073** [comment]
I'm attaching a log and crash report, just to save them for future reference...

[X11.bin_2018-09-02-225601_Oberon.crash.log](https://github.com/macports/macports-ports/files/2343807/X11.bin_2018-09-02-225601_Oberon.crash.log)
[org.macports.log](https://github.com/macports/macports-ports/files/2343805/org.macports.log)

**Comment by cjones051073** [comment]
Seems @RJVB beat me to it ;)

https://bugzilla.freedesktop.org/show_bug.cgi?id=107555

**Comment by cjones051073** [comment]
b.t.w. Just to be clear I am not suggesting the upstream bug is definitely in the file I patch. It was just the easiest thing to do to match the single calloc call. The bug could (perhaps more likely) be in the XQuartz specific code in the way it uses calloc. If on other platforms each element is individually allocated then the free loop is indeed the correct thing. Then, the fix would be to the allocation, not the free call.

**Comment by pmetzger** [comment]
Perhaps you should be commenting on the bug issue?

**Comment by cjones051073** [comment]
I cannot comment there (yet) as I don't have an account at the moment. I will though if/when I have something to add. I want to try an alternate fix to the xquartz specific side first..

**Comment by cjones051073** [comment]
I've reworked the patch again to instead of changing the free call, to instead patch the XQuartz specific parts to individually allocate each __GLXconfig struct, thus matching individual free calls.

File: x11/xorg-server-devel/Portfile [hunk 2]
```diff
@@ -1,49 +1,32 @@
...
 PortGroup       compiler_blacklist_versions 1.0
 
-name		xorg-server-devel
+name            xorg-server-devel
 conflicts       xorg-server
-set my_name	xorg-server
-version		1.19.99.1
-categories	x11 devel
+set my_name     xorg-server
+version         1.20.99.1
```
Comment (RJVB) [inline x11/xorg-server-devel/Portfile]: Suggestion: use a version that's based on the version tags, using `git describe`. For instance, commit #fabbaa8d6260da14fe5b7ca0f3f8748af16253a2 gives a decorated version

```
> git describe
xorg-server-1.19.0-636-gfabbaa8d6
```

which can be transformed to `version 1.19.0.636`. That will probably make the chronological relationship between port:xorg-server and port:xorg-server-devel a lot easier to understand.

**Comment by RJVB** [comment]
FWIW, I've been running that version 1.19.0.636 on 10.9 for a short while now, and it seems to work fine. The official XQuartz tends to crash on start even on my legacy system; I have yet to see that with this version.

File: x11/xorg-server-devel/Portfile (hunk 2 above)
Comment (cjones051073) [reply x11/xorg-server-devel/Portfile]: That is an interesting idea, but I just mirrored with what the maintainer did for the 1.19.x branch. I would prefer to stick with that and leave changing the scheme to him.

Note though the command for the branched used here gives

```
Titan ~/Downloads/xserver > git checkout server-1.20-branch
Branch 'server-1.20-branch' set up to track remote branch 'server-1.20-branch' from 'origin'.
Switched to a new branch 'server-1.20-branch'
Titan ~/Downloads/xserver > git describe
xorg-server-1.20.1
```

and that is not a good version to use...

**Comment by RJVB** [comment]
On Monday September 03 2018 02:25:57 Chris Jones wrote:

>That is an interesting idea, but I just mirrored with what the maintainer did for the 1.19.x branch. I would prefer to stick with that and leave changing the scheme to him.

Or you wait to see if he has objections, possibly in a different PR (which would have to go in first to avoid the need for touching the epoch)?

I use this approach in most of my ports that follow git repos, and it works fine as long as upstream is rigorous in tag use.

>xorg-server-1.20.1

>and that is not a good version to use...

Evidently you'd chop the "xorg-server-" bit (just like you'd chop off the "v" if they'd be using more standard release tags like v1.20.1), so you'd get 1.20.1 . That means you're on the exact commit that corresponds to the 1.20.1 release version (even if that version isn't released, but the whole point of release branches is create release versions...)

**Comment by RJVB** [comment]
Initial impression : working fine on my 10.9.5 system.

**Comment by cjones051073** [comment]
Thanks !

I have tried a build on my OSX 10.6 (the older test system I have). At first xorg-libXfont2 failed to build (there is now a PR fixing this..) but then I get a build failure looking like

```
In file included from pixmap.c:45:
../randr/randrstr.h:66:13: error: redefinition of typedef 'CARD32' is invalid in C [-Wtypedef-redefinition]
typedef XID RRLease;
            ^
In file included from pixmap.c:45:
In file included from ../randr/randrstr.h:49:
/opt/local/include/X11/extensions/randrproto.h:53:17: note: instantiated from:
#define RRLease CARD32
                ^
In file included from pixmap.c:33:
In file included from /opt/local/include/X11/X.h:79:
/opt/local/include/X11/Xmd.h:108:22: note: previous definition is here
typedef unsigned int CARD32;
                     ^
1 error generated.
```

Anyone seen anything like this before ?

**Comment by cjones051073** [comment]
Forcing the use of MacPorts clang 3.4 the update builds just fine on OSX 10.6. Interesting the warning is still there, but not alleviated to an error.

```
In file included from pixmap.c:45:
../randr/randrstr.h:66:13: error: redefinition of typedef 'CARD32' is invalid in C [-Wtypedef-redefinition]
typedef XID RRLease;
            ^
In file included from pixmap.c:45:
In file included from ../randr/randrstr.h:49:
/opt/local/include/X11/extensions/randrproto.h:53:17: note: instantiated from:
#define RRLease CARD32
                ^
In file included from pixmap.c:33:
In file included from /opt/local/include/X11/X.h:79:
/opt/local/include/X11/Xmd.h:108:22: note: previous definition is here
typedef unsigned int CARD32;
                     ^
1 error generated.
```

So it appears the newer compilers let this through.

**Comment by jeremyhu** [comment]
Please hold off on this.  There were numerous problems with 1.20.x the last time I tried it a month ago.

**Comment by cjones051073** [comment]
Of course. I'll make this WIP.

Do you happen to have a list of what those issues where, just for interest ?

**Comment by RJVB** [comment]
>Please hold off on this.  There were numerous problems with 1.20.x the last time I tried it a month ago.

Anything in particular to look for? For me it was a rather painless upgrade from 1.19.x, as far as I can tell after running it since I posted my previous message.

**Comment by jeremyhu** [comment]
There were some issues with RandR Fullscreen not working right (at least with my display setup).  Were you using it for any fullscreen apps?

**Comment by RJVB** [comment]
I have a dual-head set-up, and use XFWM4 (if that's relevant here). I'm also running in rootless mode (X11 and native windows intermingled). I just tried to put a few apps in fullscreen mode which worked without issues (even a remote app) but I don't know if they use RandR fullscreen. 
I also tried rooted mode, and saw nothing wrong there either.

Remember that I build with DRI2 and DRI3 support enabled, maybe that makes a difference here?

**Comment by RJVB** [comment]
Or, maybe you should just build the proposed upgrade and see if you can reproduce any of the issues you had? ;)

**Comment by cjones051073** [comment]
> Why was the 1001-XQuartz-Hack-around-an-issue-that-can-occur-on-macOS.patch patch resurrected here? Wasn't that integrated upstream?

Just an oversight. The Portfile still does not use it. I'll remove it.

**Comment by jeremyhu** [comment]
@pmetzger I agree, but regressions are bad, too.

If you guys are comfortable addressing any regressions if they come up, then go ahead and merge this in and squash them if they come up.

**Comment by cjones051073** [comment]
Many thanks for coming back to this. Of course if anything comes up I will do my best to look into it, but I suspect as a devel port this will not see a huge audience. Only once the mIn port is updated will that happen, and of course that is very much up to you to decide upon.

Based on previous comments I assume the others are in agreement so will merge this now.

**Comment by cjones051073** [comment]
Not really an issue but is it normal that github let me merge this whilst still WIP.? At work we use a gitlab instance and that does not allow wip requests to be merged, which to me makes sense....

**Comment by pmetzger** [comment]
WIP is just a label we created. It's understood only by humans, not by github itself.

**Comment by pmetzger** [comment]
@jeremyhu Your help updating and cleaning up the remaining issues with the X stuff would be very, very welcome. I know you're busy, so if you can't, you can't, but you're the primary source of expertise on a bunch of compiler and X stuff, especially xquartz itself.

**Comment by cjones051073** [comment]
@pmetzger I was really referring to the title. I had appended WIP to the start of that. In gitlab that automatically makes the PR unmergable until the work in progress status is removed.. guess github doesn’t work the same way...

**Comment by pmetzger** [comment]
@cjones051073 No, it doesn't work that way at all. That said, we can do an amazing amount of scripting with hooks, so if that was really wanted, it might be possible.
