### PR TITLE
openttd: fix build failure due to const char * rvalue

### PR DESCRIPTION
**Pull request by kencu**
newer compilers flag setting a char * to a const char * as an error

@neverpanic 

##### Description
```
/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_games_openttd/openttd/work/openttd-1.6.1/src/fileio.cpp:1037:8: error: cannot initialize a variable of type 'char *' with an rvalue of type 'const char *'
        char *app_bundle = strchr(exe, '.');
              ^            ~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [fileio.o] Error 1
```

[also FYI game is now at 1.7.1 - not upgraded here to keep the commits separate]

### CODE REVIEW

**Comment by neverpanic** [comment]
Thanks. Did you also report this to the developers of openttd, or is it maybe already fixed in 1.7.1?

Are you also working on the 1.7.1 update? Those can be tricky at times, because openttd developers usually build on older machines where deprecated APIs are still available.

**Comment by kencu** [comment]
The same patch is still needed in 1.7.1. I haven't bumped it upstream as yet. I have built 1.7.1 as a bundle version - just moving to your "unix-style" version to see if it builds as easily, and if so, I'll make a PR for that too.

**Comment by kencu** [comment]
Submitted upstream <https://bugs.openttd.org/task/6575?project=1>

**Comment by neverpanic** [comment]
Does OpenTTD support building an app bundle now? Maybe we should switch to port to installing that instead?

I referenced the bug report from the patchfile in 4c9a85a40e45d8d254b5c6712580e47f7d1db5fb.

**Comment by kencu** [comment]
Yes, openTTD seems to build fine as a bundle. This target does it:

```destroot.target         bundle```

I don't know if it would find all the bits you have so helpfully preinstalled (graphics , sounds) tho...
