### PR TITLE
mariadb-10.5: stdint.h needed on 10.8 and earlier

### PR DESCRIPTION
**Pull request by chrstphrchvz**
#### Description

Build failure was observed on the [10.7](https://build.macports.org/builders/ports-10.7_x86_64-builder/builds/28718/steps/install-port/logs/stdio) and [10.8](https://build.macports.org/builders/ports-10.8_x86_64-builder/builds/24252/steps/install-port/logs/stdio) builders (10.6 fails sooner due to separate issues):

```
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_databases_mariadb-10.5/mariadb-10.5/work/server-mariadb-10.5.5/storage/perfschema/my_thread.h:49:3: error: unknown type name 'uint64_t'
  uint64_t tid64;
  ^
```

I believe this is fixed by manually including `<stdint.h>`.

###### Type(s)

- [x] bugfix
###### ~~Tested on~~

Only the patch phase has been tested.

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
> Port mariadb-10.5 **fail** on xcode8.3. [Log](https://paste.macports.org/fa9f8b2b3d75)
> Port mariadb-10.5 **fail** on xcode7.3. [Log](https://paste.macports.org/2966c9ef5e54)

```
/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_databases_mariadb-10.5/mariadb-10.5/work/server-mariadb-10.5.5/storage/maria/libmarias3/version:1:1: error: expected unqualified-id
3.1.2
^
```

```
/opt/local/libexec/llvm-9.0/bin/../include/c++/v1/cstddef:49:9: error: no member named 'ptrdiff_t' in the global namespace
using ::ptrdiff_t;
      ~~^
```

and in various headers more generally:
```
error: unknown type name 'ptrdiff_t'; did you mean 'my_ptrdiff_t'?
```

These failures are new (10.11 and 10.12 are known-working: https://ports.macports.org/port/mariadb-10.5/builds), but I don't see how they're introduced by this PR. Some of the `ptrdiff_t` errors might be resolved by manually including `<stddef.h>`/`<cstddef>`, but in some cases they appear to be **missing from `llvm-9.0`'s headers**.

**Comment by chrstphrchvz** [comment]
The new build issues strongly resemble https://trac.macports.org/ticket/59575

**Comment by kencu** [comment]
all the mysql and probably all the mariadb ports need this patch I made <https://github.com/macports/macports-ports/commit/44c085bfacc1d8163d7bcf57a3c499e0bef4ce1b#diff-4b186eec0fc2603eb8d56dd479b6737f> to build successfully with new clangs that default to c++17.

And the libtool patch.

After that, they need a new-enough libc++.dylib.

**Comment by kencu** [comment]
one easy thing for you to do, if you don't have any VMs, would be to work on getting ports to build with clang-9.0 or clang-10.

For example, that same error happens on Mojave when building mariadb-10.5 with clang-9.0.

I think it is likely because there are more VERSION files in the source:
```
$ find . | grep VERSION
./storage/columnstore/columnstore/VERSION
./storage/maria/libmarias3/VERSION
./VERSION.txt
```
but you can't just rename them to VERSION.txt -- your get this 
```
Make Error at storage/columnstore/columnstore/cmake/columnstore_version.cmake:33 (MESSAGE):
  VERSION file cannot be parsed.
Call Stack (most recent call first):
  storage/columnstore/columnstore/cmake/columnstore_version.cmake:54 (GET_COLUMNSTORE_VERSION)
  storage/columnstore/columnstore/CMakeLists.txt:95 (INCLUDE)
```
you have to do a proper fix (like the patch I referenced above).

**Comment by chrstphrchvz** [comment]
Fortunately storage/maria/libmarias3/VERSION and storage/columnstore/columnstore/VERSION appear to have been introduced in MariaDB 10.5, and are not present in 10.4 or earlier.

**Comment by kencu** [comment]
So, success, after fixing the VERSION issue:
```
port -v installed mariadb-10.5
The following ports are currently installed:
  mariadb-10.5 @10.5.5_0 (active) platform='darwin 10' archs='x86_64' date='2020-08-24T23:15:36-0700'
```

This ```uint64_t``` business is a bit strange.

There are various tests being done during configure that show this on 10.6:
```
-- Performing Test HAVE_PTHREAD_THREADID_NP
-- Performing Test HAVE_PTHREAD_THREADID_NP - Success
-- Performing Test HAVE_SYS_GETTID
-- Performing Test HAVE_SYS_GETTID - Success
-- Performing Test HAVE_PTHREAD_GETTHREADID_NP
-- Performing Test HAVE_PTHREAD_GETTHREADID_NP - Failed
```

and then in the source they do this:
```
#ifdef HAVE_PTHREAD_GETTHREADID_NP
#include <pthread_np.h>
#endif
```
So older systems (10.6, at least) fails ```HAVE_PTHREAD_GETTHREADID_NP``` and also doesn't have a header named ```<pthread_np.h>``` -- so no error there, but apparently nothing ever includes the standard ```<sys/types.h>```  and so there is no definition for ```uint64_t```.

Including ```<stdint.h>``` does work (after fixing the VERSION things). I suspect that including ```<sys/types.h>``` would too, but I didn't test that yet.

we could also just use the pure definition:
```
#ifndef _UINT64_T
#define _UINT64_T
typedef unsigned long long   uint64_t;
#endif /* _UINT64_T */
```

For upstream ... well it doesn't matter -- they won't accept any patches upstream anyway for older macOS systems, so we're on our own here.
