### PR TITLE
filezilla: update to 3.63.2.1

### PR DESCRIPTION
**Pull request by sideeffect42**
#### Description

Update the FileZilla port to version 3.62.2.1 and libfilezilla to 0.41.1.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 12.6.3 21G419 x86_64
Xcode 14.2 14C18

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by barracuda156** [comment]
Has this been tested on older macOS? Last time I had to revert back to 0.36.0 from 0.38.1 for some reason (cannot remember now what specifically kept failing): https://github.com/macports/macports-ports/pull/15992#issuecomment-1236406494

**Comment by sideeffect42** [comment]
> Has this been tested on older macOS?

No, it hasn't.

The only thing I tested on older verions (including 10.5.8 ppc) is the system version patch.

I can test the build on 10.5.8 ppc if desired.

**Comment by barracuda156** [comment]
> I can test the build on 10.5.8 ppc if desired.

If that is not a burden, please. I am away from native PPC hardware for next 10 days.

**Comment by barracuda156** [comment]
@sideeffect42 I see. It does build on 10.6.8 for `ppc` with GCC 12, but I have no 10.5.8 here to check if it OS issue or compiler issue.

**Comment by sideeffect42** [comment]
> @sideeffect42 I see. It does build on 10.6.8 for `ppc` with GCC 12, but I have no 10.5.8 here to check if it OS issue or compiler issue.

These two errors are clearly compiler errors.
Unfortunately both involve some non-trivial C++.

**Comment by sideeffect42** [comment]
Building the FileZilla port on 10.5.8 also results in numerous errors.
Many should be fixable without too much effort.

**Comment by kencu** [comment]
the last one I have working on 10.6 is 3.30.0, from 2018, with a few simple patches.

**Comment by barracuda156** [comment]
> the last one I have working on 10.6 is 3.30.0, from 2018, with a few simple patches.

Patches may be helpful to have, actually. Were those in your SL ports repo?

**Comment by sideeffect42** [comment]
I was able to fix the build of libfilezilla using GCC 7.

Also I made some progress in patching FileZilla to build on Leopard PowerPC.
It now compiles without errors, but the linking phase does not yet work for me:
```
Undefined symbols for architecture ppc:
  "wxBitmapBase::GetScaledWidth() const", referenced from:
      wxStaticBitmap::GetBitmapSize()       in filezilla-statusbar.o
  "wxBitmapBase::GetScaledHeight() const", referenced from:
      wxStaticBitmap::GetBitmapSize()       in filezilla-statusbar.o
ld: symbol(s) not found for architecture ppc
collect2: error: ld returned 1 exit status
```

I did some grepping to try to figure out where these functions are used, but I didn't yet get very far.

Another place that certainly needs working on is the Mac-specific drag&drop code. To get it to compile I mostly cpp-guarded off most of the implementation.
If someone is experienced with AppKit APIs I'd be more than happy with some assistance.

**Comment by barracuda156** [comment]
@sideeffect42 I will try FileZilla on my end to see if it builds in Rosetta and update you.

**Comment by sideeffect42** [comment]
> UPD. By the way, `O_CLOEXEC` is there in `LegacySupport`, I believe.

From what I could tell it's only `#define O_CLOEXEC 0` which effectively just ignores the flag.

Without having looked into the locations where the `O_CLOEXEC` flag is used, my gut feeling is that having the patch is better than ignoring the flag since FileZilla communicates network services.

**Comment by kencu** [comment]
that's a nice job providing the functionality of O_CLOEXEC on the older systems.

I wonder if that might lead to some opportunity to do that automatically in legacysupport, by overriding the "open" call on systems without O_CLOEXEC? We have done that for several other functions, and there's always a bit of back-and-forth sorting it out but once we have it sorted out, it works pretty nicely.

Check out our realpath override, for example:

https://github.com/macports/macports-legacy-support/blob/master/src/macports_legacy_realpath.c

**Comment by pmetzger** [comment]
This has been sitting untouched now for about nine months. What's the notion for finishing it?

**Comment by pmetzger** [comment]
@kencu I assume you have no interest in updating the port?

**Comment by kencu** [comment]
This current version installs perfectly on a Sonoma arm64 system, rebased onto the current ports master.

So lets get this in now, and then updating further can be done soon enough, I think.

This has been waiting here much too long for anyone's comfort.

**Comment by sideeffect42** [comment]
@pmetzger @kencu apologies for the delayed response, I've had a very busy schedule lately.

I've seen this PR was already merged and that's fine. It should work just fine on any recent version of macOS and also on PowerPC IIRC the application should be useable.

The only thing I remember was that most/all of the drag and drop code being `#if`ed on old versions of OS X.
I originally planned to read up on the AppKit APIs to implement drag and drop support for old systems but never got around to it.

Updating to port to the latest version should probably be possible. I'll see what I can do and if I get anything together I'll open another PR for the update.
(Very likely without drag&drop, either.)

**Comment by barracuda156** [comment]
> also on PowerPC IIRC the application should be useable.

@sideeffect42 
Both lib and app build for me as-is with no changes, but launching the app fails: https://trac.macports.org/ticket/69113
If you have tested on 10.5.8 `ppc` and can confirm the app in fact works and not merely builds, please let me know.

(I have Qt4 working pretty much robustly, but X11, GTK and WxWidgets are a mess, so it is quite possible that just some env settings are wrong. Though I have seen odd failures with WxWidgets even on Sonoma.)

**Comment by barracuda156** [comment]
@sideeffect42 It is not the case where powerpc should be any stopper to merge an update, of course. We can fix it when there is time for that.
