### PR TITLE
gdal: attempt to fix build on macOS 10.11

### PR DESCRIPTION
**Pull request by chrstphrchvz**
#### Description
See https://github.com/macports/macports-ports/pull/8217#discussion_r488560049

###### Tested on

Untested. See if Travis CI 10.11 "Xcode 7.3" build succeeds. 
###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by chrstphrchvz** [comment]
> Port gdal **fail** on xcode8.3. [Log](https://paste.macports.org/d4e78f3af1c5)

```
ogrgeopackagetablelayer.cpp:300:50: error: call to 'abs' is ambiguous
                            const int TZOffset = std::abs(sField.Date.TZFlag - 100) * 15;
                                                 ^~~~~~~~
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:664:1: note: candidate function
abs(float __lcpp_x) _NOEXCEPT {return fabsf(__lcpp_x);}
^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:668:1: note: candidate function
abs(double __lcpp_x) _NOEXCEPT {return fabs(__lcpp_x);}
^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:672:1: note: candidate function
abs(long double __lcpp_x) _NOEXCEPT {return fabsl(__lcpp_x);}
^
1 error generated.
```

Xcode 8.3 is not enough either. Raising to Xcode 9…
