### PR TITLE
proj7: fix build on 10.8-10.9

### PR DESCRIPTION
**Pull request by chrstphrchvz**
#### Description

Build failure observed on [10.8](https://build.macports.org/builders/ports-10.8_x86_64-builder/builds/24733/steps/install-port/logs/stdio) and [10.9](https://build.macports.org/builders/ports-10.9_x86_64-builder/builds/125908/steps/install-port/logs/stdio):
```
libtool: compile:  /usr/bin/clang++ -std=c++11 -DHAVE_CONFIG_H -I. -DPROJ_LIB=\"/opt/local/lib/proj7/share/proj\" -DMUTEX_pthread -I../include -DTIFF_ENABLED -I/opt/local/include -DCURL_ENABLED -I/opt/local/include -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wshorten-64-to-32 -Wshadow -Werror=vla -Wnull-dereference -Wextra-semi -Wdocumentation -Wno-documentation-deprecated-sync -Wunused-private-field -Wmissing-declarations -Wnon-virtual-dtor -Weffc++ -Woverloaded-virtual -Wweak-vtables -Wdeprecated -Wabstract-vbase-init -pipe -Os -stdlib=libc++ -arch x86_64 -fvisibility=hidden -DNOMINMAX -MT iso19111/coordinateoperation.lo -MD -MP -MF iso19111/.deps/coordinateoperation.Tpo -c iso19111/coordinateoperation.cpp  -fno-common -DPIC -o iso19111/.libs/coordinateoperation.o
iso19111/coordinateoperation.cpp:13719:9: error: return type 'nn<[...]>' must match previous return type 'const nn<[...]>' when lambda expression has unspecified explicit return type
        return ret;
        ^
…
libtool: compile:  /usr/bin/clang++ -std=c++11 -DHAVE_CONFIG_H -I. -DPROJ_LIB=\"/opt/local/lib/proj7/share/proj\" -DMUTEX_pthread -I../include -DTIFF_ENABLED -I/opt/local/include -DCURL_ENABLED -I/opt/local/include -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wshorten-64-to-32 -Wshadow -Werror=vla -Wnull-dereference -Wextra-semi -Wdocumentation -Wno-documentation-deprecated-sync -Wunused-private-field -Wmissing-declarations -Wnon-virtual-dtor -Weffc++ -Woverloaded-virtual -Wweak-vtables -Wdeprecated -Wabstract-vbase-init -pipe -Os -stdlib=libc++ -arch x86_64 -fvisibility=hidden -DNOMINMAX -MT iso19111/io.lo -MD -MP -MF iso19111/.deps/io.Tpo -c iso19111/io.cpp  -fno-common -DPIC -o iso19111/.libs/io.o
iso19111/io.cpp:4606:9: error: return type 'const nn<[...]>' must match previous return type 'nn<[...]>' when lambda expression has unspecified explicit return type
        return crs;
        ^
iso19111/io.cpp:6216:33: error: return type 'const nn<[...]>' must match previous return type 'nn<[...]>' when lambda expression has unspecified explicit return type
                                return obj;
                                ^
iso19111/io.cpp:8265:17: error: return type 'nn<[...]>' must match previous return type 'const nn<[...]>' when lambda expression has unspecified explicit return type
                return GeodeticReferenceFrame::create(
                ^
iso19111/io.cpp:8314:25: error: return type 'nn<[...]>' must match previous return type 'const nn<[...]>' when lambda expression has unspecified explicit return type
                        return GeodeticReferenceFrame::create(
                        ^
```

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?

### CODE REVIEW

**Comment by ryandesign** [comment]
Instead of blacklisting old compilers, can we fix the code? Is there an upstream bug report for this problem?

**Comment by chrstphrchvz** [comment]
I do not completely understand this error, but I'm not sure the code is at fault here. From what I can tell, it looks like there was an intentional change/improvement/clarification to C++11 compiler behavior (lambda return type deduction) introduced in Xcode 6.3 possibly as part of C++14 support. Newer clang versions don't say that the new behavior being relied on is non-standard: using `configure.cxxflags-append -pedantic`, there are no complaints from Xcode 12 resembling the Xcode < 6.3 errors.

I guess it would still be possible in this case to add explicit return types and make older C++11 compilers happy. I could not figure out exactly what types are deduced by newer compilers, but `const` rather than non-`const` is what I expect to be used (something non-`const` can be cast to and returned as `const`, whereas it doesn't make sense to return something `const` as non-`const`).
