### PR TITLE
watchman, folly, fbthrift, fb303, proxygen, wangle, fizz, & edencommon: update to 2023.05.15.00

### PR DESCRIPTION
**Pull request by herbygillot**
Update `watchman` to 2023.05.15.00, as well other FB libraries, including:

- folly
- edencommon
- fizz
- folly
- wangle
- fbthrift
- fb303
- proxygen

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with ~`sudo port -vst install`~ `sudo port -d destroot`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@herbygillot Oh, nice. I am trying right now to fix building tests for `folly`, and it is better if the port is updated first.

**Comment by herbygillot** [comment]
> @herbygillot Oh, nice. I am trying right now to fix building tests for `folly`, and it is better if the port is updated first.

I also saw that `fatal` is ready to update to this same version (`2023.05.15.00`)

**Comment by barracuda156** [comment]
> > @herbygillot Oh, nice. I am trying right now to fix building tests for `folly`, and it is better if the port is updated first.
> 
> I also saw that `fatal` is ready to update to this same version (`2023.05.15.00`)

Yeah, better keep them all in sync.

**Comment by herbygillot** [comment]
@barracuda156: `folly` failed to build in macOS 10.15: https://build.macports.org/builders/ports-10.15_x86_64-builder/builds/141926/steps/install-port/logs/stdio

```
In file included from /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_folly/folly/work/folly-v2023.05.15.00/folly/io/async/fdsock/AsyncFdSocket.cpp:17:
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_folly/folly/work/folly-v2023.05.15.00/folly/io/async/fdsock/AsyncFdSocket.h:189:25: error: non-type template argument is not a constant expression
    std::array<uint8_t, CMSG_SPACE(sizeof(int) * kMaxFdsPerSocketMsg)>
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/socket.h:652:33: note: expanded from macro 'CMSG_SPACE'
#define CMSG_SPACE(l)           (__DARWIN_ALIGN32(sizeof(struct cmsghdr)) + __DARWIN_ALIGN32(l))
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_folly/folly/work/folly-v2023.05.15.00/folly/io/async/fdsock/AsyncFdSocket.h:189:25: note: cast that performs the conversions of a reinterpret_cast is not allowed in a constant expression
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/socket.h:652:34: note: expanded from macro 'CMSG_SPACE'
#define CMSG_SPACE(l)           (__DARWIN_ALIGN32(sizeof(struct cmsghdr)) + __DARWIN_ALIGN32(l))
                                 ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/i386/_param.h:43:42: note: expanded from macro '__DARWIN_ALIGN32'
#define       __DARWIN_ALIGN32(p)       ((__darwin_size_t)((char *)(__darwin_size_t)(p) + __DARWIN_ALIGNBYTES32) &~ __DARWIN_ALIGNBYTES32)
                                         ^
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_folly/folly/work/folly-v2023.05.15.00/folly/io/async/fdsock/AsyncFdSocket.cpp:39:3: error: no matching member function for call to 'connect'
  connect(nullptr, address, connectTimeout);
  ^~~~~~~
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_folly/folly/work/folly-v2023.05.15.00/folly/io/async/AsyncSocket.h:596:16: note: candidate function not viable: no known conversion from 'folly::AsyncFdSocket' to 'folly::AsyncSocket' for object argument
  virtual void connect(
               ^
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_folly/folly/work/folly-v2023.05.15.00/folly/io/async/AsyncSocket.h:604:8: note: candidate function not viable: no known conversion from 'folly::AsyncFdSocket' to 'folly::AsyncSocket' for object argument
  void connect(
       ^
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_folly/folly/work/folly-v2023.05.15.00/folly/io/async/fdsock/AsyncFdSocket.cpp:64:27: error: cannot initialize object parameter of type 'const folly::AsyncSocket' with an expression of type 'folly::AsyncFdSocket'
  DCHECK_EQ(&sendMsgCob_, getSendMsgParamsCB());
                          ^~~~~~~~~~~~~~~~~~
/opt/local/include/glog/logging.h:1364:44: note: expanded from macro 'DCHECK_EQ'
    GLOG_MSVC_POP_WARNING() CHECK_EQ(val1, val2)
                                           ^~~~
/opt/local/include/glog/logging.h:923:54: note: expanded from macro 'CHECK_EQ'
#define CHECK_EQ(val1, val2) CHECK_OP(_EQ, ==, val1, val2)
                                                     ^~~~
/opt/local/include/glog/logging.h:899:32: note: expanded from macro 'CHECK_OP'
  CHECK_OP_LOG(name, op, val1, val2, google::LogMessageFatal)
                               ^~~~
/opt/local/include/glog/logging.h:892:44: note: expanded from macro 'CHECK_OP_LOG'
             google::GetReferenceableValue(val2),        \
                                           ^~~~
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_folly/folly/work/folly-v2023.05.15.00/folly/io/async/fdsock/AsyncFdSocket.cpp:67:21: error: no matching constructor for initialization of 'folly::DelayedDestructionBase::DestructorGuard'
    DestructorGuard dg(this);
                    ^  ~~~~
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_folly/folly/work/folly-v2023.05.15.00/folly/io/async/DelayedDestructionBase.h:67:14: note: candidate constructor not viable: no known conversion from 'folly::AsyncFdSocket *' to 'folly::DelayedDestructionBase *' for 1st argument
    explicit DestructorGuard(DelayedDestructionBase* dd) : dd_(dd) {
             ^
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_folly/folly/work/folly-v2023.05.15.00/folly/io/async/DelayedDestructionBase.h:74:5: note: candidate constructor not viable: no known conversion from 'folly::AsyncFdSocket *' to 'const folly::DelayedDestructionBase::DestructorGuard' for 1st argument
    DestructorGuard(const DestructorGuard& dg) : DestructorGuard(dg.dd_) {}
    ^
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_folly/folly/work/folly-v2023.05.15.00/folly/io/async/DelayedDestructionBase.h:76:5: note: candidate constructor not viable: no known conversion from 'folly::AsyncFdSocket *' to 'folly::DelayedDestructionBase::DestructorGuard' for 1st argument
    DestructorGuard(DestructorGuard&& dg) noexcept
    ^
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_folly/folly/work/folly-v2023.05.15.00/folly/io/async/fdsock/AsyncFdSocket.cpp:70:9: error: cannot initialize object parameter of type 'folly::AsyncSocket' with an expression of type 'folly::AsyncFdSocket'
        withAddr("Cannot send FDs without at least 1 data byte"));
        ^~~~~~~~
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_folly/folly/work/folly-v2023.05.15.00/folly/io/async/fdsock/AsyncFdSocket.cpp:71:12: error: no matching member function for call to 'failWrite'
    return failWrite(__func__, callback, 0, ex);
           ^~~~~~~~~
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_folly/folly/work/folly-v2023.05.15.00/folly/io/async/AsyncSocket.h:1621:8: note: candidate function not viable: no known conversion from 'folly::AsyncFdSocket' to 'folly::AsyncSocket' for object argument
  void failWrite(
       ^
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_folly/folly/work/folly-v2023.05.15.00/folly/io/async/AsyncSocket.h:1626:8: note: candidate function not viable: requires 2 arguments, but 4 were provided
  void failWrite(const char* fn, const AsyncSocketException& ex);
       ^
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_folly/folly/work/folly-v2023.05.15.00/folly/io/async/fdsock/AsyncFdSocket.cpp:86:21: error: no matching constructor for initialization of 'folly::DelayedDestructionBase::DestructorGuard'
    DestructorGuard dg(this);
                    ^  ~~~~
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_folly/folly/work/folly-v2023.05.15.00/folly/io/async/DelayedDestructionBase.h:67:14: note: candidate constructor not viable: no known conversion from 'folly::AsyncFdSocket *' to 'folly::DelayedDestructionBase *' for 1st argument
    explicit DestructorGuard(DelayedDestructionBase* dd) : dd_(dd) {
             ^
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_folly/folly/work/folly-v2023.05.15.00/folly/io/async/DelayedDestructionBase.h:74:5: note: candidate constructor not viable: no known conversion from 'folly::AsyncFdSocket *' to 'const folly::DelayedDestructionBase::DestructorGuard' for 1st argument
    DestructorGuard(const DestructorGuard& dg) : DestructorGuard(dg.dd_) {}
    ^
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_folly/folly/work/folly-v2023.05.15.00/folly/io/async/DelayedDestructionBase.h:76:5: note: candidate constructor not viable: no known conversion from 'folly::AsyncFdSocket *' to 'folly::DelayedDestructionBase::DestructorGuard' for 1st argument
    DestructorGuard(DestructorGuard&& dg) noexcept
    ^
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_folly/folly/work/folly-v2023.05.15.00/folly/io/async/fdsock/AsyncFdSocket.cpp:89:9: error: cannot initialize object parameter of type 'folly::AsyncSocket' with an expression of type 'folly::AsyncFdSocket'
        withAddr("Buffer was already owned by this socket"));
        ^~~~~~~~
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_folly/folly/work/folly-v2023.05.15.00/folly/io/async/fdsock/AsyncFdSocket.cpp:90:12: error: no matching member function for call to 'failWrite'
    return failWrite(__func__, callback, 0, ex);
           ^~~~~~~~~
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_folly/folly/work/folly-v2023.05.15.00/folly/io/async/AsyncSocket.h:1621:8: note: candidate function not viable: no known conversion from 'folly::AsyncFdSocket' to 'folly::AsyncSocket' for object argument
  void failWrite(
       ^
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_folly/folly/work/folly-v2023.05.15.00/folly/io/async/AsyncSocket.h:1626:8: note: candidate function not viable: requires 2 arguments, but 4 were provided
  void failWrite(const char* fn, const AsyncSocketException& ex);
       ^
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_folly/folly/work/folly-v2023.05.15.00/folly/io/async/fdsock/AsyncFdSocket.cpp:94:3: error: cannot initialize object parameter of type 'folly::AsyncSocket' with an expression of type 'folly::AsyncFdSocket'
  writeChain(callback, std::move(buf), flags);
  ^~~~~~~~~~
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_folly/folly/work/folly-v2023.05.15.00/folly/io/async/fdsock/AsyncFdSocket.cpp:101:16: error: cannot initialize object parameter of type 'folly::AsyncSocket' with an expression of type 'folly::AsyncFdSocket'
  AsyncSocket::setSendMsgParamCB(&sendMsgCob_);
               ^~~~~~~~~~~~~~~~~
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_folly/folly/work/folly-v2023.05.15.00/folly/io/async/fdsock/AsyncFdSocket.cpp:108:16: error: cannot initialize object parameter of type 'folly::AsyncSocket' with an expression of type 'folly::AsyncFdSocket'
  AsyncSocket::releaseIOBuf(std::move(buf), callback);
               ^~~~~~~~~~~~
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_folly/folly/work/folly-v2023.05.15.00/folly/io/async/fdsock/AsyncFdSocket.cpp:272:18: error: cannot initialize object parameter of type 'folly::AsyncSocket' with an expression of type 'folly::AsyncFdSocket'
    AsyncSocket::failRead(__func__, ex);
                 ^~~~~~~~
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_folly/folly/work/folly-v2023.05.15.00/folly/io/async/fdsock/AsyncFdSocket.cpp:281:18: error: cannot initialize object parameter of type 'folly::AsyncSocket' with an expression of type 'folly::AsyncFdSocket'
    AsyncSocket::failRead(__func__, ex);
                 ^~~~~~~~
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_folly/folly/work/folly-v2023.05.15.00/folly/io/async/fdsock/AsyncFdSocket.cpp:304:37: error: cannot initialize object parameter of type 'const folly::AsyncSocket' with an expression of type 'folly::AsyncFdSocket'
  DCHECK_EQ(&readAncillaryDataCob_, getReadAncillaryDataCallback());
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/include/glog/logging.h:1364:44: note: expanded from macro 'DCHECK_EQ'
    GLOG_MSVC_POP_WARNING() CHECK_EQ(val1, val2)
                                           ^~~~
/opt/local/include/glog/logging.h:923:54: note: expanded from macro 'CHECK_EQ'
#define CHECK_EQ(val1, val2) CHECK_OP(_EQ, ==, val1, val2)
                                                     ^~~~
/opt/local/include/glog/logging.h:899:32: note: expanded from macro 'CHECK_OP'
  CHECK_OP_LOG(name, op, val1, val2, google::LogMessageFatal)
                               ^~~~
/opt/local/include/glog/logging.h:892:44: note: expanded from macro 'CHECK_OP_LOG'
             google::GetReferenceableValue(val2),        \
                                           ^~~~
1 warning and 15 errors generated.
```

**Comment by barracuda156** [comment]
I will run the build on my systems tomorrow.

Upstream of `folly` is known for breaking things frequently: that is why we do not update these ports too often :)
