### PR TITLE
py3[6789]-pandas: attempt to fix build on macOS 10.8

### PR DESCRIPTION
**Pull request by chrstphrchvz**
#### Description

Build failure is currently observed for [`py36-pandas`](https://build.macports.org/builders/ports-10.8_x86_64-builder/builds/25377/steps/install-port/logs/stdio), [`py37-pandas`](https://build.macports.org/builders/ports-10.8_x86_64-builder/builds/25382/steps/install-port/logs/stdio), and [`py38-pandas`](https://build.macports.org/builders/ports-10.8_x86_64-builder/builds/25369/steps/install-port/logs/stdio) on 10.8, involving Cythonized code which MacPorts' clang 9.0 (used on macOS 10.6) and newer Xcode clang do not complain about:

```
pandas/_libs/window/aggregations.cpp:39797:30: error: use of logical '&&' with constant operand [-Werror,-Wconstant-logical-operand]
  if ((CYTHON_USE_TYPE_SLOTS && CYTHON_USE_PYTYPE_LOOKUP) && likely(!__pyx_type___pyx_MemviewEnum.tp_dictoffset && __pyx_type___pyx_MemviewEnum.tp_getattro == PyObject_GenericGetAttr)) {
                             ^  ~~~~~~~~~~~~~~~~~~~~~~~~
pandas/_libs/window/aggregations.cpp:39797:30: note: use '&' for a bitwise operation
  if ((CYTHON_USE_TYPE_SLOTS && CYTHON_USE_PYTYPE_LOOKUP) && likely(!__pyx_type___pyx_MemviewEnum.tp_dictoffset && __pyx_type___pyx_MemviewEnum.tp_getattro == PyObject_GenericGetAttr)) {
                             ^~
                             &
pandas/_libs/window/aggregations.cpp:39797:30: note: remove constant to silence this warning
  if ((CYTHON_USE_TYPE_SLOTS && CYTHON_USE_PYTYPE_LOOKUP) && likely(!__pyx_type___pyx_MemviewEnum.tp_dictoffset && __pyx_type___pyx_MemviewEnum.tp_getattro == PyObject_GenericGetAttr)) {
                            ~^~~~~~~~~~~~~~~~~~~~~~~~~~~
pandas/_libs/window/aggregations.cpp:39814:30: error: use of logical '&&' with constant operand [-Werror,-Wconstant-logical-operand]
  if ((CYTHON_USE_TYPE_SLOTS && CYTHON_USE_PYTYPE_LOOKUP) && likely(!__pyx_type___pyx_memoryview.tp_dictoffset && __pyx_type___pyx_memoryview.tp_getattro == PyObject_GenericGetAttr)) {
                             ^  ~~~~~~~~~~~~~~~~~~~~~~~~
pandas/_libs/window/aggregations.cpp:39814:30: note: use '&' for a bitwise operation
  if ((CYTHON_USE_TYPE_SLOTS && CYTHON_USE_PYTYPE_LOOKUP) && likely(!__pyx_type___pyx_memoryview.tp_dictoffset && __pyx_type___pyx_memoryview.tp_getattro == PyObject_GenericGetAttr)) {
                             ^~
                             &
pandas/_libs/window/aggregations.cpp:39814:30: note: remove constant to silence this warning
  if ((CYTHON_USE_TYPE_SLOTS && CYTHON_USE_PYTYPE_LOOKUP) && likely(!__pyx_type___pyx_memoryview.tp_dictoffset && __pyx_type___pyx_memoryview.tp_getattro == PyObject_GenericGetAttr)) {
                            ~^~~~~~~~~~~~~~~~~~~~~~~~~~~
pandas/_libs/window/aggregations.cpp:39829:30: error: use of logical '&&' with constant operand [-Werror,-Wconstant-logical-operand]
  if ((CYTHON_USE_TYPE_SLOTS && CYTHON_USE_PYTYPE_LOOKUP) && likely(!__pyx_type___pyx_memoryviewslice.tp_dictoffset && __pyx_type___pyx_memoryviewslice.tp_getattro == PyObject_GenericGetAttr)) {
                             ^  ~~~~~~~~~~~~~~~~~~~~~~~~
pandas/_libs/window/aggregations.cpp:39829:30: note: use '&' for a bitwise operation
  if ((CYTHON_USE_TYPE_SLOTS && CYTHON_USE_PYTYPE_LOOKUP) && likely(!__pyx_type___pyx_memoryviewslice.tp_dictoffset && __pyx_type___pyx_memoryviewslice.tp_getattro == PyObject_GenericGetAttr)) {
                             ^~
                             &
pandas/_libs/window/aggregations.cpp:39829:30: note: remove constant to silence this warning
  if ((CYTHON_USE_TYPE_SLOTS && CYTHON_USE_PYTYPE_LOOKUP) && likely(!__pyx_type___pyx_memoryviewslice.tp_dictoffset && __pyx_type___pyx_memoryviewslice.tp_getattro == PyObject_GenericGetAttr)) {
                            ~^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?

### CODE REVIEW

**Review by stromnov — APPROVED** [review]

**Comment by ryandesign** [comment]
I would instead suggest removing `-Werror` from the compile flags.

**Comment by kencu** [comment]
@chrstphrchvz --- would you like to do as Ryan asked?

**Comment by chrstphrchvz** [comment]
Pushed commit to update to 1.1.3 (bugfix release: https://pandas.pydata.org/pandas-docs/version/1.1.3/whatsnew/v1.1.3.html); compiles on macOS 10.15.7 using Xcode 12 command line tools, Python 3.8.6.

Someone suggested to upstream that they stop using `-Werror` in releases, but at least one of the developers wants to keep using it: pandas-dev/pandas#33315. I suggest raising the issue there if `-Werror` does not belong in MacPorts or releases in general, and/or if upstream (possibly to Cython rather than pandas) should do something to remain compatible with unmaintained compilers.

@stromnov, what is your preference for dealing with this?

**Comment by chrstphrchvz** [comment]
Adding patch to fix implicit function declaration in `py27-pandas`:
```
In file included from pandas/_libs/lib.c:641:
pandas/_libs/src/parse_helper.h:141:26: error: implicit declaration of function 'tolower_ascii' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    for (; *p; ++p) *p = tolower_ascii(*p);
                         ^
```

I'm not sure why this error is observed for the Xcode 11.7 Azure CI builder.

I do not know if other adjustments in the patch affect functionality, so I have increased the revision.

**Comment by chrstphrchvz** [comment]
Rebased since the maintainer updated the port to 1.1.3 and added a Python 3.9 subport (b151864263).

**Comment by chrstphrchvz** [comment]
Splitting `py27-pandas` change off to #9080 since that is simpler/separate/more critical, so ignore its build failures here.

**Comment by ryandesign** [comment]
> I would instead suggest removing `-Werror` from the compile flags.

I've done this in b024436774d25aeada605045d54972239dbc8e95; sorry, I forgot about this PR, so it needs to be rebased again.

**Comment by chrstphrchvz** [comment]
Unless @stromnov prefers avoiding compilers over removing `-Werror`, this can be closed without merging.

**Comment by ryandesign** [comment]
In MacPorts ports we prefer not to use `-Werror` ever because you never know when a new version of Xcode will contain a new version of clang that introduces new warnings.
