### PR TITLE
aircrack-ng: fix up build on 10.6

### PR DESCRIPTION
**Pull request by evanmiller**
#### Description

* Fix a duplicate symbol error building on 10.6
* Remove unneeded `dprintf` patch (this function is now provided by legacysupport)
* ~~Rename patch files to use MacPorts conventions~~

Tests pass locally except for a few which fail because of `mktemp` CLI syntax.

See: https://trac.macports.org/ticket/47301
See: https://trac.macports.org/ticket/61160

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8
Xcode x.y / Command Line Tools x.y.z

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [x] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by ryandesign** [comment]
> * Fix a duplicate symbol error building on 10.6

Is there an upstream bug report or fix for this issue?

> * Remove unneeded `dprintf` patch (this function is now provided by legacysupport)

Good to know! Thanks.

> * Rename patch files to use MacPorts conventions

Please do not rename the patchfiles according to [outdated conventions](https://trac.macports.org/ticket/59695). I prefer the patchfiles named the way they were.

**Comment by evanmiller** [comment]
> > * Fix a duplicate symbol error building on 10.6
> 
> Is there an upstream bug report or fix for this issue?
> 

I've included the error message I'm seeing at the top of the patch. I will plan to report it upstream.

> > * Remove unneeded `dprintf` patch (this function is now provided by legacysupport)
> 
> Good to know! Thanks.
> 
> > * Rename patch files to use MacPorts conventions
> 
> Please do not rename the patchfiles according to [outdated conventions](https://trac.macports.org/ticket/59695). I prefer the patchfiles named the way they were.

OK

**Comment by evanmiller** [comment]
The duplicate symbol error was fixed here:

https://github.com/aircrack-ng/aircrack-ng/commit/f6f1396807607f5649d20631db517cfca3a1f5c4

**Comment by ryandesign** [comment]
Shall we use the complete upstream patch then?

Does it change the binary -- does it require a revbump?
