### PR TITLE
dovecot: update to 2.4.5

### PR DESCRIPTION
**Pull request by BjarneDMat**
#### Description

Preliminary work : 
- getting dovecot to 2.4.5
- DRYing the DBs

###### Tested on
```
Model Identifier: MacPro5,1     macOS 15.7.8 24G824 x86_64
Xcode 26.3 17C529               Command Line Tools 26.3.0.0.1.1771626560
```

### CODE REVIEW

**Comment by BjarneDMat** [comment]
💣 presently, it fails w/ a lot of stuff like this 👎 
```
make[3]: Entering directory `/opt/local/var/macports/build/dovecot-69f84174/work/dovecot-2.4.5/src/lib-dovecot-gssapi'
  CCLD     libdovecot-gssapi.la
ld: warning: alignment (2) of atom '_auth_gssapi_mech_krb5_oid_desc' (/opt/local/var/macports/build/dovecot-69f84174/work/dovecot-2.4.5/src/lib-auth/.libs/libauth-gssapi.a[2]
(auth-gssapi.o)) is too small and may result in unaligned pointers 
ld: warning: alignment (2) of atom '_auth_gssapi_mech_spnego_oid_desc' (/opt/local/var/macports/build/dovecot-69f84174/work/dovecot-2.4.5/src/lib-auth/.libs/libauth-gssapi.a[
2](auth-gssapi.o)) is too small and may result in unaligned pointers 
Undefined symbols for architecture x86_64:
  "_buffer_append", referenced from:
      _mech_gssapi_gs1_input in libsasl-gssapi.a[2](libsasl_gssapi_la-dsasl-client-mech-gssapi.o)
...
   "_uchar_empty_ptr", referenced from:
      _mech_gssapi_auth_initial in libsasl-gssapi.a[3](libsasl_gssapi_la-sasl-server-mech-gssapi.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [libdovecot-gssapi.la] Error 1
make[3]: Leaving directory `/opt/local/var/macports/build/dovecot-69f84174/work/dovecot-2.4.5/src/lib-dovecot-gssapi'

```

**Comment by BjarneDMat** [comment]
If I interpret the error message correctly, the problem is, that it tries to link w/ an incorrect *.dylib

How do I got about finding the cause of this 🤔🙏🏻❓

**Comment by BjarneDMat** [comment]
So, I tried 2.4.0..2.4.5 to see if any of them would build & install. They all fail to build in different ways, w/ 2.4.4 & 2.4.5 failing to build in the same way.

I took a look at the brew cask & "stole" the patches

**Comment by ryandesign** [comment]
> If I interpret the error message correctly, the problem is, that it tries to link w/ an incorrect *.dylib

Which dylib do you think it is trying to link with? Which dylib do you think it should be using instead?

**Comment by BjarneDMat** [comment]
> > If I interpret the error message correctly, the problem is, that it tries to link w/ an incorrect *.dylib
> 
> Which dylib do you think it is trying to link with? Which dylib do you think it should be using instead?

I don't know . I don't yet know enough about C/C++ programming to debug on my own.
I think I've seen this kind of problem when a port links to the xCode libs instead of the MP libs.

**Comment by BjarneDMat** [comment]
🤔 tried this : 
```
$=> git diff
diff --git a/mail/dovecot/Portfile b/mail/dovecot/Portfile
index 5b6f8add36b..c8a8e8a7814 100644
--- a/mail/dovecot/Portfile
+++ b/mail/dovecot/Portfile
@@ -102,7 +102,8 @@ if {${name} eq ${subport}} {
                     path:lib/libssl.dylib:openssl \
                     port:lz4 \
                     port:xz \
-                    port:zlib
+                    port:zlib \
+                    port:kerberos5
 
     set default_internal_user   _dovecot
     set default_login_user      _dovenull
@@ -123,7 +124,8 @@ if {${name} eq ${subport}} {
                     --with-gssapi=yes \
                     --without-lua
 
-    configure.cppflags  -I${prefix}/include/openssl
+    configure.cppflags  "-I${prefix}/include/openssl -I${prefix}/include"
+    configure.universal_ldflags "-L${prefix}/lib"
     configure.env-append \
                     PANDOC=false
 

```
😢 didn't solve the problem 👎

**Comment by danielluke** [comment]
IIRC there are problems with the dovecot build system (it works on linux(tm)). They've fixed some things over the 2.4.x releases and I can get 2.4.5 to build with `./configure --without-lua` on my 15.7.9 intel system. I haven't tested to see if it actually works, though.

**Comment by BjarneDMat** [comment]
I've been checking up on what might be going wrong.
My latest anaysis is, that `gssapi` is looking for the `libs` in the wrong place. The missing symbols are from all over the place. : 
```
$=> grep 'referenced from' dovecot_2.4.5_6_build.log 
  "_buffer_append", referenced from:
  "_buffer_append_c", referenced from:
  "_buffer_create_dynamic", referenced from:
  "_buffer_free", referenced from:
  "_buffer_get_modifiable_data", referenced from:
  "_buffer_set_used_size", referenced from:
  "_default_pool", referenced from:
  "_dsasl_client_mech_register", referenced from:
  "_e_debug", referenced from:
  "_e_error", referenced from:
  "_e_info", referenced from:
  "_env_put", referenced from:
  "_event_send_abort", referenced from:
  "_event_want_level", referenced from:
  "_i_panic", referenced from:
  "_i_unreached", referenced from:
  "_mem_equals_timing_safe", referenced from:
  "_p_strdup", referenced from:
  "_p_strndup", referenced from:
  "_pool_datastack_create", referenced from:
  "_sasl_server_mech_register", referenced from:
  "_sasl_server_mech_unregister", referenced from:
  "_sasl_server_request_failure", referenced from:
  "_sasl_server_request_get_extra_field", referenced from:
  "_sasl_server_request_internal_failure", referenced from:
  "_sasl_server_request_lookup_credentials", referenced from:
  "_sasl_server_request_output", referenced from:
  "_sasl_server_request_set_authid", referenced from:
  "_sasl_server_request_success", referenced from:
  "_str_c", referenced from:
  "_str_c_modifiable", referenced from:
  "_str_free", referenced from:
  "_str_sanitize", referenced from:
  "_t_str_new", referenced from:
  "_t_strndup", referenced from:
  "_t_strsplit_spaces", referenced from:
  "_uchar_empty_ptr", referenced from:
```
So, I think it's a problem w/ the `make.*` files, but presently, I don't know enough about `make` to be able to really debug the issue 👎
