### PR TITLE
iTerm2: Update to 3.2.5

### PR DESCRIPTION
**Pull request by markemer**
#### Description

* Update to 3.2.5
* Fix makefile so it builds with Xcode 10 on macOS 10.14

Closes: https://trac.macports.org/ticket/57197
Closes: https://trac.macports.org/ticket/57190

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.1 18B75
Xcode 10.1 10B61

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [X] checked your Portfile with `port lint`?
- [X] tried existing tests with `sudo port test`?
- [X] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by pmetzger** [comment]
CI failures seem real. See, for example: https://paste.macports.org/d343f305cade

**Comment by markemer** [comment]
They kinda do, but I don't have 10.13 and i386. And the errors aren't helpful...

**Comment by markemer** [comment]
What is this about:
```
error: could not create session: requestError(description: "unknown error while handling message: unableToInitializeCore(errors: [\"/Applications/Xcode-10.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain: error: failed to load toolchain: toolchain \\\'com.apple.dt.toolchain.XcodeDefault\\\' already registered from /Applications/Xcode-10.0.app/Contents/Developer/Toolchains/OSX10.13.xctoolchain\"])")
```
Ever see that before?

**Comment by kencu** [comment]
> I wonder why it builds on 10.14 but not 10.13.

This looks like it might be relevant:
```
error: use of undeclared identifier 'NSAppearanceNameDarkAqua'
```

**Comment by mojca** [comment]
Yes, I would definitely say it's
```
error: use of undeclared identifier 'NSAppearanceNameDarkAqua'; did you mean 'NSAppearanceNameAqua'?
```
which is something new for 10.14, without the developers taking care of supporting any older OS.

You should file a ticket with upstream (or in the worst case make it fail in `pre-fetch` on anything older than 10.14).

**Comment by markemer** [comment]
Whoops missed that. I'll see what's up - but yeah, upstream is getting kinda hostile to older versions - at least for building. Back to 10.12 is what's supported by binary, but it may need 10.14 for building. This is going to become a bigger and bigger problem going forward I think.

**Comment by kencu** [comment]
You could try to require the 10.14 SDK to build, but set the deployment target to the current OS. That should let 10.13 and 10.14 build it (with Xcode 10), and motivated 10.12'ers can install the 10.14 SDK perhaps.

Or you can download a binary instead.

**Comment by markemer** [comment]
I like the idea of changing the deployment target to the current OS. I’ll give that a go.

**Comment by pmetzger** [comment]
An alternative: we could build the old iTerm on old MacOS, and the new one on new MacOS. Conditionalizing the portfile would be straightforward.

**Comment by cjones051073** [comment]
@pmetzger Pinning older OSes to older releases of course is easy, but I think we should avoid this whenever possible. For one, it would mean those OSes would never get any feature improvements.

However, I also agree with @markemer that this discussion highlights a basic conflict with have in MacPorts in how we require to always build on the same OS as we deploy on. This is generally not how things work at large, with developers, or is really what Apple recommends. There it is common to require building on the latest OS, but to set the deployment target to an older OS. So, to be fair to the iTerm2 devs, their requirement to use the latest OS to build is not that uncommon or unreasonable. 

Fixing this in MacPorts though is far from obvious...

**Comment by pmetzger** [comment]
> Pinning older OSes to older releases of course is easy, but I think we should avoid this whenever possible. For one, it would mean those OSes would never get any feature improvements.

That's an unfortunate side effect, but it is also the most straightforward fix. I'll note that if you're on an old OS, you're probably not looking for cutting edge features anyway (and iTerm isn't exactly dramatically different than it was a few years ago.)

> this discussion highlights a basic conflict with have in MacPorts in how we require to always build on the same OS as we deploy on

Sure, but we're definitely going to fix that now or quickly.

**Comment by cjones051073** [comment]
> > Pinning older OSes to older releases of course is easy, but I think we should avoid this whenever possible. For one, it would mean those OSes would never get any feature improvements.
> 
> That's an unfortunate side effect, but it is also the most straightforward fix. I'll note that if you're on an old OS, you're probably not looking for cutting edge features anyway (and iTerm isn't exactly dramatically different than it was a few years ago.)

Yes, that is probably fair enough. If there is no other option, i agree its better than nothing.

> 
> > this discussion highlights a basic conflict with have in MacPorts in how we require to always build on the same OS as we deploy on
> 
> Sure, but we're definitely going to fix that now or quickly.

Guess you are missing a not somewhere above ;)

But yes, this is a complex issue and not one we will fix any time soon.

**Comment by kencu** [comment]
> > > Pinning older OSes to older releases of course is easy, but I think we should avoid this whenever possible. For one, it would mean those OSes would never get any feature improvements.
> > 
> > 
> > That's an unfortunate side effect, but it is also the most straightforward fix. I'll note that if you're on an old OS, you're probably not looking for cutting edge features anyway (and iTerm isn't exactly dramatically different than it was a few years ago.)
> 
> Yes, that is probably fair enough. If there is no other option, i agree its better than nothing.
> 
> > > this discussion highlights a basic conflict with have in MacPorts in how we require to always build on the same OS as we deploy on
> > 
> > 
> > Sure, but we're definitely going to fix that now or quickly.
> 
> Guess you are missing a not somewhere above ;)
> 
> But yes, this is a complex issue and not one we will fix any time soon.

Off topic for this PR I guess, but my experience with Mojave +universal was a good pointer to the remaining issues with using SDKs and deployment targets, I think.

For the most part, the cmake and autotools ports work correctly right now. portconfigure.tcl sets them up just fine to build against an SDK with a deployment target, I found.

There is an issue with the `use_configure no` ports. the various cxxflags etc are not presently set up correctly by portconfigure.tcl, and these need to be all done manually in each port (ugh). See <https://github.com/macports/macports-ports/blob/master/graphics/freeimage/Portfile> for an example.

Finally, I noticed `libtool` does not pass the `isysroot` during the link phase, but only passes the `syslibroot`. This seemed to cause libtool builds to fail to link properly against the SDK, but more investigation is needed to see what this is about (perhaps it's something easy).

**Comment by yan12125** [comment]
I didn't find an upstream ticket, so I filed one - https://gitlab.com/gnachman/iterm2/issues/7336

**Comment by ryandesign** [comment]
> I noticed `libtool` does not pass the `isysroot` during the link phase, but only passes the `syslibroot`.

As far as I know, that's how it's supposed to be. That's what MacPorts base has always set. `-isysroot` in C*FLAGS for use during compiling, `-syslibroot` in LDFLAGS for use during linking.

**Comment by ryandesign** [comment]
> The bigger issue I suspect will come when you try and take a binary built on one OS, and deploy it on an older one.

That's what `MACOSX_DEPLOYMENT_TARGET` is for. You set it to the oldest macOS version you want to be able to run on. MacPorts sets this to the build macOS version automatically.

> How will MacPorts handle the dependencies in this case, which might also have been built differently between the two OSes ? You cannot just take all the deps for the package in question from the newer OS, and transplant those on the older one as well, as that will like break many other ports.

This isn't applicable. Ports are built on the version of macOS that they will run on. The deployment target is set to that version already.

**Comment by kencu** [comment]
> As far as I know, that's how it's supposed to be. That's what MacPorts base has always set. `-isysroot` in C*FLAGS for use during compiling, `-syslibroot` in LDFLAGS for use during linking.

What you describe is how it supposed to work, but it's not what I seemed to see as 'boots on the ground'. There are a couple of refs about this that might give a clue:

The clang and gcc ld drivers on darwin will automatically send -syslibroot to the linker if the -isysroot is specified on the gcc or clang build line: <https://gcc.gnu.org/ml/gcc-patches/2005-06/msg00308.html>

and this bit of weirdness, that I think I ran into -- If the last syslibroot is set to "/" then all syslibroots are ignored! See <https://reviews.llvm.org/D4409> , down around here `3. If the last -syslibroot is "/", all of them are ignored entirely.`

So some of this weirdness may explain what I was witnessing, although I don't pretend to have it all elegantly sorted out.

**Comment by cjones051073** [comment]
> > The bigger issue I suspect will come when you try and take a binary built on one OS, and deploy it on an older one.
> 
> That's what `MACOSX_DEPLOYMENT_TARGET` is for. You set it to the oldest macOS version you want to be able to run on. MacPorts sets this to the build macOS version automatically.

I know this,

> > How will MacPorts handle the dependencies in this case, which might also have been built differently between the two OSes ? You cannot just take all the deps for the package in question from the newer OS, and transplant those on the older one as well, as that will like break many other ports.
> 
> This isn't applicable. Ports are built on the version of macOS that they will run on. The deployment target is set to that version already.

Yes, I know this is how things are currently done. You are missing my point, I was discussing the fact that how MacPorts does things does not really match how things are done in the wider world. There it is quite common to require building on the latest OSes, say 10.14, but to set MACOSX_DEPLOYMENT_TARGET to an *older* release, so the resulting binaries can be deployed on older OSes as well. If you go to the main iTerm2 site there a binary can be downloaded that works with 10.10+. It was built though in 10.14. The fact that MacPorts cannot do this and requires builds to be made on the same OSes as we deploy on is in some cases, such as iTerm2, an additional constraint that limits us in terms of what we can provide.

**Comment by kencu** [comment]
The solution to this should be to install the most recent macOS SDK on each system and build against that SDK with a deployment target set to the system we're building on. That actually does for the most part work, although we run into issues right now because our ld64 port has no tapi support (because Apple hasn't released the source).

**Comment by cjones051073** [comment]
Will the 10.14 SDK really work properly in an 10.10 system ?

**Comment by eborisch** [comment]
Well, for RHEL, FreeBSD, and Ubuntu (and likely others, but are were the ones I run into) packages are generated for each major release separately.

Now, if you are selling a product, or compiling your own code for release as a binary, yes, you'll typically build on/for the oldest platform you want to run on ... but for package management approaches out there, especially those that support building (opposed to download a binary) when necessary, building to the platform you are on is a rational (and frequent) choice, and lets you use the latest features available.

But this is getting off topic. I vote for adding a switch based on XCode version, and build the old release on older XCode.

**Comment by pmetzger** [comment]
>  I vote for adding a switch based on XCode version, and build the old release on older XCode.

Seconded. It's the most expedient solution for the moment.

**Comment by kencu** [comment]
> As far as I know, that's how it's supposed to be. That's what MacPorts base has always set. `-isysroot` in C*FLAGS for use during compiling, `-syslibroot` in LDFLAGS for use during linking.

I organized these observations into something readable here <https://trac.macports.org/ticket/57612>

**Comment by markemer** [comment]
So for this one, should just use a tag further back in iTerm based on the latest that will build on that Xcode/macOS?

**Comment by ryandesign** [comment]
> Yes, I know this is how things are currently done. You are missing my point, I was discussing the fact that how MacPorts does things does not really match how things are done in the wider world. There it is quite common to require building on the latest OSes, say 10.14, but to set MACOSX_DEPLOYMENT_TARGET to an _older_ release, so the resulting binaries can be deployed on older OSes as well. If you go to the main iTerm2 site there a binary can be downloaded that works with 10.10+. It was built though in 10.14. The fact that MacPorts cannot do this and requires builds to be made on the same OSes as we deploy on is in some cases, such as iTerm2, an additional constraint that limits us in terms of what we can provide.

I am aware of all of this, except that the requirement is not to build on a newer OS; the requirement is to build with the SDK of a newer OS. So the solution we are currently interested in exploring is providing a way of installing the newer SDKs on older OS versions. I am working on a MacOSX.sdk port to do that, and I also submitted a PR to base to make it easier to use that port, though the port and the PR are currently incomplete.

**Comment by pmetzger** [comment]
@markemer I couldn't parse that. But there should be a conditional in the Portfile that picks a version of iTerm based on the version of MacOS (or possibly on the version of the SDK), and the latest that will build should be selected.

**Comment by markemer** [comment]
Yeah. That’s what I meant. I’ll do that. Should we close this then?

**Comment by pmetzger** [comment]
@markemer Nah, you can just update this one to do what you want.

**Comment by eborisch** [comment]
See if https://github.com/macports/macports-ports/pull/3033 does what (the collective) you want.

**Comment by pmetzger** [comment]
@eborisch Looks pretty good to me. @markemer?

**Comment by markemer** [comment]
Yep. I think #3033 was exactly what I planned to do. Thanks!

**Comment by eborisch** [comment]
Resolved with https://github.com/macports/macports-ports/pull/3033.
