### PR TITLE
mesos: attempt to fix build on 10.11 and earlier

### PR DESCRIPTION
**Pull request by chrstphrchvz**
#### Description

Build failures were observed:
* [10.6](https://build.macports.org/builders/ports-10.6_x86_64-builder/builds/33701/steps/install-port/logs/stdio), [10.6 (i386)](https://build.macports.org/builders/ports-10.6_i386-builder/builds/17068/steps/install-port/logs/stdio): `error: use of undeclared identifier 'strnlen'`
* [10.7](https://build.macports.org/builders/ports-10.7_x86_64-builder/builds/29897/steps/install-port/logs/stdio), [10.9](https://build.macports.org/builders/ports-10.9_x86_64-builder/builds/126046/steps/install-port/logs/stdio): `error: no member named 'fdopendir' in the global namespace`
* [10.9](https://build.macports.org/builders/ports-10.9_x86_64-builder/builds/126046/steps/install-port/logs/stdio), [10.10](https://build.macports.org/builders/ports-10.10_x86_64-builder/builds/122514/steps/install-port/logs/stdio): `error: thread-local storage is not supported for the current target`

Two other failures I'm not aware how to best address:
* [10.8](https://build.macports.org/builders/ports-10.8_x86_64-builder/builds/24869/steps/install-port/logs/stdio): <tt>error: libtool: unknown option character &grave;n' in: -no_warning_for_no_symbols</tt>
* [10.11](https://build.macports.org/builders/ports-10.11_x86_64-builder/builds/120899/steps/install-port/logs/stdio):
```
checking C++ standard library for undefined behaviour with selected optimization level... yes
configure: error: Mesos cannot be built with optimizations against this version of libcxx (MESOS-5745).
                  Consider building without optimizations, or changing the used C++ standard library.
```

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?

### CODE REVIEW

**Comment by ryandesign** [comment]
> * [10.8](https://build.macports.org/builders/ports-10.8_x86_64-builder/builds/24869/steps/install-port/logs/stdio): error: libtool: unknown option character `n' in: -no_warning_for_no_symbols

If you can figure out how, please disable silent rules so that we can see what commands are being run when that error occurs.

**Comment by chrstphrchvz** [comment]
> * [10.8](https://build.macports.org/builders/ports-10.8_x86_64-builder/builds/24869/steps/install-port/logs/stdio): <tt>error: libtool: unknown option character `n' in: -no_warning_for_no_symbols</tt>

According to https://stackoverflow.com/a/37751847/4896937 this option is unrecognized prior to Xcode 7. The combination of `compiler.cxx_standard 2011` and `compiler.thread_local_storage yes` will avoid Xcode < 8, so this PR might effectively resolve this issue.

**Comment by chrstphrchvz** [comment]
> * [10.11](https://build.macports.org/builders/ports-10.11_x86_64-builder/builds/120899/steps/install-port/logs/stdio):
> 
> ```
> checking C++ standard library for undefined behaviour with selected optimization level... yes
> configure: error: Mesos cannot be built with optimizations against this version of libcxx (MESOS-5745).
>                   Consider building without optimizations, or changing the used C++ standard library.
> ```

Pinging @kencu in case they're aware whether a solution for this is available or in progress.

**Comment by kencu** [comment]
I guess it's a libc++ thing rather than a clang version thing, so perhaps just using a newer compiler won't fix it...

looks like upstream suggests setting the optflags to ```-O0```, which is easy enough in the portfile for the affected systems, it would seem.

**Comment by kencu** [comment]
see <https://issues.apache.org/jira/browse/MESOS-6606>

**Comment by kencu** [comment]
let's go with this and see how it works out. @chrstphrchvz -- thanks for your apparently boundless energy!
