### PR TITLE
asciidoctor: Revert to last fully working version of Ruby (2.6)

### PR DESCRIPTION
**Pull request by fhgwright**
Ruby3.0 doesn't build for 10.4, 10.5, 10.7, or 10.8.  Ruby2.7 also
fails for 10.4, 10.5, and 10.7.  The Ruby dependency shouldn't be changed
until the new Ruby version is fully compatible.

Also adds myself as a maintainer, mainly to keep these sorts of changes
from slipping through in the future.

TESTED:
Built and ran on macOS 10.4-10.5 ppc, 10.4-10.6 i386, and 10.6-10.15
x86_64.

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

Mac OS X 10.4.11 8S165, PPC, Xcode 2.5 8M2558
Mac OS X 10.4.11 8S2167, i386, Xcode 2.5 8M2558
Mac OS X 10.5.8 9L31a, PPC, Xcode 3.1.4 9M2809
Mac OS X 10.5.8 9L31a, i386, Xcode 3.1.4 9M2809
Mac OS X 10.5.8 9L31a, x86_64, Xcode 3.1.4 9M2809
Mac OS X 10.6.8 10K549, i386, Xcode 3.2.6 10M2518
Mac OS X 10.6.8 10K549, x86_64, Xcode 3.2.6 10M2518
Mac OS X 10.7.5 11G63, x86_64, Xcode 4.6.3 4H1503
OS X 10.8.5 12F2560, x86_64, Xcode 5.1.1 5B1008
OS X 10.9.5 13F1911, x86_64, Xcode 6.2 6C131e
OS X 10.10.5 14F2511, x86_64, Xcode 7.2 7C68
OS X 10.11.6 15G22010, x86_64, Xcode 8.1 8B62
macOS 10.12.6 16G2136, x86_64, Xcode 9.2 9C40b
macOS 10.13.6 17G14042, x86_64, Xcode 10.1 10B61
macOS 10.14.6 18G9323, x86_64, Xcode 11.3.1 11C505
macOS 10.15.7 19H2, x86_64, Xcode 12.4 12D4e

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [N/A] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [N/A] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by reneeotten** [comment]
according to upstream ruby 2.6.8 is "in security maintenance phase (will EOL soon!)" - so moving away from that is a good thing. According to the [buildbots](https://build.macports.org/builders/ports-10.8_x86_64-builder/builds/59498/steps/install-port/logs/stdio) `ruby30` fails on 10.8 due to 
```
random.c:485:18: warning: implicit declaration of function 'SecRandomCopyBytes' is invalid in C99 [-Wimplicit-function-declaration]
```

so instead of holding all (modern) systems back to an old version I would say it's preferable to fix that failure or, alternatively, restrict the use of `ruby26` to older systems only. I don't think that keeping everything at `ruby26` is the best solution here, but let's see what others think.

**Comment by fhgwright** [comment]
@reneeotten 
> according to upstream ruby 2.6.8 is "in security maintenance phase (will EOL soon!)" - so moving away from that is a good thing. According to the [buildbots](https://build.macports.org/builders/ports-10.8_x86_64-builder/builds/59498/steps/install-port/logs/stdio) `ruby30` fails on 10.8 due to
> 
> ```
> random.c:485:18: warning: implicit declaration of function 'SecRandomCopyBytes' is invalid in C99 [-Wimplicit-function-declaration]
> ```
> 
> so instead of holding all (modern) systems back to an old version I would say it's preferable to fix that failure or, alternatively, restrict the use of `ruby26` to older systems only. I don't think that keeping everything at `ruby26` is the best solution here, but let's see what others think.

The point is that it works with ruby26 now, and moving it to a newer version breaks that.  Until fairly recently it had used ruby24, and the move to ruby26 was motivated just to get native ARM support.  I just got through fixing ruby26 to unbreak asciidoctor, only to have the latter switch to a version broken on even more OS versions than ruby26.

It's likely that the issues with ruby27 are similar to ruby26, but it still takes time to sort that out, in addition to nay new issues in ruby30.  I've been holding off on updating gpsd because adding the missing dependency on asciidoctor will break it in the cases where asciidoctor is broken.

Asciidoctor's own documentation states that it works with Ruby versions 2.3-3.0.

Unfortunately, too many people seem to observe the motto "If it ain't broke, fix that."

**Comment by reneeotten** [comment]
@fhgwright I see your point and didn't realize you spend the time on fixing `ruby26` on legacy systems to get this port working again - so I'm sorry about that. 

I have personally no interest in this port - so no stake in merging the "offending" PR and don't really care either way. I guess that other viewpoint is that people would just prefer to stick to a recent Ruby version on current systems and avoid installing an almost EOL version that is not needed just for `asciidoctor`. 

So how about pinning the port to use `ruby26` on OSes that cannot build a newer Ruby version yet? That would supposedly make everyone happy ;) ?!

**Comment by fhgwright** [comment]
@reneeotten 
> So how about pinning the port to use `ruby26` on OSes that cannot build a newer Ruby version yet? That would supposedly make everyone happy ;) ?!

Actually, when I started out to fix this, my Plan B was going to be to switch back to `ruby24` on the older systems, but figured that fixing `ruby26` was worth a shot.  Last year I'd fixed `ruby22-25`, mainly so that `ruby24` would work for `asciidoctor`, but `ruby26-27` had nastier problems that I didn't want to chase at the time (and there was no `ruby30`).  But since `ruby26` proved tractable (albeit with considerable pain), there was no need for Plan B.

I'd be willing to so the "split version" thing if people insist, but note that the switch to `ruby30` only happened yesterday, so the majority of `asciidoctor` users already have `ruby26` from the old dependency, and the switch to `ruby30` probably causes more extra installs than the old way.  It's not that big a deal in any case, since none of the `ruby` ports are either terribly large or terribly slow to build.  Not like, say, an extra `gcc` version. :-) I'm unconvinced that the split version is worth the complication.

**Comment by reneeotten** [comment]
this issue seems to have disappeared now `ruby30` builds on [all systems](https://ports.macports.org/port/ruby30/details/), see 6f9214d6682931089858c6efd9fb7591471eab52
