### PR TITLE
mhxd: new port, Hotline client and server

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Let’s see if this quite an archaic software builds.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
@kencu Could you say if this is something fixable for newer OS or I should rather restrict it to old ones, like we did for archaic Haskell compilers?

**Comment by kencu** [comment]
```
2023-04-21T00:45:55.2235910Z if /usr/bin/clang -DHAVE_CONFIG_H -D_REENTRANT -D_GNU_SOURCE -I. -I. -I../.. -I. -I.. -I../.. -I../lib -I../conf -I../protocol     -I/opt/local/libexec/openssl11/include -isystem/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk  -pipe -I/opt/local/libexec/openssl11/include -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -arch x86_64 -Wall -Wall -W -MT decode.o -MD -MP -MF ".deps/decode.Tpo" \
2023-04-21T00:45:55.2252200Z 	  -c -o decode.o `test -f 'decode.c' || echo './'`decode.c; \
2023-04-21T00:45:55.2297170Z 	then mv -f ".deps/decode.Tpo" ".deps/decode.Po"; \
2023-04-21T00:45:55.2300760Z 	else rm -f ".deps/decode.Tpo"; exit 1; \
2023-04-21T00:45:55.2313930Z 	fi
2023-04-21T00:45:55.3018910Z In file included from decode.c:2:
2023-04-21T00:45:55.3028710Z ./hxd.h:364:15: error: expected parameter declarator
2023-04-21T00:45:55.3029390Z extern size_t strlcpy (char *dst, const char *src, size_t siz);
2023-04-21T00:45:55.3029930Z               ^
```

it looks like it is missing an include header, to start with. Newer MacOS versions error out on this. It might be a simple fix.

**Comment by barracuda156** [comment]
Added the header there, now it fails like this:
```
In file included from hlwrite.c:6:
./hxd.h:365:15: error: expected ')'
  
In file included from hlwrite.c:6:
./hxd.h:365:15: error: conflicting types for '__builtin___strlcpy_chk'
```

**Comment by barracuda156** [comment]
@evanmiller If you got a minute, could you try this on something you use (besides 10.6)?

**Comment by evanmiller** [comment]
Capitalize `CoreServices` in configure.in

Add to configure.in

```
    AC_CHECK_FUNC(strlcpy, AC_DEFINE(HAVE_STRLCPY, 1, [strlcpy]),
            aclo_strlcpy=yes;
            HXDLIBLDADD="$HXDLIBLDADD ../lib/strlcpy.o")
    if test "x$aclo_strlcpy" = "xyes"; then
        AC_LIBOBJ([strlcpy])
    fi
```

Modify Portfile to use ./autogen.sh and modify autogen.sh to use MacPorts libtoolize

Add to src/hxd/htxf.c

```
#if defined(HAVE_CORESERVICES)
#include "apple/alias.h"
#include "apple/files.h"
#endif
```

Then it builds on 13.3

**Comment by barracuda156** [comment]
> Capitalize `CoreServices` in configure.in
> 
> Add to configure.in
> 
> ```
>     AC_CHECK_FUNC(strlcpy, AC_DEFINE(HAVE_STRLCPY, 1, [strlcpy]),
>             aclo_strlcpy=yes;
>             HXDLIBLDADD="$HXDLIBLDADD ../lib/strlcpy.o")
>     if test "x$aclo_strlcpy" = "xyes"; then
>         AC_LIBOBJ([strlcpy])
>     fi
> ```
> 
> Modify Portfile to use ./autogen.sh and modify autogen.sh to use MacPorts libtoolize
> 
> Add to src/hxd/htxf.c
> 
> ```
> #if defined(HAVE_CORESERVICES)
> #include "apple/alias.h"
> #include "apple/files.h"
> #endif
> ```
> 
> Then it builds on 13.3

@evanmiller Wow, thank you very much! I tried autotools initially, it did not work. Now I see what I missed there.

**Comment by barracuda156** [comment]
Gonna deal with this one tonight.

**Comment by barracuda156** [comment]
@evanmiller Still fails for me (from the look of things same/similar errors, like earlier):
https://github.com/macports/macports-ports/actions/runs/4789193014/jobs/8516759255?pr=18361

Did I miss something or made a mistake? https://github.com/macports/macports-ports/pull/18361/files#diff-1a6dfb073a73c385c718024137f605e6c0dc57dbd92c7cadfb7806441fee24a2

**Comment by barracuda156** [comment]
@kencu Could you take another look, when you have a bit of time, please? Apparently `ppc` and `aarch64` work, while `x86` remains broken.

**Comment by barracuda156** [comment]
I think I have found a reason: headers which define __attribute__ for non-GNU compilers to nothing were included above headers pulling Intel intrinsics, but the latter need __attribute__ to work.

**Comment by barracuda156** [comment]
@mascguy Could you take a look please? I have finally fixed the build for Intel.

**Comment by mascguy** [comment]
> @mascguy Could you take a look please? I have finally fixed the build for Intel.

I need to test locally with trace mode, and verify various things. (So not a quick thing.)

Will look at it later today, if possible.

**Comment by barracuda156** [comment]
@mascguy Awesome, thanks!

I tried to build a couple of other Hotline clients, but most of those are hopelessly broken – the code is archaic. This one worked, save for GUI – may be fixable too, but did not work so far.

File: net/mhxd/Portfile [hunk 1]
```diff
@@ -0,0 +1,86 @@
...
+    ln -sf ${rundir}/hxd/bin/hxd ${destroot}${prefix}/sbin/hxd
+    copy ${srcdir}/hx/hx ${destroot}${prefix}/bin
+    copy ${worksrcpath}/doc/hxd ${destroot}${prefix}/share/doc
+    xinstall -m 0644 -W ${worksrcpath} AUTHORS COPYING INSTALL NEWS PROBLEMS README ${destroot}${prefix}/share/doc/hxd
+    xinstall -d ${destroot}${prefix}/var/run/hxd
+}
+
+startupitem.create      yes
+startupitem.executable  ${prefix}/sbin/hxd
+startupitem.pidfile     ${prefix}/var/run/hxd/hxd.pid
```
Comment (mascguy) [inline net/mhxd/Portfile:84]: During destroot, the following error occurs:

```
Error: --->  Unknown pidfile style /opt/local/var/run/hxd/hxd.pid presented to startupitem.pidfile
```

That's because `startupitem.pidfile` requires two parameters, but you're only passing one:

https://guide.macports.org/#reference.startupitems

Apparently this doesn't cause the build to fail, which is why CI still succeeded. But if you test locally, you should certainly see the issue.

Comment (barracuda156) [reply net/mhxd/Portfile:84]: Thank you! I will fix it now.

Comment (barracuda156) [reply net/mhxd/Portfile]: @mascguy I read the page, and turned out we do not need `pidfile` with `startup.executable` at all. Just dropped it.

File: net/mhxd/Portfile [hunk 2]
```diff
@@ -0,0 +1,85 @@
...
+    copy ${srcdir}/hx/hx ${destroot}${prefix}/bin
+    copy ${worksrcpath}/doc/hxd ${destroot}${prefix}/share/doc
+    xinstall -m 0644 -W ${worksrcpath} AUTHORS COPYING INSTALL NEWS PROBLEMS README ${destroot}${prefix}/share/doc/hxd
+    xinstall -d ${destroot}${prefix}/var/run/hxd
+}
+
+startupitem.create      yes
+startupitem.executable  ${prefix}/sbin/hxd
+
+destroot.keepdirs       ${destroot}${prefix}/var/run/hxd
```
Comment (mascguy) [inline net/mhxd/Portfile:85]: I think this was only need when the pidfile was being used. Probably not anymore though, right?

Comment (barracuda156) [reply net/mhxd/Portfile:85]: Yeah, should be. Will remove that too now.

Comment (barracuda156) [reply net/mhxd/Portfile:85]: Done

Comment (mascguy) [reply net/mhxd/Portfile:85]: The line still seems to be there, even after multiple browser refreshes.

Comment (barracuda156) [reply net/mhxd/Portfile:85]: Sorry, maybe something went wrong with rebasing. I will fix it now again.

Comment (barracuda156) [reply net/mhxd/Portfile]: Fixed. My mistake, rebase didn’t go through correctly.

**Review by mascguy — APPROVED** [review]
