### PR TITLE
jython: minor improvements

### PR DESCRIPTION
**Pull request by chrstphrchvz**
Repair checksums for `-installer`

Relax Java version requirement following 2.7.2 update

Use HTTPS URLs

###### Tested on

macOS 10.15.6
OpenJDK 11.0.8

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
Only for `jython -installer`
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

File: lang/jython/Portfile [hunk 1]
```diff
@@ -67,13 +64,15 @@ if {![variant_isset installer]} {
...
+                    sha256  4938cc7079f48fa64e7558682b9bf9a62ebee16bbce698570007667945d08f60 \
+                    size    46106571
+    # Remove during next update
+    dist_subdir   ${name}/${version}_1
 
-    # Use Ant 1.10.x for Java 8 compatibility
+    # Use Ant 1.9.x for Java 7 compatibility
     depends_build-append \
-                    port:apache-ant
+                    port:apache-ant-1.9
```
Comment (chrstphrchvz) [inline lang/jython/Portfile:75]: To ensure `jython -installer` builds with Java 7, Ant 1.9.x is needed. But I wonder if this would be somewhat annoying for those who normally build with Java ≥ 8 and Ant 1.10.x, as the the `apache-ant` and `apache-ant-1.9` ports cannot be installed simultaneously. One alternative is to drop Java 7 support (set `java.version 1.8+` and only need to use Ant 1.10.x). Another would be to drop the `-installer` variant entirely (even though some users have objected to MacPorts offering ports which can't be built from source).

File: lang/jython/Portfile [hunk 2]
```diff
@@ -18,13 +18,10 @@ long_description    \
...
 
-homepage            http://www.jython.org/
+homepage            https://www.jython.org/
 
-# Jython 2.7.1 is only compatible with Java 7/8, and is known to be
-# incompatible with Java 9+ (this will likely be resolved by Jython 2.7.2).
-# Since the Java portgroup doesn't support specifying a maximum Java version
-# but supports specifying an exact version, only use Java 8 for now.
-java.version        1.8
+java.version        1.7+
```
Comment (amake) [inline lang/jython/Portfile:23]: I had the following issue with this change to an "or later" version specification:

- I have openjdk8 and openjdk13 installed
- When installing jython with `-installer`, the `1.7+` version spec resolved to openjdk13
- Jython was thus compiled with openjdk13
- However my `JAVA_HOME` is generally set to Java 1.8; when launching Jython I get this error:

    ```
    Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
        at org.python.core.io.BufferedReader.clear(BufferedReader.java:147)
        at org.python.core.io.BufferedReader.<init>(BufferedReader.java:27)
        at org.python.core.PyFile.createBuffer(PyFile.java:227)
        at org.python.core.PyFile.file___init__(PyFile.java:185)
        at org.python.core.PyFile.file___init__(PyFile.java:178)
        at org.python.core.PyFile.<init>(PyFile.java:101)
        at org.python.core.PySystemState.<init>(PySystemState.java:236)
        at org.python.core.PySystemState.doInitialize(PySystemState.java:1222)
        at org.python.core.PySystemState.initialize(PySystemState.java:1130)
        at org.python.core.PySystemState.initialize(PySystemState.java:1085)
        at org.python.core.PySystemState.initialize(PySystemState.java:1080)
        at org.python.core.PySystemState.initialize(PySystemState.java:1075)
        at org.python.util.jython.main(jython.java:533)
    ```

The cause is this: https://jira.mongodb.org/browse/JAVA-2559

The best solution to me seems to be to require precisely Java 1.8, as the result can then be executed by any version.

This solves the Apache Ant issue as well (I do think that the world has moved past Java 7 and Ant 1.9, and we shouldn't bother supporting building with these).

**Comment by chrstphrchvz** [comment]
Forced `-installer` to use JDK 8 and Ant 1.10.x in bfd5266106d as suggested.

**Comment by amake** [comment]
Thanks!
