### PR TITLE
libqalculate: fix build on macOS 10.8-10.11

### PR DESCRIPTION
**Pull request by chrstphrchvz**
#### Description
Build failure observed on [macOS 10.8-10.11](https://ports.macports.org/port/libqalculate/builds):
```
MathStructure-integrate.cc:6580:11: error: variable length array of non-POD element type 'Number'
        Number R1[max_steps], R2[max_steps];
                 ^
MathStructure-integrate.cc:6581:30: error: use of undeclared identifier 'R2'
        Number *Rp = &R1[0], *Rc = &R2[0];
                                    ^
```

Since the port builds on 10.6-10.7, which use MacPorts' clang 9.0, avoiding older Xcode versions on 10.8-10.11 should allow the port to build on those OS versions as well.

###### Tested on

Untested. See if Travis CI Xcode 7.3 and 8.3 builds succeed.

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by jjstickel** [comment]
OK by me if it tests OK.
