### PR TITLE
mc: Workaround on missing 'utimensat' on 10.13

### PR DESCRIPTION
**Pull request by vovinacci**
###### Description
mc: Workaround on missing 'utimensat' on 10.13
closes: https://trac.macports.org/ticket/54774

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.13 17A365
Xcode 9.0 9A235

###### Verification 
Have you
- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by lbschenkel** [comment]
Are you sure that you didn't reverse the logic? `utimenstat` *is* present in 10.13, but not present in any earlier version. However, autotools gets confused by Xcode 9 on macOS <= 10.12 since it includes a 10.13 SDK (which claims the function exist), but the runtime libraries for macOS do not have the function.

**Comment by vovinacci** [comment]
@lbschenkel This fixed the build for me on 10.13 as with default settings build was failing
```
:info:build file.c:668:23: error: no member named 'st_atim' in 'struct stat'
:info:build     (*times)[0] = sb->st_atim;
:info:build                   ~~  ^
:info:build file.c:669:23: error: no member named 'st_mtim' in 'struct stat'
:info:build     (*times)[1] = sb->st_mtim;
:info:build                   ~~  ^
```
I'm not that deep into macOS, so cannot discuss what is there and what is not and I'm sorry for that, but this fixed the issue on 10.13 and that's why I'm submitting PR.

**Comment by lbschenkel** [comment]
Maybe I don't fully understand the issue affecting this specific port; I just commented because other ports were similarly affected but the solution was the opposite of the one being implemented here.

**Comment by raimue** [comment]
Upstream: https://github.com/MidnightCommander/mc/pull/130

**Comment by zyv** [comment]
@lbschenkel the solution is correct, please see our upstream discussion.

**Comment by lbschenkel** [comment]
Yep... sorry for the false alarm. I would like to clarify that I was not actually reviewing this PR, and I am not a committer, so it's not up to me to merge this.

**Comment by kencu** [comment]
confirmed that this workaround fixes the build on 10.13.
```
$ port -v installed mc
The following ports are currently installed:
  mc @4.8.19_0+slang2 (active) platform='darwin 17' archs='x86_64' date='2017-10-16T21:58:12-0700'```
mc builds and runs with this patch. This is the same fix used on homebrew. If an upstream fix is developed that preserves the utimenstat functionality on 10.13 then we can revbump this, but for all the users waiting three weeks now, I think it's fair that this can reasonably be committed as is for now.
