### PR TITLE
gnuradio: update gnuradio to 3.10 with all OOT

### PR DESCRIPTION
**Pull request by ra1nb0w**
#### Description
This PR updates gnuradio to 3.10 and all OOT modules

- gr-baz: obsolete
- gr-fcdproplus: obsolete
- gr-gsm: obsolete
- gr-iio: obsolete
- gr-specest: obsolete

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on
macOS 10.14.6 18G9323 x86_64
Xcode 10.3 10G8

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by ra1nb0w** [comment]
maybe we can move to python 3.10

**Comment by michaelld** [comment]
Volk is moved to Py310 by default. Will move uhd and libiio too

**Comment by ra1nb0w** [comment]
thank you

**Comment by mascguy** [comment]
Rebased against master. Also, is this PR ready for merge?

**Comment by mascguy** [comment]
Also, it looks like you're also adding a new (unrelated) port, `mathjax2`. While it looks fine to me, did you intend to include it in this PR?

I'm fine with it though. @michaelld ?

**Review by mascguy — APPROVED** [review]
LGTM, but would like @michaelld to approve before merge.

EDIT: David is a co-maintainer, so Never Mind. Lol

**Comment by mascguy** [comment]
> LGTM, but would like @michaelld to approve before merge.

Actually David is a co-maintainer, so Never Mind. Lol

**Comment by mascguy** [comment]
FYI, at least one of the `gr-*` ports is failing to build locally for me. Can't remember which one at the moment, but is that expected?

**Comment by ra1nb0w** [comment]
which architecture and macOS version? because on my macOS 10.14 x86_64 every port should build fine.

**Comment by mascguy** [comment]
> which architecture and macOS version? because on my macOS 10.14 x86_64 every port should build fine.

I'm building on 10.15 x86_64.

**Comment by ra1nb0w** [comment]
Unfortunately, I don't have any macOS > 10.14 so I can't test. If you remember the port feel free to report otherwise we will see after CI.

**Comment by mascguy** [comment]
Rebased against master

**Comment by mascguy** [comment]
Port `gt-osmosdr` fails with the following error:

```
:info:build /opt/local/var/macports/build/_opt_macports_sources_ports_enabled_science_gr-osmosdr/gr-osmosdr/work/gr-osmosdr-a100eb024c0210b95e4738b6efd836d48225bd03/lib/hackrf/hackrf_sink_c.cc:302:9: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
:info:build   const register __m128 mulme = _mm_set_ps( 127.0f, 127.0f, 127.0f, 127.0f );
:info:build         ^~~~~~~~~
```

**Comment by ra1nb0w** [comment]
Very strange. They were working fine on macOS 10.14 when I created this PR maybe later version are more strict (like with `gr-osmosdr`).
About `replaced_by`: probably we can remove that and just make it obsolete. Michael?

**Comment by mascguy** [comment]
> > Very strange. They were working fine on macOS 10.14 when I created this PR maybe later version are more strict (like with `gr-osmosdr`). About `replaced_by`: probably we can remove that and just make it obsolete. Michael?
> 
> Why would you ever make the parent ports obsolete?
> 
> Look at what we do for primaries throughout MacPorts: Python ports... Perl5 ports... etc. The parents are stubs, and depend on the most recent - or preferred - subport.
> 
> That's how this should be done, rather than how it is currently.
> 
> Does that make sense David?

To be clear, I'm not trying to be critical here - hindsight is 20/20, after all - but rather, this is an opportunity for improvement.

**Comment by ra1nb0w** [comment]
Sorry for the long delay but I am not using too much macOS these days.
@mascguy don't worry, any comment is appreciated.

- `gr-ofdm`: is only available as gr37-ofdm therefore requires  python 2.7 only
- `gr-osmosdr`: should be fixed reading the commits
- `gr-ieee802-11`: fixed; probably a forced commit by the author
- gr-* and gr37-* issue: probably we can drop gnuradio 3.7 completely and make all related ports `obsolete` since the user base should be zero nowadays. What do you think @michaelld ?

**Comment by reneeotten** [comment]
is there any point in keeping this PR in the queue given that it hasn't received om more than half a year; also by now it should be using Python 3.11 ;) If anyone intends to work on this for real by all means keep it open;  but if not let's start cleaning up the queue...

**Comment by ra1nb0w** [comment]
@reneeotten unfortunately, I don't have the time to update this PR (also because I am using macos rarely nowadays)
