### PR TITLE
libbiosig: fix build on < 10.7

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Fix for old systems

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
On Sonoma:
```
  /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_libbiosig/libbiosig/work/biosig4c++-1.8.6/t210/sopen_heka_read.c:54:7: error: call to undeclared library function 'finite' with type 'int (double)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
     54 |         if (!fi/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_libbiosig/libbiosig/work/biosig4c++-1.8.6/t210/sopen_heka_read.c:54:7: error: nite(x)) {
        |              ^
  /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_libbiosig/libbiosig/work/biosig4c++-1.8.6/t210/sopen_heka_read.c:54:7: error: call to undeclared library function 'finite' with type 'int (double)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
     54/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_libbiosig/libbiosig/work/biosig4c++-1.8.6/t210/sopen_heka_read.c:54:7: note: include the header <math.h> or explicitly provide a declaration for 'finite'
   |         if (!finite(x)) {
        |              ^
  /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_libbiosig/libbiosig/work/biosig4c++-1.8.6/t210/sopen_heka_read.c:54:7: note: include the header <math.h> or explicitly provide a declaration for 'finite'
  call to undeclared library function 'finite' with type 'int (double)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
     54 |         if (!finite(x)) {
        |              ^
  /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_libbiosig/libbiosig/work/biosig4c++-1.8.6/t210/sopen_heka_read.c:54:7: note: include the header <math.h> or explicitly provide a declaration for 'finite'
  11 error generated error.
   generated.
  1 error generated.
```

**Comment by reneeotten** [comment]
can you please fix that issue at the same time 😉?
