### PR TITLE
cppcheck: fix build on macOS <10.12

### PR DESCRIPTION
**Pull request by aeiouaeiouaeiouaeiouaeiouaeiou**
#### Description

https://build.macports.org/builders/ports-10.11_x86_64-builder/builds/270063/steps/install-port/logs/stdio
Doesn't happen on other buildbots that use the newer Clang.

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 10K549 x86_64
Xcode 3.2.6 10M2518

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

File: devel/cppcheck/Portfile [hunk 1]
```diff
@@ -45,6 +46,9 @@ post-patch {
 
 compiler.cxx_standard       2011
 compiler.thread_local_storage yes
+# build/valueflow.cpp:10973:124: error: call
+# to deleted function 'toString' on macOS <10.12
+compiler.blacklist-append   {*gcc-[3-4].*} {clang < 900}
```
Comment (barracuda156) [inline devel/cppcheck/Portfile:51]: Not that it hurts, but blacklisting pre-C++11 gccs is redundant. They are already excluded by two options specified above.
