### PR TITLE
ghc: update to 9.6.3

### PR DESCRIPTION
**Pull request by dylanarmstrong**
#### Description

Update GHC to 9.6.3.

I noticed some style bugs with linting, but they seem to be pre-existing false positives.

###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 14.0 23A344 x86_64
Xcode 15.0 15A240d

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by dylanarmstrong** [comment]
As a note, the documentation fails to build for me as the upstream changes to sphinx_rtd_theme did not make it into this release.

https://gitlab.haskell.org/ghc/ghc/-/issues/23444

**Comment by breiter** [comment]
> As a note, the documentation fails to build for me as the upstream changes to sphinx_rtd_theme did not make it into this release.

The documentation also fails o build for ghc@9.6.2 which prevents the current version of the port from installing.

**Comment by pmetzger** [comment]
@dylanarmstrong I think you should patch the theme as you suggest. It would have the effect you want.

**Comment by breiter** [comment]
FWIW, in order to install the current GHC, used pip to install sphinx 6 on top of the sphinx 7 port.

**Comment by dylanarmstrong** [comment]
> @dylanarmstrong ?

Thanks, yeah that's what I'll do. I haven't had time to work on this, but will try and get to it in the next few days.

**Comment by reneeotten** [comment]
@i0ntempest committed an update to this port in 2ad6423fad75eae938aa430962eee2b598e05626 and didn't follow the usual pathway of opening a PR for ports that have a maintainer. 

So this is now conflicting; it seems to me from looking through the comments here that additional changes besides a version update are needed for it to work properly...

**Comment by dylanarmstrong** [comment]
Huh, that’s not what I was expecting to see.

**Comment by i0ntempest** [comment]
Sorry I jumped the gun, I forgot I had the old sphinx installed which is why I believed it’s fine to push it. I’ll back port the theme later (if no one beats me to it).

**Comment by essandess** [comment]
This latest commit apparently fails to address the issue: https://github.com/macports/macports-ports/commit/99d3a312a2d08a212782999e0db71afa79e350ad#diff-c7968cfa7dd4491c4f36b05d17922247eee14b20e9a0abd8e2a05879af62c173

I recommend either rolling back to the latest version of `ghc` that builds and waiting for upstream to address this issue, or commenting out the `Portfile` commands that build the documentation.

**Comment by essandess** [comment]
@reneeotten Many ports depend upon a working `ghc`. I tentatively recommend a rollback of previous commits to `9.6.2` or `9.6.1`. Unfortunately, I do not have the cycles to track this down and make sure that a rollback will still compile.

@i0ntempest Please follow the standard workflow for merging commits unless you’re very, very certain things will work. I’m not aware of any pressing issue that demands we update to `9.6.3` while it is known to be broken upstream. If so, we can simply temporarily suppress documentation builds, but please explain the rational for these commits before merging them.

**Comment by breiter** [comment]
I don't think the port can be rolled back to a working state. The problem is that py37-sphinx was updated to an incompatible version. GHC documentation will not build unless the sphinx version is 6.2.1 or earlier.

**Comment by kencu** [comment]
the latest commit worked fine to fix the ghc build on almost every system, according to the buildbot.

https://build.macports.org/builders/ports-13_x86_64-watcher/builds/12798

**Comment by i0ntempest** [comment]
ghc now builds on 10.13 to 13 according to the buildbots, I don't know if previous versions worked on anything below that but they probably wouldn't given this is a minor update. What I do know is it won't build on 14 because ghc treats all build warnings as errors.

**Comment by kencu** [comment]
Nope, it builds fine on Sonoma arm64

% port -v installed ghc
The following ports are currently installed:
  ghc @9.6.3_0 (active) requested_variants='' platform='darwin 23' archs='arm64' date='2023-10-17T00:20:04-0700'

no issues with warnings as error

**Comment by i0ntempest** [comment]
@kencu I'm on Sonoma arm64 as well and I'm getting this:
```
:info:build In file included from rts/ExecPage.c:8:0: error: 
:info:build In file included from rts/include/Rts.h:38:0: error: 
:info:build In file included from rts/include/Stg.h:414:0: error: 
:info:build rts/include/stg/SMP.h:593:38: error:
:info:build      warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
:info:build     |
:info:build 593 | EXTERN_INLINE void write_barrier     () {} /* nothing */
:info:build     |                                      ^
:info:build EXTERN_INLINE void write_barrier     () {} /* nothing */
:info:build                                      ^
:info:build                                       void
:info:build rts/include/stg/SMP.h:594:38: error:
:info:build      warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
:info:build     |
:info:build 594 | EXTERN_INLINE void store_load_barrier() {} /* nothing */
:info:build     |                                      ^
:info:build EXTERN_INLINE void store_load_barrier() {} /* nothing */
:info:build                                      ^
:info:build                                       void
:info:build rts/include/stg/SMP.h:595:38: error:
:info:build      warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
:info:build     |
:info:build 595 | EXTERN_INLINE void load_load_barrier () {} /* nothing */
:info:build     |                                      ^
:info:build EXTERN_INLINE void load_load_barrier () {} /* nothing */
:info:build                                      ^
:info:build                                       void
:info:build 3 warnings generated.
```
Guess I'll open a ticket.
