### PR TITLE
glib2, gobject-instrospection, glibmm, pango, gtk4, py-gobject3: update to latest versions

### PR DESCRIPTION
**Pull request by reneeotten**
#### Description
The `-devel` ports for these packages have been updated earlier and all seem to build fine. This PR updates the "main" ports to the latest upstream versions.

###### Tested on
macOS 26.4.1 25E253 x86_64
Xcode 26.0.1 17A400

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by reneeotten** [comment]
the CI failures are for only `py36-gobject3` and due to the fact that Python 3.6 does not build on newer macOS versions; this should thus be ignored.

**Comment by barracuda156** [comment]
@reneeotten Do we know if any dependents need rebuild after this? (I hope revbumps are avoidable, just asking.)

**Comment by barracuda156** [comment]
@reneeotten This patch is needed for `gtk4`: https://github.com/macos-powerpc/powerpc-ports/blob/8979c4100146767e5b85ce0e43effe6c8fac055b/gnome/gtk4/files/patch-fix-meson.build

**Comment by reneeotten** [comment]
`pango` is failing on 10.11 - 10.8, with:
```
utils/viewer-cocoa.m
../pango-1.57.1/utils/viewer-cocoa.m:140:19: error: use of undeclared identifier 'NSWindowStyleMaskTitled'
                                                 styleMask:(NSWindowStyleMaskTitled |
                                                            ^
../pango-1.57.1/utils/viewer-cocoa.m:141:18: error: use of undeclared identifier 'NSWindowStyleMaskClosable'
                                                           NSWindowStyleMaskClosable)
                                                           ^
../pango-1.57.1/utils/viewer-cocoa.m:189:49: error: use of undeclared identifier 'NSEventMaskAny'
    NSEvent *event = [app nextEventMatchingMask:NSEventMaskAny
                                                ^
../pango-1.57.1/utils/viewer-cocoa.m:195:27: error: use of undeclared identifier 'NSEventTypeKeyDown'; did you mean 'NSEventTypeGesture'?
      if ([event type] == NSEventTypeKeyDown)
                          ^~~~~~~~~~~~~~~~~~
                          NSEventTypeGesture
/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:47:5: note: 'NSEventTypeGesture' declared here
    NSEventTypeGesture NS_ENUM_AVAILABLE_MAC(10_5)       = 29,
    ^
4 errors generated.
```

indeed it seems these variables are only present in the 10.12 SDK or above. I'll try to add a patch to solve that and use the "old" names and see if that works. It looks like these are the corresponding ones (not sure yet about `NSEventTypeKeyDown`):
```
older SDKs					> 10.12
NSTitledWindowMask			NSWindowStyleMaskTitled
NSClosableWindowMask        NSWindowStyleMaskClosable
NSAnyEventMask 				NSEventMaskAny
```

However, what I don't understand is why it seems to build on 10.7 and below... anyone?

**Comment by barracuda156** [comment]
@reneeotten Probably it disables Cocoa part altogether on earlier systems? I never needed it, so I was not aware it even exists :) 
If it is more or less trivial, it will be easily fixable, though I’m not sure it is useful. GTK requires much later macOS version, and while their requirement is completely unjustified for X11, the code likely uses late Cocoa features. And if GTK is not using quartz, arguably little utility in having it in pango.

Besides, you have fixed py-gobject, the latest Komikku now builds and works. I could finally drop a huge patch used to hack around gtk/adw API incompatibility.

**Comment by reneeotten** [comment]
@barracuda156 it looks like the build path if different depending on whether `CoreText` is true or false, from the configure part:
```
Checking if "CoreText availability" with dependency appleframeworks links: YES 
```

so I guess, figuring out where that comes from and/or if it can be disabled would be good... ~I have no time to look at that right now, so if anyone else has more insights in this ; help is welcome ;)~ I think I figured it out; let me test a bit and then I'll commit if if everything looks fine.

**Comment by barracuda156** [comment]
@reneeotten See how Cairo does that: it check for specific symbol, not just framework. So while CoreText is available in 10.6, Cairo disables quartz font codepath.

**Comment by brunvonlope** [comment]
gobject-introspection is now appending /opt/local/lib to all .dylib listed on `shared-libs` key inside .gir files, even if the said .gir files were generated to a custom prefix (I don’t mean a custom MacPorts installation but a project that e.g. -Dprefix=/my_prefix on meson

That is on MacPorts only, homebrew gobject-introspection is not appending the prefix so working as expected

**Comment by reneeotten** [comment]
> gobject-introspection is now appending /opt/local/lib to all .dylib listed on `shared-libs` key inside .gir files, even if the said .gir files were generated to a custom prefix (I don’t mean a custom MacPorts installation but a project that e.g. -Dprefix=/my_prefix on meson

Not sure if that's a use-case we are actively supporting. I think the assumption is currently that files will be installed in the MacPorts' prefix. What is wrong with that approach as in, what is the use-case where one would set `-Dprefix` to something else than the MacPorts' prefix (and is that useful/necessary to do). I haven't looked (carefully) at where this is happening and whether or not we could easily change something without breaking (other) stuff...
