### PR TITLE
htop: needs legacysupport

### PR DESCRIPTION
**Pull request by kencu**
Compat.c:40:17: error: use of undeclared identifier 'AT_FDCWD'
   if (dirfd != AT_FDCWD || mode != F_OK) {

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8
Xcode 4.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by neverpanic** [comment]
@kencu I'm sorry, needs legacysupport on which OSes exactly? It worked fine on 10.14, and that's already quite old.

**Comment by kencu** [comment]
It failed on <10.12, with the issue I put in the commit message. See: https://ports.macports.org/port/htop/builds

With legacysupport, it's fine back to 10.6 at least.

I know you don't any older systems, and have no interest in them, so you can't test anyway. As it was a minor thing only adding legacysupport, when the ci system cleared it, I moved it along rather than adding to the hundreds of PRs already sitting around in the queue now.

If you want to vet such minor tweaks on all your ports in future, I can leave them sit lomger. Just trying to avoid tickets and hassles as I move through updating my own ports.

**Comment by neverpanic** [comment]
No it's fine if you make such changes, I would just have preferred some information on which systems this affects in the commit message, but it's documented in this PR now, so that's fine.
