### PR TITLE
audacity : update to 2.2.0

### PR DESCRIPTION
**Pull request by RJVB**
This updates port:audacity to 2.2.0 and fixes Trac issues like [#55115](https://trac.macports.org/ticket/55115) and [#53438](https://trac.macports.org/ticket/53438) .

In addition, a variant allows building Audacity against wxWidgets 3.2 .

### CODE REVIEW

File: audio/audacity/Portfile [hunk 1]
```diff
@@ -63,10 +64,29 @@ homepage            http://www.audacityteam.org/
 
 compiler.blacklist  {*gcc-[234].[0-8]}
 
-wxWidgets.use       wxWidgets-3.0
+if {[variant_exists wx32] && [variant_isset wx32]} {
+    wxWidgets.use   wxWidgets-3.2
+    # we want to use the wxWidgets-3.2 "bleeding edge" port!
+    wxWidgets.port  wxWidgets-3.2
```
Comment (mojca) [inline audio/audacity/Portfile]: Doesn't it work for you without setting `wxWidgets.port` explicitly? I fixed a bug a while ago and would like to know in case I didn't fix the problem in a proper way.

File: audio/audacity/Portfile [hunk 2]
```diff
@@ -63,10 +64,29 @@ homepage            http://www.audacityteam.org/
...
+
 depends_build-append \
                     port:${wxWidgets.port}
 
+if {![catch {set wxw_stdlib [active_variants ${wxWidgets.port} stdlib]} err]} {
+    if {${wxw_stdlib}} {
+        long_description-append "This port needs ${wxWidgets.port} without the +stdlib variant."
+        pre-fetch {
+            ui_error "This port needs ${wxWidgets.port} without the +stdlib variant."
+            return -code error "reinstall port:${wxWidgets.port} without the +stdlib variant"
```
Comment (mojca) [inline audio/audacity/Portfile]: Out of curiosity: what problems are caused by `+stdlib`?

File: audio/audacity/Portfile [hunk 3]
```diff
@@ -192,6 +207,18 @@ configure.args-append \
                     CPPFLAGS=-I${prefix}/include \
                     WX_CONFIG=${wxWidgets.wxconfig}
 
+# the embedded portmidi is linux-only as of v2.2.0
+# building against the system portaudio leads to missing symbols due to
+# mismatched symbol visibility which I haven't managed to address.
```
Comment (mojca) [inline audio/audacity/Portfile]: Again, out of pure curiosity. Does it mean that Audacity includes its own copy of `portmidi` (which also comes as a standalone port in MacPorts) which fails to work correctly when built against system libraries? But if you compile against `portmidi` from MacPorts it works OK?

File: audio/audacity/Portfile (hunk 1 above)
Comment (RJVB) [reply audio/audacity/Portfile]: I see that this is no longer required, you fixed the glitch that made this necessary.

File: audio/audacity/Portfile (hunk 2 above)
Comment (RJVB) [reply audio/audacity/Portfile]: I honestly don't remember, I ran into that in March when building against wxWidgets-3.0 . 

Is that the wxWidgets +stdlib variant used by many? In that case it might be worth investigating if this is only a build incompatibility.

File: audio/audacity/Portfile (hunk 3 above)
Comment (RJVB) [reply audio/audacity/Portfile]: Yes and no. Until this version I used the portmidi copy shipped with Audacity, probably as an oversight. That embedded copy can no longer be used because it has received modifications that lock it in to ALSA or some other Linux-specific tech. The build against `port:portmidi` works fine (if it didn't I would have had to strip midi support or add a patch that reverts the mentioned commits).

FWIW, the opposite happened with PortAudio: I did use the copy in MacPorts but that no longer works so I have to use the embedded copy.

**Comment by mojca** [comment]
Copied from Travis (minor issue):
```
Error: conflicts references unknown port: audacity-gtk
```

**Comment by mojca** [comment]
I tried to build `audacity-devel +wx32` and it seems to work fine.  The commits need to be squashed though.

I don't know whether the version for the devel port is the best one, but I have no clue what else to use, so it should work for now (the question is perhaps whether one should put the first part of the git shasum into the version string).

**Comment by RJVB** [comment]
IMHO, never put a git hash directly in a version string; they're random instead of monotonically increasing. Audacity is clever enough to use tags in an appropriate fashion, so `git describe` returns a string that can be massaged into a suitable version number (which is what I'm doing here).

Can commits be squashed using the github web interface? If not I'll have to ask you to commit this some other way.

**Comment by mojca** [comment]
It's worth noting that at the moment the existing Audacity port doesn't build on our buildbot for 10.13:
```
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_audio_audacity/audacity/work/Audacity-2.1.3/lib-src/libflac/src/libFLAC/.libs/libFLAC.a ../lib-src/libflac/src/libFLAC/.libs/libFLAC.a -lid3tag -lmad -lm ../lib-src/libnyquist/libnyquist.a -lSoundTouch -ltwolame -lvorbisenc -lvorbisfile -lvorbis -logg ../lib-src/lv2/liblv2.a ../lib-src/portsmf/libportSMF.a ../lib-src/sbsms/src/.libs/libsbsms.a ../lib-src/libvamp/libvamp-hostsdk.a -framework CoreAudioKit -lz -framework OpenGL -framework System -framework AudioToolbox -framework Cocoa -framework Carbon -framework IOKit
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_ModalDialogDelegate", referenced from:
      objc-class-ref in libFileDialog.a(libFileDialog_la-FileDialogPrivate.o)
ld: symbol(s) not found for architecture x86_64
```

Yes, GitHub allows doing the squash via web interface, but it's disabled for MacPorts because one cannot prevent that from being the default which is not desirable. Anyway, if you allowed modifying the branch, I can squash locally and fix this PR. I don't think there's any need to have more than one commit which makes that operation super easy.

**Comment by mojca** [comment]
Regarding git shasums: I always use something like
```
<version>-<increasing_identifier>-<shasum>
```
Where the `increasing_identifier` is either date or some suffix like `.1` in your case.

In your case I would literally use the output of: `git describe --tags`:  `Audacity-2.2.0-1-gfd3813f`

**Comment by RJVB** [comment]
> It's worth noting that at the moment the existing Audacity port doesn't build on our buildbot for 10.13:

That's one of the trac issues fixed by the patch we've discussed by email.

The "Allow edits from maintainers" checkbox is ticked on this PR, do you need anything else for the squashing?

Re: the -devel version: I'd really prefer to keep it as is so that things like `ver_cmp` work. Using a date form is useful when there's no other information available (but knowing there can be more than 1 commit per day) but a hash really doesn't convey any useful information. Someone who's really interested in a full reference to the commit and knows what to do with that information should be savvy enough to find that it in the Portfile.

**Comment by mojca** [comment]
Can you please double-check my commit? (I made some minor changes.)

**Comment by RJVB** [comment]
LGTM.
