### PR TITLE
logrotate: attempt to fix build on macOS 10.6

### PR DESCRIPTION
**Pull request by chrstphrchvz**
#### Description
[Build fails on macOS 10.6](https://build.macports.org/builders/ports-10.6_i386-builder/builds/24103/steps/install-port/logs/stdio) which doesn't have `O_CLOEXEC` (but which is available from legacysupport):
```
/opt/local/bin/clang-mp-9.0 -DHAVE_CONFIG_H -I.  -include config.h -I/opt/local/include -Wall -Wconversion -Wdeclaration-after-statement -Wextra -Wmissing-format-attribute -Wmissing-noreturn -Wmissing-prototypes -Wpointer-arith -Wshadow -Wstrict-prototypes -Wundef -Wunused -Wwrite-strings -pipe -Os -arch i386 -MT logrotate.o -MD -MP -MF .deps/logrotate.Tpo -c -o logrotate.o logrotate.c
logrotate.c:2900:47: error: use of undeclared identifier 'O_CLOEXEC'
    int lockFd = open(stateFilename, O_RDWR | O_CLOEXEC);
                                              ^
1 error generated.
```

###### ~~Tested on~~

Untested.

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by ctreleaven** [comment]
I don't understand how the "macos-11.0" test was both a failure and a success?

Other than that, looks good to be merged.
