### PR TITLE
kitlist: Update to version 2.0.0

### PR DESCRIPTION
**Pull request by frankdean**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 26.5.1 25F80 arm64
Xcode 26.6 17F113

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] checked your Portfile with `port lint`?
- [x] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vs install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Review by reneeotten — CHANGES_REQUESTED** [review]
whitespace changes should be in a separate commit from functional changes. The diff is now way too large to easily see what the relevant changes are.

**Comment by frankdean** [comment]
> whitespace changes should be in a separate commit from functional changes. The diff is now way too large to easily see what the relevant changes are.

Version 2.0.0 is a rewrite of the application using wxWidgets to replace the [deprecated libglade2](https://mail.gnome.org/archives/devel-announce-list/2009-May/msg00003.html).

File: office/kitlist/Portfile [hunk 1]
```diff
@@ -1,36 +1,38 @@
...
+
+homepage            https://www.fdsd.co.uk/kitlist/
+master_sites        ${homepage}source/
+
+checksums           rmd160  cd42e2d2a38454e737301dfdaaefb502590fccb4 \
+                    sha256  7fb24154418892b2a2560e2d2be360a79257f8b8e569c8642df76ba5a1b562e1 \
+                    size    420450
+
+depends_build       port:pkgconfig
+
```
Comment (barracuda156) [inline office/kitlist/Portfile:34]: This should be path-style. Also, no need for duplicate empty lines.

File: office/kitlist/Portfile [hunk 2]
```diff
@@ -1,36 +1,38 @@
...
+
+depends_lib         port:${wxWidgets.port} \
+                    port:pugixml
+
+configure.args      --with-wxdir=${wxWidgets.wxdir}
+configure.cxxflags-append \
+                    -Wno-writable-strings
```
Comment (barracuda156) [inline office/kitlist/Portfile:43]: This is clang-specific flag.

File: office/kitlist/Portfile [hunk 3]
```diff
@@ -1,36 +1,38 @@
...
-                   port:libglademm \
-                   port:yaml-cpp
-
-configure.args     --disable-build-docs \
-                   --without-gconf
-
-compiler.cxx_standard 2011
-configure.cxxflags-append -std=c++11
+PortSystem          1.0
+PortGroup           wxWidgets 1.0
```
Comment (barracuda156) [inline office/kitlist/Portfile:5]: The app supports ftxui, so a heavy thing like wx can be made optional in a variant.

**Review by barracuda156 — CHANGES_REQUESTED** [review]
Also configure unnecessarily refuses to build with wxGTK and gcc.

**Comment by barracuda156** [comment]
```
configure:5646: checking for wx-config
configure:5649: result: /opt/local/Library/Frameworks/wxWidgets.framework/Versions/wxGTK/3.2/bin/wx-config
configure:5707: checking for wxWidgets version >= 3.2.0
configure:5753: result: yes (version 3.2.10)
configure:5782: checking for wxWidgets static library
configure:5786: result: no
configure:5956: checking if wxWidgets supports selected compiler and platform
configure:5975: /opt/local/bin/g++-mp-16 -std=c++20 -c -pipe -Os -Wno-writable-strings -D_GLIBCXX_USE_CXX11_ABI=0 -arch ppc -DNDEBUG     -I/opt/local/include -I/opt/local/Library/Frameworks/wxWidgets.framework/Versions/wxGTK/3.2/lib/wx/include/gtk3-unicode-3.2 -I/opt/local/Library/Frameworks/wxWidgets.framework/Versions/wxGTK/3.2/include/wx-3.2 -DWXUSINGDLL -D__WXGTK3__ -D__WXGTK__ -D_FILE_OFFSET_BITS=64 conftest.cpp >&5
conftest.cpp: In function 'int main()':
conftest.cpp:19:21: error: expected ';' before numeric constant
   19 |                 exit 1;
      |                     ^~
      |                     ;
At global scope:
cc1plus: note: unrecognized command-line option '-Wno-writable-strings' may have been intended to silence earlier diagnostics
configure:5975: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "kitlist"
| #define PACKAGE_TARNAME "kitlist"
| #define PACKAGE_VERSION "2.0.0"
| #define PACKAGE_STRING "kitlist 2.0.0"
| #define PACKAGE_BUGREPORT "frank.dean@fdsd.co.uk"
| #define PACKAGE_URL ""
| #define PACKAGE "kitlist"
| #define VERSION "2.0.0"
| #define HAVE_CXX20 1
| #define HAVE_GUI 1
| /* end confdefs.h.  */
| #include <iostream>
| int
| main (void)
| {
|   #ifdef __APPLE__
| 		#ifndef __clang__
| 		exit 1;
| 		#else
| 		std::cout << "Is compiling with clang on Apple\n";
| 		#endif
| 		#endif
|   ;
|   return 0;
| }
configure:5980: error: in '/opt/local/var/macports/build/kitlist-a38b468b/work/kitlist-2.0.0':
configure:5982: error: The wxOSX/Cocoa native port of wxWidgets can only be built using Apple clang.  Specify compiler with e.g. CXX=/usr/bin/g++
See 'config.log' for more details
```

**Comment by barracuda156** [comment]
Configuring against FTXUI 7.0.0 (i.e. current release) also fails.

**Comment by barracuda156** [comment]
Unfortunately, not an issue with configure only, the code actually fails:
```
main.cpp: In function 'int main(int, char**)':
main.cpp:218:7: error: 'KitListFtxui' was not declared in this scope; did you mean 'fdsd::ftxui::KitListFtxui'?
  218 |       KitListFtxui ftxui_app;
      |       ^~~~~~~~~~~~
      |       fdsd::ftxui::KitListFtxui
In file included from main.cpp:30:
kitlist_ftxui.hpp:57:7: note: 'fdsd::ftxui::KitListFtxui' declared here
   57 | class KitListFtxui : public KitListBaseApp {
      |       ^~~~~~~~~~~~
main.cpp:219:7: error: 'ftxui_app' was not declared in this scope
  219 |       ftxui_app.run(filename);
      |       ^~~~~~~~~
make[2]: *** [main.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/opt/local/var/macports/build/kitlist-a38b468b/work/kitlist-2.0.0/src'
make[1]: *** [all-recursive] Error 1
```

**Comment by frankdean** [comment]
> Also configure unnecessarily refuses to build with wxGTK and gcc.

Will now build with wxGTK as a variant, once wsGTK 3.2 is available in MacPorts

File: office/kitlist/Portfile (hunk 3 above)
Comment (frankdean) [reply office/kitlist/Portfile:5]: Created a variant for FTXUI

**Comment by frankdean** [comment]
> Configuring against FTXUI 7.0.0 (i.e. current release) also fails.

Should now build with FTXUI 7.0.0, when the port is available in MacPorts.

**Comment by frankdean** [comment]
> Unfortunately, not an issue with configure only, the code actually fails:
> 
> ```
> main.cpp: In function 'int main(int, char**)':
> main.cpp:218:7: error: 'KitListFtxui' was not declared in this scope; did you mean 'fdsd::ftxui::KitListFtxui'?
>   218 |       KitListFtxui ftxui_app;
>       |       ^~~~~~~~~~~~
>       |       fdsd::ftxui::KitListFtxui
> In file included from main.cpp:30:
> kitlist_ftxui.hpp:57:7: note: 'fdsd::ftxui::KitListFtxui' declared here
>    57 | class KitListFtxui : public KitListBaseApp {
>       |       ^~~~~~~~~~~~
> main.cpp:219:7: error: 'ftxui_app' was not declared in this scope
>   219 |       ftxui_app.run(filename);
>       |       ^~~~~~~~~
> make[2]: *** [main.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[2]: Leaving directory `/opt/local/var/macports/build/kitlist-a38b468b/work/kitlist-2.0.0/src'
> make[1]: *** [all-recursive] Error 1
> ```

Fixed.  Thanks!

**Comment by frankdean** [comment]
@barracuda156 the application doesn't build with gcc, either as a wxWidgets application or as an FTXUI one, so I've blacklisted the compiler.

**Comment by barracuda156** [comment]
> @barracuda156 the application doesn't build with gcc, either as a wxWidgets application or as an FTXUI one, so I've blacklisted the compiler.

@frankdean It does, I have literally done that myself (only for wx, but FTXUI should be easier).

P. S. wxWidgets will not build with gcc, possibly, but wxGTK _can_ be built with it.

**Comment by barracuda156** [comment]
Also MacPorts never uses gcc by default on 10.6+ on x86/arm, so blacklisting has only an effect to prevent the build on systems where clangs are not supported. Even if gcc builds were failing, blacklist remains redundant (only relevant for powerpc users).

I will verify with your current portfile in a while and post an update. Replying from mobile right now.

File: office/kitlist/Portfile [hunk 4]
```diff
@@ -1,36 +1,74 @@
...
+if { [string match *clang* ${configure.compiler}] } {
+    configure.cxxflags-append \
+                    -Wno-writable-strings
+} elseif { [string match *gcc* ${configure.compiler}] } {
+    configure.cxxflags-append \
+                    -Wno-write-strings
+    configure.cxx_stdlib    libstdc++
+}
+
+variant wxwidgets32 conflicts wxgtk32 description {Use wxWidgets 3.2 with GTK} {
```
Comment (barracuda156) [inline office/kitlist/Portfile]: Descriptions are swapped.

File: office/kitlist/Portfile [hunk 5]
```diff
@@ -1,36 +1,74 @@
...
+compiler.cxx_standard \
+                    2020
+
+if { [string match *clang* ${configure.compiler}] } {
+    configure.cxxflags-append \
+                    -Wno-writable-strings
+} elseif { [string match *gcc* ${configure.compiler}] } {
+    configure.cxxflags-append \
+                    -Wno-write-strings
+    configure.cxx_stdlib    libstdc++
```
Comment (barracuda156) [inline office/kitlist/Portfile]: Please do not manually reset C++ runtime. For libc++-based systems it is wrong, since dependencies use libc++. For libstdc++-using systems this will result in omitting C++ ABI flag, which gonna break linkage with missing symbols.

File: office/kitlist/Portfile [hunk 6]
```diff
@@ -1,36 +1,74 @@
...
+depends_build       port:autoconf-archive \
+                    path:bin/pkg-config:pkgconfig
+
+depends_lib         port:pugixml
+
+use_autoreconf      yes
+autoreconf.args     --install --force --replace-handwritten
+
+compiler.blacklist  *gcc*
+compiler.fallback   clang
```
Comment (barracuda156) [inline office/kitlist/Portfile]: Neither of these are needed (or correct). MacPorts does not pick gcc on any arm64/x86_64 systems at least for 10.6+ (I am not sure what happens on 10.5 i386). Falling back to Apple clang will not work for macOS where the system clang does not support C++20. The build with gcc works fine on `libstdc++`-using systems (which is the only relevant case anyway), so blacklist unnecessarily breaks the port.

File: office/kitlist/Portfile [hunk 7]
```diff
@@ -1,36 +1,74 @@
...
+    configure.cxx_stdlib    libstdc++
+}
+
+variant wxwidgets32 conflicts wxgtk32 description {Use wxWidgets 3.2 with GTK} {
+    wxWidgets.use               wxWidgets-3.2
+    configure.args-append       --with-wxdir=${wxWidgets.wxdir}
+    depends_lib-append          port:${wxWidgets.port}
+}
+
+variant wxgtk32 conflicts wxwidgets32 description {Use Cocoa-based wxWidgets 3.2} {
```
Comment (barracuda156) [inline office/kitlist/Portfile]: This should probably be commented out, since MacPorts does not have the port for wxGTK-3.2 at the moment.

File: office/kitlist/Portfile [hunk 8]
```diff
@@ -1,36 +1,74 @@
...
+    wxWidgets.use               wxGTK-3.2
+    configure.args-append       --with-wxdir=${wxWidgets.wxdir}
+    depends_lib-append          port:${wxWidgets.port}
+}
+
+variant ftxui description {Use FTXUI text based front-end} {
```
Comment (barracuda156) [inline office/kitlist/Portfile:63]: Is +ftxui compatible with +wx*?

**Review by barracuda156 — CHANGES_REQUESTED** [review]

File: office/kitlist/Portfile (hunk 8 above)
Comment (frankdean) [reply office/kitlist/Portfile:63]: It will build an executable that can then run with either front-end, based on command line parameters.

File: office/kitlist/Portfile (hunk 4 above)
Comment (frankdean) [reply office/kitlist/Portfile]: My bad.  Thanks.

File: office/kitlist/Portfile (hunk 5 above)
Comment (frankdean) [reply office/kitlist/Portfile]: Removed.

File: office/kitlist/Portfile (hunk 8 above)
Comment (barracuda156) [reply office/kitlist/Portfile:63]: Great

File: office/kitlist/Portfile (hunk 6 above)
Comment (frankdean) [reply office/kitlist/Portfile]: Removed.

File: office/kitlist/Portfile (hunk 7 above)
Comment (frankdean) [reply office/kitlist/Portfile]: Commented out

**Comment by barracuda156** [comment]
@frankdean The build works now fine with both wxGTK and FTXUI enabled. How do I run it with TUI though? `kitlist --help` errors out with unable to initialize GTK (which happens because I do not have X server active, but I do not want to run wx in this case).

**Comment by frankdean** [comment]
> @frankdean The build works now fine with both wxGTK and FTXUI enabled. How do I run it with TUI though? `kitlist --help` errors out with unable to initialize GTK (which happens because I do not have X server active, but I do not want to run wx in this case).

If wx* is enabled, main() is implemented by wxWidgets, so I think it would need to be compiled without +wx* to run without the X server being available.  The FTXUI implementation is something of an experiment and not 100% complete.  Some notes in the README.

**Comment by barracuda156** [comment]
Just to illustrate the GCC build works:
[kitlist.gcc.log.txt](https://github.com/user-attachments/files/29946719/kitlist.gcc.log.txt)

**Comment by frankdean** [comment]
> Just to illustrate the GCC build works: [kitlist.gcc.log.txt](https://github.com/user-attachments/files/29946719/kitlist.gcc.log.txt)

That's great news!   Many thanks for your help!

**Comment by barracuda156** [comment]
If you had failures with gcc on a recent macOS, those are likely either due to libc++ issues (by default MacPorts uses the system C++ runtime on libc++ systems) or due to gcc issues with parsing Apple system headers. The latter is rather annoying, but does not happen on older macOS.

**Review by barracuda156 — APPROVED** [review]
All the build issues with older macOS have been resolved.

Building with wxGTK may require `legacysupport` PG (depending on how that gets implemented), but since the variant is not enabled at the moment, that is irrelevant.

**Comment by barracuda156** [comment]
@frankdean Ah, sorry, one more thing: since wxGTK-3.2 does not exist in MacPorts, it is better to default to `+tui` on older macOS where wxWidgets do not build.

If we are to believe buildbots, on < 10.10 it does not: https://ports.macports.org/port/wxWidgets-3.2/details

**Comment by frankdean** [comment]
> @frankdean Ah, sorry, one more thing: since wxGTK-3.2 does not exist in MacPorts, it is better to default to `+tui` on older macOS where wxWidgets do not build.
> 
> If we are to believe buildbots, on < 10.10 it does not: https://ports.macports.org/port/wxWidgets-3.2/details

I've added that.  Thanks again for all your help.

**Review by barracuda156 — APPROVED** [review]
Thank you!

**Comment by frankdean** [comment]
@reneeotten Thanks!
