### PR TITLE
hugs98: fix the build

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

`hugs98` is an old port which has been failing across the board for ages: https://ports.macports.org/port/hugs98/details/
Same on FreeBSD: https://www.freshports.org/lang/hugs/
So I am not sure it will build on newer systems, since it may need an old `gcc` version.
It is confirmed to build for PPC now, and I believe Intel build should work too, at least on 10.5.x–10.6.x.

@mascguy @kencu Looks like I have fixed another archaic Haskell compiler :)
```
10:~ svacchanda$ port -v installed hugs98
The following ports are currently installed:
  hugs98 @plus-Sep2006_3 (active) requested_variants='' platform='darwin 10' archs='ppc' date='2022-08-08T01:33:22+0545'
```

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 Server
Xcode 3.2.6

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by barracuda156** [comment]
Strangely, bots try using Clang despite explicit blacklisting in the portfile (blacklisting was not introduced by me – this port never built with Clang in Macports).

How to convince them to use GCC?

**Comment by barracuda156** [comment]
@evanmiller Could you please test the build on Leopard and/or Tiger?

**Comment by barracuda156** [comment]
@mascguy I got an idea, but I need your help to test it. Since the port does not build with Clang or new GCC, but builds with gcc-4.2, it way work with `apple-gcc-4.2`, and then it gonna – hopefully – build up to El Capitan: https://ports.macports.org/port/apple-gcc42/details/

I will make a commit to introduce a build dependency on `apple-gcc-4.2` for select OSs now. If you are okay with trying it, please merge. (It does not harm anyone, since currently the port is broken anyway. In the worst case we get it fixed for <11.)

**Comment by barracuda156** [comment]
@mascguy If this works, we can try the same for `nhc98`.

**Comment by barracuda156** [comment]
UPD. In fact let me try something first.

**Comment by barracuda156** [comment]
@mascguy @kencu Any idea why it fails to pass checks?
```
checking how to run the C preprocessor... /opt/local/bin/cpp-mp-12 -arch x86_64 -traditional-cpp -Uvector
  configure: error: in `/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_lang_hugs98/hugs98/work/hugs98-plus-Sep2006':
  configure: error: C preprocessor "/opt/local/bin/cpp-mp-12 -arch x86_64 -traditional-cpp -Uvector" fails sanity check
  See `config.log' for more details
  Command failed:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_lang_hugs98/hugs98/work/hugs98-plus-Sep2006" && ./configure --prefix=/opt/local CPP="/opt/local/bin/cpp-mp-12 -arch x86_64 -traditional-cpp -Uvector" 
  Exit code: 1
```
I do not get this config failure locally with `gcc12` and `-arch ppc`. And we do need those `-traditional-cpp -Uvector` flags, otherwise we get this kind of error: https://github.com/E3SM-Project/E3SM/issues/2725

**Comment by mascguy** [comment]
I'll defer to @kencu and @cjones051073, in terms of how we deal with this port.

**Comment by barracuda156** [comment]
So yeah, compare (portfile is identical).

Buildbot (`gcc12`, x86):
```
DEBUG: system:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_lang_hugs98/hugs98/work/hugs98-plus-Sep2006" && ./configure --prefix=/opt/local CPP="/opt/local/bin/cpp-mp-12 -traditional-cpp -Uvector" 
  checking build system type... i686-apple-darwin21.6.0
  checking host system type... i686-apple-darwin21.6.0
  checking target system type... i686-apple-darwin21.6.0
  checking for bison... bison -y
  checking for gcc... /opt/local/bin/gcc-mp-12
  checking whether the C compiler works... yes
  checking for C compiler default output file name... a.out
  checking for suffix of executables... 
  checking whether we are cross compiling... no
  checking for suffix of object files... o
  checking whether the compiler supports GNU C... yes
  checking whether /opt/local/bin/gcc-mp-12 accepts -g... yes
  checking for /opt/local/bin/gcc-mp-12 option to enable C11 features... none needed
  checking how to run the C preprocessor... /opt/local/bin/cpp-mp-12 -traditional-cpp -Uvector
  configure: error: in `/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_lang_hugs98/hugs98/work/hugs98-plus-Sep2006':
  configure: error: C preprocessor "/opt/local/bin/cpp-mp-12 -traditional-cpp -Uvector" fails sanity check
  See `config.log' for more details
  Command failed:  cd "/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_lang_hugs98/hugs98/work/hugs98-plus-Sep2006" && ./configure --prefix=/opt/local CPP="/opt/local/bin/cpp-mp-12 -traditional-cpp -Uvector" 
  Exit code: 1
```
My local build (`gcc12`, ppc):
```
Executing:  cd "/opt/local/var/macports/build/_opt_PPCRosettaPorts_lang_hugs98/hugs98/work/hugs98-plus-Sep2006" && ./configure --prefix=/opt/local CPP="/opt/local/bin/cpp-mp-12 -traditional-cpp -Uvector" CC="/opt/local/bin/gcc-mp-12 -arch ppc" --build=powerpc-apple-darwin10 
checking build system type... powerpc-apple-darwin10
checking host system type... powerpc-apple-darwin10
checking target system type... powerpc-apple-darwin10
checking for bison... bison -y
checking for gcc... /opt/local/bin/gcc-mp-12 -arch ppc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether /opt/local/bin/gcc-mp-12 -arch ppc accepts -g... yes
checking for /opt/local/bin/gcc-mp-12 -arch ppc option to enable C11 features... none needed
checking how to run the C preprocessor... /opt/local/bin/cpp-mp-12 -traditional-cpp -Uvector
checking for grep that handles long lines and -e... /opt/local/bin/ggrep
checking for egrep... /opt/local/bin/ggrep -E
```

**Comment by barracuda156** [comment]
> I'll defer to @kencu and @cjones051073, in terms of how we deal with this port.

@mascguy Thanks. It is really weird, since in completely identical settings preprocessor works for me (on Rosetta) but fails on bots.

P. S. Well, if this approach fails to work eventually, we can revert to using `apple-gcc-4.2` for all Intel systems where it builds and set `known_fail` for the later ones. _Though it should work with newer gccs._

**Comment by barracuda156** [comment]
@mascguy The current status:

1. As @catap confirmed, my port builds on 10.6.8 for x86_64 using stock compiler. So at least we got some Intel fixed.
2. Later MacOS SDK have some differences due to which `-traditional-cpp -Uvector` fails on them. It is not a problem of `gcc12`, since on 10.6.8 Rosetta `gcc12` works for me.
3. I tried using `tradcpp` for >10, but `RAWCPP=${prefix}/bin/tradcpp` arg is ignored by the build system (nothing is changed), while `CPP=${prefix}/bin/tradcpp` is recognized, but fails on config (both on buildbots and locally on 10.6.8):
```
checking for /opt/local/bin/gcc-mp-12 option to enable C11 features... none needed
  checking how to run the C preprocessor... /opt/local/bin/tradcpp
  configure: error: in `/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_lang_hugs98/hugs98/work/hugs98-plus-Sep2006':
  configure: error: C preprocessor "/opt/local/bin/tradcpp" fails sanity check
```

**Comment by barracuda156** [comment]
@FranklinChen Maybe you could suggest something? I am out of ideas how to fix preprocessing for newer MacOSs. With `-traditional-cpp -Uvector` cpp errs on SDK, and without it errs on the code itself. `tradcpp` does not work either.

**Comment by mascguy** [comment]
> The current status:
>     1. As @catap confirmed, my port builds on 10.6.8 for x86_64 using stock compiler. So at least we got some Intel fixed.
>     2. Later MacOS SDK have some differences due to which `-traditional-cpp -Uvector` fails on them. It is not a problem of `gcc12`, since on 10.6.8 Rosetta `gcc12` works for me.
>     3. I tried using `tradcpp` for >10, but `RAWCPP=${prefix}/bin/tradcpp` arg is ignored by the build system (nothing is changed), while `CPP=${prefix}/bin/tradcpp` is recognized, but fails on config (both on buildbots and locally on 10.6.8):
> 
> ```
> checking for /opt/local/bin/gcc-mp-12 option to enable C11 features... none needed
>   checking how to run the C preprocessor... /opt/local/bin/tradcpp
>   configure: error: in `/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_lang_hugs98/hugs98/work/hugs98-plus-Sep2006':
>   configure: error: C preprocessor "/opt/local/bin/tradcpp" fails sanity check
> ```

Unfortunately my knowledge is lacking in this area, so I'll defer to others.

**Comment by barracuda156** [comment]
@evanmiller Maybe you got some ideas here?

**Comment by barracuda156** [comment]
Just a memo for myself on what to fix: Rosetta has `ld` issues with `gcc-4.2` (though the build does not err out on these):
```
ld: warning: in /opt/local/lib/libX11.dylib, file was built for ppc7400 which is not the architecture being linked (x86_64)
../../libraries/tools/hsc2hs -D__HUGS__ -Iinclude -I/opt/local/include --lflag=-lX11 -o Graphics/X11/Xlib/Atom.hs Graphics/X11/Xlib/Atom.hsc
ld: warning: in /opt/local/lib/libX11.dylib, file was built for ppc7400 which is not the architecture being linked (x86_64)
../../libraries/tools/hsc2hs -D__HUGS__ -Iinclude -I/opt/local/include --lflag=-lX11 -o Graphics/X11/Xlib/Event.hs Graphics/X11/Xlib/Event.hsc
ld: warning: in /opt/local/lib/libX11.dylib, file was built for ppc7400 which is not the architecture being linked (x86_64)
```

**Comment by barracuda156** [comment]
Well, this port is stubborn -_-
```
runhugs: Error occurred
  ERROR "libraries/bootlib/Foreign/C/Types.hs":173 - Undefined type constructor "NotReallyAType"
```
And this thing is only present in some obscure macros in configure scripts.

At the same time, the port builds fine on old systems, with recent fixes or without.

**Comment by barracuda156** [comment]
If anyone thinks we are better off restricting Hugs to systems that can use apple-gcc-4.2, let me know. Currently existing in Macports version is completely broken. My port at least builds on 10.5 and 10.6 (ppc and x86).

**Comment by barracuda156** [comment]
For the record, with `clang` it failed pretty much identically like with `gcc` just before. Multiple warnings:
```
warning: missing terminating '"' character [-Winvalid-pp-token]
```
Then:
```
Undefined symbols for architecture x86_64:
    "_main", referenced from:
       implicit entry/start for main executable
  ld: symbol(s) not found for architecture x86_64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  runhugs: Error occurred
```
And:
```
ERROR "libraries/bootlib/Foreign/C/Types.hs":173 - Undefined type constructor "NotReallyAType"
```

**Comment by barracuda156** [comment]
@harens May I request you to take a look and hopefully merge? I am not gonna waste more time trying to fix it for newer macOS and clangs. Disabling those, like for `nhc98` earlier.

Presently the port is just broken: https://ports.macports.org/port/hugs98/details
We can’t make it worse, and I have verified that it builds successfully with Xcode gcc-4.2 and modern gcc-12.
At least on 10.6, it build both for ppc and x86.

There is little point to have it on modern macOS where GHC is supported, but it will be nice to have it finally fixed on older systems, where no modern Haskell compilers work atm.

File: lang/hugs98/files/patch-packages.diff [hunk 1]
```diff
@@ -0,0 +1,143 @@
...
+ # internal Hugs modules
+
+--- packages/network/include/HsNetworkConfig.h.in.orig	2006-09-21 05:33:38.000000000 +0700
++++ packages/network/include/HsNetworkConfig.h.in	2022-09-20 23:43:56.000000000 +0700
+@@ -36,7 +36,7 @@
+ /* Define to 1 if you have the <netinet/tcp.h> header file. */
+ #undef HAVE_NETINET_TCP_H
+ 
+-/* Define to 1 if you have the `readlink' function. */
++/* Define to 1 if you have the `readlink` function. */
```
Comment (harens) [inline lang/hugs98/files/patch-packages.diff:106]: This seems to only be changing the apostrophe type within some comments? This change is made a few times within the file.

File: lang/hugs98/files/patch-gcc-inline.diff [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+-#  define INLINE extern inline
++#  ifdef __GNUC_STDC_INLINE__
++#   define INLINE extern inline __attribute__((__gnu_inline__))
++#  else
++#   define INLINE extern inline
++#  endif
+ # else
+ #  define INLINE inline
+ # endif
+
```
Comment (harens) [inline lang/hugs98/files/patch-gcc-inline.diff:20]: nitpick: This file is missing a newline at the end.

**Review by harens — COMMENTED** [review]
I won't pretend I understand what everything does, but you've put a lot of time and effort into this (thank you 😄) so I'm happy to merge this if nobody else has any comments.

File: lang/hugs98/Portfile [hunk 3]
```diff
@@ -1,42 +1,90 @@
...
+
+checksums           rmd160  4a7e744360a29fbf94f5ac86ea559e80f12205a5 \
+                    sha256  aafaca9ca544572ebef70bbe86b5eb0abaa5d7c11c0b766d7db72a46b022bed5 \
+                    size    5322244
 
-homepage            http://www.haskell.org/hugs/
-master_sites        http://cvs.haskell.org/Hugs/downloads/2006-09/
+depends_build-append \
+                    port:bison \
+                    port:gmake
```
[the remark this answers is not in the document]
Comment (barracuda156) [reply lang/hugs98/Portfile:26]: Let me check and fix this.

[the remark this answers is not in the document]
Comment (barracuda156) [reply lang/hugs98/Portfile]: Fixed, thank you.

File: lang/hugs98/files/patch-gcc-inline.diff (hunk 2 above)
Comment (barracuda156) [reply lang/hugs98/files/patch-gcc-inline.diff]: Added.

File: lang/hugs98/files/patch-packages.diff (hunk 1 above)
Comment (barracuda156) [reply lang/hugs98/files/patch-packages.diff]: Removed these, indeed inconsequential.

**Comment by barracuda156** [comment]
> I won't pretend I understand what everything does, but you've put a lot of time and effort into this (thank you 😄) so I'm happy to merge this if nobody else has any comments.

@harens Suggested fixes made, thank you.

File: lang/hugs98/Portfile [hunk 4]
```diff
@@ -1,42 +1,88 @@
...
+
+PortSystem          1.0
 
 name                hugs98
 version             plus-Sep2006
-revision            2
-categories          lang
-maintainers         nomaintainer
-platforms           darwin
+revision            3
```
Comment (harens) [inline lang/hugs98/Portfile:7]: Sorry @barracuda156 just noticed that this doesn't warrant a revbump, since it only fixes the build and doesn't modify any installed files. Taking a look at the [stats](https://ports.macports.org/port/hugs98/stats/), the few people that do have hugs98 installed shouldn't have to rebuild it.

Also, it seems like at least three people have (somehow) installed it on macOS 12 and 10.13, but here we're blacklisting for > 10.11

Comment (barracuda156) [reply lang/hugs98/Portfile:7]: > doesn't warrant a revbump, since it only fixes the build and doesn't modify any installed files

We cannot be sure that everything is installed exactly the same, since there are new patches. We already had a case with another port, when avoiding revbump in a silimar situation led into trouble.

> Also, it seems like at least three people have (somehow) installed it on macOS 12 and 10.13, but here we're blacklisting for > 10.11

I have seen that, but it is likely some glitch. Neither buildbots (with current version of the port) nor CIs (with updated one) succeeded to build it on newer OSs.

**Comment by harens** [comment]
Thanks for all of your work on this @barracuda156! :)

File: lang/hugs98/Portfile (hunk 4 above)
Comment (barracuda156) [reply lang/hugs98/Portfile:7]: @harens Thank you! Glad this is finally merged.
