### PR TITLE
gdb-apple: fix build on 10.5/10.6

### PR DESCRIPTION
**Pull request by evanmiller**
#### Description

* Split `patch-gdb-availability.diff` into 2 pieces to be more manageable
* Promote the larger piece to be applied unconditionally, testing function-relevant macros instead of MAC_OS_X_VERSION_MIN_REQUIRED (this fixes a build problem on 10.5)
* Fix a duplicate symbol linking error witnessed on 10.6 with clang-11
* Promote `patch-macosx-tdep.c.diff` to be applied unconditionally
* Add `size` to the checksums

CC @kencu and @barracuda156

###### Type(s)

- [x] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8
Xcode x.y

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

**Review by mascguy — APPROVED** [review]
Approving on behalf of Jeremy.

But we can leave this open for three days, to provide others the opportunity to review.

**Comment by kencu** [comment]
looks ok to me too.

**Comment by barracuda156** [comment]
@evanmiller I fully understand that my exotic case is no one's concern, haha, but for the record, new patch fails on 10.6 PPC on this:
```
./macosx/macosx-nat-dyld.c: In function ‘macosx_locate_dyld_via_taskinfo’:
./macosx/macosx-nat-dyld.c:809: error: ‘struct task_dyld_info’ has no member named ‘all_image_info_addr’
./macosx/macosx-nat-dyld.c:810: error: ‘struct task_dyld_info’ has no member named ‘all_image_info_size’
./macosx/macosx-nat-dyld.c:812: error: ‘struct task_dyld_info’ has no member named ‘all_image_info_addr’
./macosx/macosx-nat-dyld.c:869: warning: unused variable ‘dyld_here’
./macosx/macosx-nat-dyld.c: In function ‘macosx_get_osabi_from_dyld_entry’:
./macosx/macosx-nat-dyld.c:1926: warning: passing argument 1 of ‘xfree’ discards qualifiers from pointer target type
./macosx/macosx-nat-dyld.c:1929: warning: passing argument 1 of ‘xfree’ discards qualifiers from pointer target type
./macosx/macosx-nat-dyld.c: In function ‘dyld_fix_path’:
./macosx/macosx-nat-dyld.c:3631: warning: unused variable ‘prefix’
make[1]: *** [macosx-nat-dyld.o] Error 1
```
While the old one was transparent enough to change, the new one is not.

**Comment by mascguy** [comment]
> @evanmiller I fully understand that my exotic case is no one's concern, haha, but for the record, new patch fails on 10.6 PPC on this:
>
> [...]
>
> While the old one was transparent enough to change, the new one is not.

Evan, let me know if there's anything I can to help. (Even if it's just merging the ultimate PR/change.)

**Comment by kencu** [comment]
10.6 PPC is about 1/2 way between 10.6 and 10.5 in SDK features. so things that might be expected to work on 10.6 don’t work. Sometimes you can force a 10.5 path for it, but it’s a frustrating lot of extra work and testing for a system that is exceptionally niche in use and interest. So you really need to be using it, and care…

I was initially intrigued, but then uninterested once all the many warts were made visible. I can’t see anything 10.6 for PPC can do that 10.5 doesn’t do better, so far at least. 

The kludgy workarounds often needed to pathway 10.6 for PPC are IMHO generally too hack for MacPorts.

But sometimes trying build on that system turns up more generic logic errors in base or portfiles, and those are reasonable to fix.

**Comment by barracuda156** [comment]
@kencu The earlier version of @evanmiller patch here had a condition on the OS (>=10500) – which in fact should have been >=10600 – so it was transparent to modify it for the case of 10.6 PPC. New patch made it unnecessarily non-trivial. Anyone else who would want to make `gdb-apple` work for 10.6 PPC now will need to reinvent the bicycle or dig out the old version of the patch.
Does the new conditioning give any benefits? I do not ask anyone to make others' life difficult for the sake of a niche case, but I think it is reasonable not to make niche life more difficult without a good reason.

>I can’t see anything 10.6 for PPC can do that 10.5 doesn’t do better, so far at least.

I have demonstrated a couple of such cases in fact, though, admittedly, nothing tremendously significant.

**Comment by evanmiller** [comment]
> @kencu The earlier version of @evanmiller patch here had a condition on the OS (>=10500) – which in fact should have been >=10600 – so it was transparent to modify it for the case of 10.6 PPC. New patch made it unnecessarily non-trivial. Anyone else who would want to make `gdb-apple` work for 10.6 PPC now will need to reinvent the bicycle or dig out the old version of the patch. Does the new conditioning give any benefits? I do not ask anyone to make others' life difficult for the sake of a niche case, but I think it is reasonable not to make niche life more difficult without a good reason.
> 
> > I can’t see anything 10.6 for PPC can do that 10.5 doesn’t do better, so far at least.
> 
> I have demonstrated a couple of such cases in fact, though, admittedly, nothing tremendously significant.

If you need a pre-processor line to evaluate to false, you can always change it to `#if 0` locally. The new logic tries to condition on the features that the SDK self-reports as available. This is generally less error-prone than conditioning on OS versions and releases, but as you discovered there are exceptions to the rule.
