### PR TITLE
openmpi: Fix GCC check and reenable parallel build

### PR DESCRIPTION
**Pull request by saagarjha**
#### Description

There are a couple of things to note here:
* I've reenabled parallel builds. In the process of updating Open MPI, I must have run a dozen or so builds and didn't see any issues, so I figured it might be OK to remove the restriction in hopes that it had been fixed upstream.
* I've moved around some lines relating to Fortran in an effort to fix what I felt were bugs in the current install, which would always depend on GCC and hence enable Fortran unconditionally. I'm not super confident on how this variant is supposed to work, since it looks to me that you cannot use Fortran with clang anyways, but I think the new behavior is better than what we had before.

Finally, one odd quirk that I didn't see fit to include in this pull request but I thought I'd mention: I run MacPorts so that it pulls port information off of Git, so in the Fortran variant builds I'd get an error where some autogenerated files would have lines like these:

```fortran
include '/opt/local/var/macports/build/_Users_saagarjha_Git_macports-ports_science_openmpi/openmpi-default/work/openmpi-4.0.0/ompi/mpiext/pcollreq/mpif-h/mpiext_pcollreq_mpifh.h'
```

which would kill the build unless I set `FCFLAGS='-ffree-line-length-none'` because apparently it's a syntax error in Fortran to have a line longer than 132 characters.

###### Type(s)

- [ ] bugfix
- [X] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.4 18E184e
Xcode 10.2 10P91b

###### Verification 
Have you

- [X] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [X] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [X] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [X] checked your Portfile with `port lint`?
- [X] tried a full install with `sudo port -vst install`?
- [X] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by saagarjha** [comment]
Hmm, is there something I should do about clang33 and clang34? It seems macOS doesn't support these anymore.

**Comment by seanfarley** [comment]
> Hmm, is there something I should do about clang33 and clang34? It seems macOS doesn't support these anymore.

That ... is a good question. I know macports supports older versions but if change the logic for this then the compilers group and mpi group will need to be updated.

**Comment by kencu** [comment]
clang 3.3 is not of much use anymore, but clang-3.4 is pretty critical for bootstrapping at least still, on older systems.

clang-3.4 is the last clang that could build (on Intel) with gcc-4.2 using Autotools, so we'll probably have that forever.

**Comment by cjones051073** [comment]
So where do we stand with this PR ?

**Comment by kencu** [comment]
Clang-3.4 is only needed up to about 10.8 or so I think. It’s needed for bootstrap and also there are a couple of ports that force it as the compiler for certain builds. 

If it doesn’t build on the newer systems that’s not an issue.

**Comment by reneeotten** [comment]
```openmpi``` was updated to its latest version in [this commit](https://github.com/macports/macports-ports/commit/b6fddbb06ee1eceb8dde6279a99b73ce0cb096db). I am not sure whether that has addressed the points raised in this PR; but, if so, this should probably be closed.

**Comment by GiovanniBussi** [comment]
Openmpi does not build correctly on OSX 10.11 (El Capitan). Here's part of the error message:
````
:info:build /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_science_openmpi/openmpi-default/work/openmpi-4.0.1/opal/mca/pmix/pmix3x/pmix/src/server/pmix_server_ops.c:3432:19: error: use of undeclared identifier 'CLOCK_MONOTONIC'
:info:build     clock_gettime(CLOCK_MONOTONIC, &tp);
````
Apparently, this is a [known issue](https://github.com/open-mpi/ompi/issues/6583). Is there a way to roll back to openmpi 3 when using older OS? Thanks! Giovanni

**Comment by cjones051073** [comment]
Try adding the legacysupport portgroup. This is specifically designed to address issues exactly like this.

**Comment by cjones051073** [comment]
seems to be working with my OSX10.11 VM, so I've pushed

https://github.com/macports/macports-ports/commit/fbb6e3c435e059dde92628c6bdc659142074c14c

File: science/openmpi/Portfile [hunk 1]
```diff
@@ -136,15 +137,13 @@ if {${subport} != ${name}} {
     archive_sites
 
     depends_build-append        port:pkgconfig
+    depends_build-append        port:perl5
```
Comment (cjones051073) [inline science/openmpi/Portfile]: I suspect this is no longer needed, due to changes made to perl5 since you first submitted this. Can you remove this line ?

File: science/openmpi/Portfile [hunk 2]
```diff
@@ -136,15 +137,13 @@ if {${subport} != ${name}} {
...
     depends_lib-append          port:hwloc
     depends_run                 port:mpi_select port:mpi-doc
     select.group                mpi
     select.file                 ${filespath}/${name}-${cname}
     livecheck.type              none
 
-    # avoid "Can't open profile/psizeof_f08.f90 for writing"
-    use_parallel_build no
```
Comment (cjones051073) [inline science/openmpi/Portfile]: I agree if this is no longer needed it would be good to reenable parallel builds.

File: science/openmpi/Portfile [hunk 3]
```diff
@@ -210,9 +209,9 @@ if {${subport} != ${name}} {
         append long_description " (AND THE FORTRAN COMPILER SELECTED BY THE VARIANT, IF ANY)"
 
         compilers.choose   fc
-        compilers.setup    default_fortran
```
Comment (cjones051073) [inline science/openmpi/Portfile]: Should you also move the first choose line here too ?

**Comment by cjones051073** [comment]
Reviewing the residual changes, there is still some merit I think to merging this. For instance updating the devel port, and reenable parallel builds. 

@saagarjha can you please though update the PR title and description accordingly ?

File: science/openmpi/Portfile (hunk 2 above)
Comment (cjones051073) [reply science/openmpi/Portfile]: It would be useful though if you could find reference to an upstream commit addressing this ... Just to prove its specifically been addressed.

File: science/openmpi/Portfile (hunk 1 above)
Comment (saagarjha) [reply science/openmpi/Portfile]: Yup, I can confirm that the port builds without this line.

File: science/openmpi/Portfile (hunk 3 above)
Comment (saagarjha) [reply science/openmpi/Portfile]: Sure.

File: science/openmpi/Portfile (hunk 2 above)
Comment (saagarjha) [reply science/openmpi/Portfile]: I don't have much context around this change, actually: I just never saw it occur in the dozens of builds I ran and not making this change would have made the take many times longer…

Comment (cjones051073) [reply science/openmpi/Portfile]: OK thanks. I am inclined to agree. If problems reappear the option can always be put back.

File: science/openmpi/Portfile (hunk 3 above)
Comment (cjones051073) [reply science/openmpi/Portfile]: thanks

**Comment by cjones051073** [comment]
OK, as this port is now `nomaintainer` I am going to merge this. Note, I have also submitted https://github.com/macports/macports-ports/pull/4314 which removes support for various versions on platforms where the various compilers are no longer supported.
