### PR TITLE
HexFiend: update to 2.13.1

### PR DESCRIPTION
**Pull request by Tatsh**
#### Description

https://trac.macports.org/ticket/57824

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.15.7 19H2
Xcode 12.1 12A7403

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`? n/a
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?

### CODE REVIEW

File: editors/HexFiend/Portfile [hunk 1]
```diff
@@ -5,12 +5,11 @@ PortGroup       xcode 1.0
...
-github.setup    ridiculousfish HexFiend 2.9.0 v
-checksums       rmd160  ba4276249a262c1b808baafe3aa580ecfa75f224 \
-                sha256  158d398c7f723a1b1e622cabac7dd80b5556a64c8b649ab88e9989f45d2a39cc \
-                size    3474321
+github.setup    ridiculousfish HexFiend 2.13.1 v
+checksums       rmd160  7677158ec5d61351eae8086f0c37c04b9766c8c7 \
+                sha256  54a9eee7d2f3f25e8a7217fe89cdd6ee796a53e495e75e0e7dfdb5764d5ca34f \
+                size    3488533
 
-epoch           1
```
Comment (mf2k) [inline editors/HexFiend/Portfile:13]: This line needs to be restored. The `epoch` can never be decreased because anyone who has this port installed will not see this update.

**Review by mf2k — CHANGES_REQUESTED** [review]

File: editors/HexFiend/Portfile (hunk 1 above)
Comment (Tatsh) [reply editors/HexFiend/Portfile:13]: Restored the line.

**Review by mf2k — APPROVED** [review]
You need to add the reference to the Trac ticket to the commit message:

`Closes: https://trac.macports.org/ticket/57824`

**Comment by Tatsh** [comment]
> You need to add the reference to the Trac ticket to the commit message:
> 
> `Closes: https://trac.macports.org/ticket/57824`

Done.

**Comment by neverpanic** [comment]
The hexfiend-framework subport seems to fail. However, the Hexfiend port seems to install the Framework in `/Applications/MacPorts/Hex Fiend.app/Contents/Frameworks/HexFiend.framework/`. Maybe we should just drop the subport?

**Comment by Tatsh** [comment]
> The hexfiend-framework subport seems to fail. However, the Hexfiend port seems to install the Framework in `/Applications/MacPorts/Hex Fiend.app/Contents/Frameworks/HexFiend.framework/`. Maybe we should just drop the subport?

I think so. I don't see anything depending on the HexFiend framework package.

**Comment by neverpanic** [comment]
Can you push a change that just drops it? I don't think there's a big point in explicitly marking it as obsoleted either.

**Review by neverpanic — APPROVED** [review]
If this passes CI, I'm merging it.

**Comment by neverpanic** [comment]
This fails on 10.13 with
```
/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_editors_HexFiend/HexFiend/work/ridiculousfish-HexFiend-5a08e1f/framework/sources/HFFunctions.m:955:66: error: use of undeclared identifier 'NSAppearanceNameDarkAqua'; did you mean 'NSAppearanceNameAqua'?
```
I'm assuming the versions below that will also not work.

Should we modify the block at the bottom to be `${os.major} < 14` and modify the error message?

The Azure 10.14 build fails with what seems to be a permission problem, but according to https://trac.macports.org/ticket/61392 there are currently some problems with that, so I wouldn't consider that blocking.

**Comment by Tatsh** [comment]
If that's the only error we might be able to patch it to work on 10.13 but unfortunately right now I have no way to test locally.

On the latest HEAD they are using more new constants that are not available in older SDKs so this is a kind of a ongoing issue. Unfortunately it looks like upstream is too willing to drop older SDKs and Xcode versions. 

The binary should still work on 10.12 and above. Would need an update from upstream on what macOS versions they intend to support.

**Comment by neverpanic** [comment]
The build on 10.14 passes for me locally with this patch:
```
diff --git a/editors/HexFiend/Portfile b/editors/HexFiend/Portfile
index 08ec3cdddbc..cccfa99e8bc 100644
--- a/editors/HexFiend/Portfile
+++ b/editors/HexFiend/Portfile
@@ -28,10 +28,6 @@ long_description \n\
     * Smooth scrolling. No separate pages - scroll like any text document.

 supported_archs x86_64
-macosx_deployment_target 10.8
-
-# The project only works with Xcode >= 8
-minimum_xcodeversions {11 8.0}

 patch.pre_args  -p1
 patchfiles      0001-xcode-Disable-Sparkle.patch
```

Can you apply that and increase the version filter at the bottom? There may be ways to make HexFiend work on 10.13 and lower, but for now it doesn't, so I'd rather have it fail quickly than waste users' time just to end up with a broken build.

File: editors/HexFiend/Portfile [hunk 2]
```diff
@@ -51,9 +47,9 @@ destroot {
     xinstall -m 644 ${worksrcpath}/License.txt ${destroot}${prefix}/share/doc/${name}
 }
 
-if {${os.platform} ne "darwin" || ${os.major} < 12} {
+if {${os.platform} ne "darwin" || ${os.major} < 18} {
     pre-fetch {
-        ui_error "${subport} @${version} only works with OS X 10.8 Mountain Lion or later."
-        return -code error "incompatible OS X version"
+        ui_error "${subport} @${version} only works with macOS 10.14 Mojave or later."
```
Comment (Tatsh) [inline editors/HexFiend/Portfile:52]: On this line, should it be `${subport}` or something else now that there are no subports? Or does it still work like this?

Comment (neverpanic) [reply editors/HexFiend/Portfile:52]: `$subport` will equal `$name`, but it will still be set, so no need to change that.

**Review by neverpanic — APPROVED** [review]
