### PR TITLE
love-11: fix build on macOS <10.12

### PR DESCRIPTION
**Pull request by aeiouaeiouaeiouaeiouaeiouaeiou**
* blacklist clang < 900

###### Type(s)

- [ ] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6.8 10K549 x86_64
Xcode 3.2.6 10M2518

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [x] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [x] tried a full install with `sudo port -vst install`?
- [x] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by ryandesign** [comment]
I see the problem you were trying to solve was:

```
common/macosx.mm:104:7: error: unexpected '@' in program
                if (@available(macOS 11.0, *))
                    ^
1 error generated.
```

Unfortunately, it appears to only solve it on Mac OS X 10.6. It doesn't solve it for 10.8–10.11 where the error is now:

```
Undefined symbols for architecture x86_64:
  "__availability_version_check", referenced from:
      ___isPlatformVersionAtLeast in libclang_rt.osx.a(os_version_check.c.o)
      __initializeAvailabilityCheck in libclang_rt.osx.a(os_version_check.c.o)
ld: symbol(s) not found for architecture x86_64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

For some reason the build already succeeded on 10.7 before this change.

There's only two places in the code that the new `@available` syntax is used, and only one of them on macOS, so I might be inclined to patch it rather than trying to make `@available` work on older systems.
