### PR TITLE
oath-toolkit: update to 2.6.11, fix build on < 10.7

### PR DESCRIPTION
**Pull request by barracuda156**
#### Description

Update, fix

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.6
Xcode 3.2

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?
- [ ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

### CODE REVIEW

**Comment by barracuda156** [comment]
```
  global.c:164:3: error: call to undeclared library function 'free' with type 'void (void *)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    free (ptr);
    ^
  global.c:164:3: note: include the header <stdlib.h> or explicitly provide a declaration for 'free'
  1 warning and 1 error generated.
```

Will fix this.

**Comment by reneeotten** [comment]
@barracuda156 are you working on this? If not, please close the PR until you had time to do so.

**Comment by barracuda156** [comment]
Let someone else fix stuff for systems I am not interested in.
