### PR TITLE
cctools 949.0.1 update

### PR DESCRIPTION
**Pull request by kencu**
###### Type(s)

- [ ] bugfix
- [x] enhancement
- [ ] security fix

###### Tested on

macOS 10.14.6 18G4032
Xcode 11.3.1 11C504 

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL?

- [x] checked your Portfile with `port lint`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by kencu** [comment]
This is an early build still, for broader testing amongst interested parties. So far only built on 10.14, and has undergone minimal testing to date. Please don't commit this at present -- it needs to build on every system, 10.4 PPC TIger to 10.15 Catalina before it can be committed.

**Comment by kencu** [comment]
And -- not going to be so simple any more:
```
../writeout.c:146:10: warning: implicit declaration of function 'clock_gettime' is invalid in C99 [-Wimplicit-function-declaration]
            if (clock_gettime(CLOCK_REALTIME, &toc_timespec)) {
                ^
../writeout.c:146:24: error: use of undeclared identifier 'CLOCK_REALTIME'
            if (clock_gettime(CLOCK_REALTIME, &toc_timespec)) {
                              ^
../writeout.c:298:17: warning: implicit declaration of function 'utimensat' is invalid in C99 [-Wimplicit-function-declaration]
                time_result = utimensat(AT_FDCWD, output, times, 0);
                              ^
../writeout.c:298:27: error: use of undeclared identifier 'AT_FDCWD'
                time_result = utimensat(AT_FDCWD, output, times, 0);
                                        ^
```

**Comment by kencu** [comment]
We can't (I don't think...) use legacysupport here -- well maybe we can, if we can sort out the bootstrapping issues -- but if we can't, we can probably copy in the parts we need, either into libstuff, or just patch it into the file that is looking for it.

**Comment by kencu** [comment]
this remains a WIP while we sort out builds on older systems

**Comment by kencu** [comment]
Hmm. This fails on Xcode 8.3 because the version of clang in 8.3 doesn't fully support the __builtin_available macOS setting.... Will have to come up with a workaround for that. And it also fails on 10.4 at present (10.5 not yet tested). I'm trying to avoid a bootstrap version of cctools, so I'll see if I can get this to build on 10.4 and 10.5 with the default system compiler.

**Comment by kencu** [comment]
I'll come back to this.
