### PR TITLE
KeePassXC-devel: update to latest devel & update patch

### PR DESCRIPTION
**Pull request by tenzap**
Update patch to fix build on macos

Fixes these build errors on macos 10.8

/src/touchid/TouchID.mm:132:5: error: unknown type name 'SecAccessControlCreateFlags'
/src/touchid/TouchID.mm:148:4: error: use of undeclared identifier 'SecAccessControlRef'

Fix build when built with Qt5.6 (used on macos 10.7)

###### Type(s)

- [x] bugfix
- [ ] enhancement
- [ ] security fix

###### Tested on

macOS 10.15.7 19H2026 x86_64
Command Line Tools 12.4.0.0.1.1610135815

Builds on 10.15 but couldn't test on 10.8, 10.7...

###### Verification 
Have you

- [x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ ] checked your Portfile with `port lint --nitpick`?
- [ ] tried existing tests with `sudo port test`?
- [ ] tried a full install with `sudo port -vst install`?
- [ ] tested basic functionality of all binary files?

### CODE REVIEW

**Comment by tenzap** [comment]
Any news on this? I would like to check that it builds fine on older macos wireless

**Comment by tenzap** [comment]
Any news here?

I would like to check if the patches resolve the build of keepassxc-devel on older Macs, so that i can use them in the update of keepassxc to latest upstream stable (2.7.4)

Thanks
